### ISSUE TITLE
Docs re-org/enhancements for ZNE

### ISSUE THREAD

**Issue by crazy4pi314** [unitaryfund/mitiq#1000]
Issue Description
-----------------

As a part of #908, and as specified by the [RFC](https://docs.google.com/document/d/13un5TZPknSOhmOBkrL2rsofjGfdp2jDnd-DywLpGFPc/edit#heading=h.mckr847qq60k) we want to add a general concepts section to the docs about how ZNE works in Mitiq.

**Comment by nathanshammah** [comment]
Shall we try to meet next week (@crazy4pi314 @purva-thakre @Misty-W) to try to split up existing content and work on it in a way that tries to harmonize the work of many authors? Even just knowing what existing text may be split up in which of the 5 sections will help.

**Comment by purva-thakre** [comment]
It's not much at the moment but here's a brief outline of what I have in mind. We can discuss more and make changes on Tuesday. Here's [a link to the Google Doc](https://docs.google.com/document/d/1am4P6DoHxMeiokcqfc8uSpPpuInNtfysi68G7irF47Y/edit?usp=sharing).
