### ISSUE TITLE
Decide a convention for titles and file names in users guide

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#1013]
As part of the documentation reorganization, the users guide is being refurbished. See https://github.com/unitaryfund/mitiq/projects/6, https://github.com/unitaryfund/mitiq/issues/908 and [RFC](https://docs.google.com/document/d/13un5TZPknSOhmOBkrL2rsofjGfdp2jDnd-DywLpGFPc/edit#).

For techniques, the accepted proposal plans to have many short `.myst` files. The proposed table of contents with this regard in the RFC is as follows:

1. How do I use this technique?
-- Absolute basics. Just show how to run `execute_with_technique`.
2. When should I use this technique?
-- A simple example where the technique improves performance.
3. What additional options are available?
-- E.g., the noise scaling method in ZNE, precision in PEC, or ansatz in CDR.
4. What happens when I use this technique?
-- The “lower-level” documentation. E.g., for ZNE, circuits are folded then executed, then results are extrapolated.
5. Who thought of this? Why does it work? And who’s using it?
-- A “theory-based” notebook primarily with text and mathematics rather than code.
-- References to original literature.
-- References to benchmarks and example uses in literature.

## Titles
Do we want to keep the titles as questions as they are now?
If so, especially 5. could be shortened and modified

## Files names
Currently in the #1004 draft for PEC, the files are called `guide/guide-pec-1.myst` etc. I have two proposals:

1. Remove the `guide-` part in the tittle (is a convention I introduced first I think, but since it's in the `guide` folder, it seems unnecessary)
2. Having the numbering is useful, I'd just add something a bit more expressive to the files names. It helps with the URL and especially if someone is navigating the folder from Jupyter Notebook. 

## References
We already have a reference section for the whole documentation. At the cost of making the last file a bit less self-consistent, but in order to avoid unnecessary duplication, I propose to simply use the current formalism to refer to the bibliography, i.e. `:cite:`Title` ` etc. So file 5 contains a discussion but the articles are properly linked in the bibliography only, at https://mitiq.readthedocs.io/en/latest/zz_bibliography.html.

**Comment by nathanshammah** [comment]
The current proposal is to use this names for titles:
```
How do I use this [technique name]?
-- Absolute basics. Just show how to run execute_with_technique.
When should I use this [technique name]?
-- A simple example where [technique name] improves performance.
What additional options are available?
-- E.g., the noise scaling method in ZNE, precision in PEC, or ansatz in CDR.
What happens when I use [technique name]?
-- The “lower-level” documentation. E.g., for ZNE, circuits are folded then executed, then results are extrapolated.
Who thought of this? Why does it work? And who’s using it?
-- A “theory-based” notebook primarily with text and mathematics rather than code.
-- References to original literature (using the `:cite:` directive to generate a single bibliography for the full document).
-- References to benchmarks and example uses in literature  (using the `:cite:` directive to generate a single bibliography for the full document).
```
The proposal for the names of the files is
```
guide/[technique-acronym]-1-intro.myst
guide/[technique-acronym]-2-example.myst
guide/[technique-acronym]-3-options.myst
guide/[technique-acronym]-4-low-level.myst
guide/[technique-acronym]-5-theory.myst
```
Example: guide/pec-5-theory.myst.

Please comment here if you have objections, or just like the comment if you agree @qryan @andreamari @crazy4pi314 @Misty-W @purva-thakre @L-P-B  (and all involved in rewriting the docs).

**Comment by andreamari** [comment]
For the second file names I would propose:
guide/[technique-acronym]-2-use-case.myst
to avoid confusion with the other examples of the docs.

The rest LGTM

**Comment by andreamari** [comment]
The question-style titles are fine for me. 
To make the last one "Who thought of this? Why does it work? And who’s using it?" shorter we could use:
- "Why does it work?" or "What is the theory behind [technique name]?".
