### ISSUE TITLE
Docs build sometime fail on RTD

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#1014]
Docs are failing on read the docs for both the latest release and stable release, v. 011. A look at the build logs says that they were killed by RTD due to excessive time to build, 926 seconds.

**Comment by rmlarose** [comment]
This needs more details to be made actionable. Do you know why RTD sometimes times out?

**Comment by nathanshammah** [comment]
The title is now updated. The latest failing build log can be found here: https://readthedocs.org/projects/mitiq/builds/15173588/
It cites `Command killed due to excessive memory consumption` and the last file listed in the log not labeled as a successful build is `Executing: /home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/stable/docs/source/guide/guide-observables.myst
`
