### ISSUE TITLE
Test code CI broken due to linkcheck

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#1016]
The current master CI test for testcode are broken, seemingly due to a `linkcheck` issue. Note that the test was passing on the PR #944. 
It may be this item below, labeled al "broken"
**(    contributing: line   15) broken    https://www.asmeurer.com/git-workflow/ - HTTPSConnectionPool(host='www.asmeurer.com', port=443): Max retries exceeded with url: /git-workflow/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe6c84d3250>: Failed to establish a new connection: [Errno -2] Name or service not known'))**
```

(guide/guide-error-mitigation: line  289) ok        https://www.pygsti.info/
( code_of_conduct: line   70) ok        https://www.contributor-covenant.org
(contributing_docs: line   25) ok        https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html
(contributing_docs: line  235) ok        https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html
(          readme: line   92) ok        https://www.rigetti.com/uploads/Logos/logo-rigetti-gray.jpg
(          apidoc: line   22) ok        https://www.sciencedirect.com/science/article/abs/pii/S0377042719303449
(contributing_docs: line   10) ok        https://www.sphinx-doc.org/en/master/usage/installation.html
(          readme: line  102) redirect  https://www.semanticscholar.org/paper/Mitiq%3A-A-software-package-for-error-mitigation-on-LaRose-Mari/dc55b366d5b2212c6df8cd5c0bf05bab13104bd7#citing-papers - permanently to https://www.semanticscholar.org/paper/Mitiq%3A-A-software-package-for-error-mitigation-on-LaRose-Mari/a691edbe01caa0ac93405a5d50ab8bb1b416d667#citing-papers
build finished with problems.
make[1]: *** [Makefile:20: linkcheck] Error 1
make[1]: Leaving directory '/home/runner/work/mitiq/mitiq/docs'
make: *** [Makefile:47: linkcheck] Error 2
Error: Process completed with exit code 2.
```

**Comment by andreamari** [comment]
That web page  https://www.asmeurer.com/git-workflow/ doesn't exists anymore. The associated GitHub repo still exists.
So I would propose this fix, untill the web page will reappear: https://github.com/unitaryfund/mitiq/pull/1018/commits/2039dd96cf9b4f1cb3661aa24dae6cb277d0e4f3

**Comment by andreamari** [comment]
Actually https://www.asmeurer.com/git-workflow/ is up again!  

The magic of open-source: https://github.com/asmeurer/git-workflow/issues/11  :-)

**Comment by nathanshammah** [comment]
Tests are again failing on master due to linkcheck.

**Comment by natestemen** [comment]
Doc builds are failing again (https://github.com/unitaryfund/mitiq/runs/6623525872), so am going to reopen this.

I've run `make linkcheck` locally and despite only seeing `ok`, `redirect` and a few `-ignored-`, the program finishes with
```
build finished with problems, 1 warning.
make[1]: *** [linkcheck] Error 1
make: *** [linkcheck] Error 2
```

Is there a way to run this program to only show failing links?

**Comment by natestemen** [comment]
Upon further consideration, this is another case of https://github.com/unitaryfund/mitiq/issues/1308. Sorry for the notifications. Closing.
