### ISSUE TITLE
Automate contributors list

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#1036]
All contributors is nice but hard to keep updated. Unless there is strong opposition, let's remove this in favor of the [automated GH tool](https://github.com/unitaryfund/mitiq/graphs/contributors).

**Comment by nathanshammah** [comment]
It has been decided at the Mitiq meeting to opt for an automation of the all-contributors tool. This could be done with a Github Action.

**Comment by natestemen** [comment]
I'm in strong favor of removing allcontributors as well. IMO it's a larger burden than benefit. Reopening.

> It has been decided at the Mitiq meeting to opt for an automation of the all-contributors tool. This could be done with a Github Action.

Are there repos you know of that do this?

**Comment by natestemen** [comment]
After searching around some more, I've found the [allcontributors CLI](https://allcontributors.org/docs/en/cli/overview) bun unfortunately it does not provide any ongoing automation. As far as I can tell, it's the same amount of work as using the bot through comments. (which we are not very good at)

I have not found any projects using GH actions to automate this. Any objections to remove the bot? @nathanshammah @Misty-W
