### ISSUE TITLE
Add GHZ circuits to benchmarks

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#1058]
Currently `mitiq.benchmarks` contains RB and mirror circuits, and needs more benchmark circuits.

GHZ circuits provide natural scaling with the number of qubits, are structured (in contrast to random as with RB and mirror circuits), and have additional nice features for benchmarking error mitigation:

- GHZ circuits result in idle qubits for which it is natural to apply dynamical decoupling.
- GHZ circuits should only produce two bitstrings for which it is natural to apply post-selection.

GHZ circuits were used in https://arxiv.org/abs/2108.09197 as a benchmark, see Fig. 2(c) - (d). Also see this paper (page 3, left column, 3rd paragraph) for a nice discussion of expected results for assumed (but realistic) error models with local/non-local observables.

**Comment by rmlarose** [comment]
Thoughts or objections @andreamari?

**Comment by andreamari** [comment]
No objections.
GHZ circuits are interesting since, as you said, are very non-random and very empty.

**Comment by nathanshammah** [comment]
+1 for GHZ.

**Comment by Rahul-Mistri** [comment]
Can I take a crack at this?

**Comment by nathanshammah** [comment]
Hi @Rahul-Mistri, could you come to the Mitiq community call to discuss more? It's today (as every Friday) at 6pm CET/9am PT on the [Unitary Fund Discord](http://discord.unitary.fund/).

**Comment by crazy4pi314** [comment]
Suggested docs:
https://mitiq.readthedocs.io/en/stable/examples/braket_mirror_circuit.html?highlight=generate%20mirrot#generate-mirror-circuit

**Comment by rmlarose** [comment]
Thanks @Rahul-Mistri, it's all yours!

You can check out https://github.com/unitaryfund/mitiq/blob/8f0523d6c4de623f9ac1354c145e3b836eb0632f/mitiq/benchmarks/mirror_circuits.py#L133-L140 for another benchmark function to get the general context.

The simplest function should look something like

```python
def generate_ghz_circuit(nqubits: int, return_type: Optional[str] = None) -> QPROGRAM:
    qubits = cirq.LineQubit.range(nqubits)
    circuit = cirq.Circuit(cirq.H.on(qubits[0]), [cirq.CNOT(qubits[i], qubits[i + 1]) for i in range(nqubits - 1)])
    return convert_from_mitiq(circuit, return_type)
```

You may wish to take the quantum computer topology (as a networkx graph similar to the mirror circuits benchmark function) into account, but I think the above implementation is sufficient for now.

**Comment by andreamari** [comment]
@allcontributors please add @Rahul-Mistri for tests and code
