### ISSUE TITLE
Read the docs not updating latest documentation

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#1072]
Issue Description
-----------------

Read the docs is not updating latest documentation at this moment. The ZNE docs are not updated. 

How to Reproduce
----------------
See
https://mitiq.readthedocs.io/en/latest/guide/guide.html
that is not matching the latest file structure.

**Comment by andreamari** [comment]
Seems related to the final Latex build. Indeed, all readthedocs works in all current PR previews, in which the pdf is not produced. 
This is the last message:

<details>
[rtd-command-info] start-time: 2022-01-06T15:09:11.094087Z, end-time: 2022-01-06T15:09:33.417737Z, duration: 22, exit-code: 0
/home/docs/checkouts/readthedocs.org/user_builds/mitiq/envs/latest/bin/python -m sphinx -b latex -D language=en -d _build/doctrees . _build/latex
Running Sphinx v3.5.4
loading translations [en]... done
making output directory... done
loading pickled environment... checking bibtex cache... up to date
done
myst v0.13.7: MdParserConfig(renderer='sphinx', commonmark_only=False, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, update_mathjax=False, enable_extensions=['amsmath', 'colon_fence', 'deflist', 'dollarmath', 'html_image', 'smartquotes'], disable_syntax=[], url_schemes=('http', 'https', 'mailto'), heading_anchors=None, html_meta=[], footnote_transition=True, substitutions=[], sub_delimiters=['{', '}'])
building [mo]: targets for 0 po files that are out of date
building [latex]: all documents
updating environment: executing outdated notebooks... Executing: /home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/latest/docs/source/examples/vqe-pyquil-demo.myst
Executing: /home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/latest/docs/source/examples/pyquil_demo.myst
done
0 added, 0 changed, 0 removed
WARNING: Execution Failed: /home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/latest/docs/source/examples/vqe-pyquil-demo.myst
WARNING: Execution Failed: /home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/latest/docs/source/examples/pyquil_demo.myst
looking for now-outdated files... none found
processing mitiq.tex... index readme guide/guide guide/guide-getting-started guide/guide-executors guide/guide-observables guide/zne guide/zne-1-intro guide/zne-2-use-case guide/zne-3-options guide/zne-4-low-level guide/zne-5-theory guide/pec guide/pec-1-intro guide/pec-2-use-case guide/pec-3-options guide/pec-4-low-level guide/pec-5-theory guide/guide-cdr guide/guide-error-mitigation examples/examples examples/braket_mirror_circuit examples/ibmq-backends examples/pyquil_demo examples/vqe-pyquil-demo examples/simple_landscape examples/maxcut-demo examples/cdr_api examples/hamiltonians examples/mitiq-paper/mitiq-paper-codeblocks apidoc toc_contributing contributing contributing_docs examples/template release code_of_conduct changelog zz_bibliography 
resolving references...
/home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/latest/README.md:4: WARNING: a suitable image for latex builder not found: ['image/svg+xml'] (https://img.shields.io/badge/all_contributors-28-orange.svg?style=flat-square)
/home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/latest/README.md:6: WARNING: a suitable image for latex builder not found: ['image/svg+xml'] (https://github.com/unitaryfund/mitiq/workflows/build/badge.svg)
/home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/latest/README.md:6: WARNING: a suitable image for latex builder not found: ['image/svg+xml'] (https://readthedocs.org/projects/mitiq/badge/?version=stable)
/home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/latest/README.md:6: WARNING: a suitable image for latex builder not found: ['image/svg+xml'] (https://codecov.io/gh/unitaryfund/mitiq/branch/master/graph/badge.svg)
/home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/latest/README.md:6: WARNING: a suitable image for latex builder not found: ['image/svg+xml'] (https://badge.fury.io/py/mitiq.svg)
/home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/latest/README.md:6: WARNING: a suitable image for latex builder not found: ['image/svg+xml'] (https://img.shields.io/badge/arXiv-2009.04417-%3CCOLOR%3E.svg)
/home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/latest/README.md:6: WARNING: a suitable image for latex builder not found: ['image/svg+xml'] (https://static.pepy.tech/personalized-badge/mitiq?period=total&units=international_system&left_color=black&right_color=green&left_text=Downloads)
/home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/latest/README.md:6: WARNING: a suitable image for latex builder not found: ['image/svg+xml'] (https://img.shields.io/badge/GitHub-5C5C5C.svg?logo=github)
/home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/latest/README.md:6: WARNING: a suitable image for latex builder not found: ['image/svg+xml'] (https://img.shields.io/badge/Supported%20By-Unitary%20Fund-FFFF00.svg)
/home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/latest/README.md:6: WARNING: a suitable image for latex builder not found: ['image/svg+xml'] (https://img.shields.io/badge/dynamic/json?color=blue&label=Discord&query=approximate_presence_count&suffix=%20online.&url=https%3A%2F%2Fdiscord.com%2Fapi%2Finvites%2FJqVGmpkP96%3Fwith_counts%3Dtrue)
/home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/latest/README.md:6: WARNING: a suitable image for latex builder not found: ['image/svg+xml'] (https://mybinder.org/badge_logo.svg)
/home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/latest/docs/CONTRIBUTING_DOCS.md:5: WARNING: a suitable image for latex builder not found: ['image/svg+xml'] (https://github.com/unitaryfund/mitiq/workflows/Python%20Build/badge.svg?branch=master)
/home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/latest/docs/CONTRIBUTING_DOCS.md:5: WARNING: a suitable image for latex builder not found: ['image/svg+xml'] (https://badge.fury.io/py/mitiq.svg)
/home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/latest/docs/CONTRIBUTING_DOCS.md:5: WARNING: a suitable image for latex builder not found: ['image/svg+xml'] (https://img.shields.io/badge/Supported%20By-UNITARY%20FUND-brightgreen.svg?style=for-the-badge)
/home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/latest/README.md:4: WARNING: a suitable image for latex builder not found: ['image/svg+xml'] (https://img.shields.io/badge/all_contributors-28-orange.svg?style=flat-square)
/home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/latest/README.md:6: WARNING: a suitable image for latex builder not found: ['image/svg+xml'] (https://github.com/unitaryfund/mitiq/workflows/build/badge.svg)
/home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/latest/README.md:6: WARNING: a suitable image for latex builder not found: ['image/svg+xml'] (https://readthedocs.org/projects/mitiq/badge/?version=stable)
/home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/latest/README.md:6: WARNING: a suitable image for latex builder not found: ['image/svg+xml'] (https://codecov.io/gh/unitaryfund/mitiq/branch/master/graph/badge.svg)
/home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/latest/README.md:6: WARNING: a suitable image for latex builder not found: ['image/svg+xml'] (https://badge.fury.io/py/mitiq.svg)
/home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/latest/README.md:6: WARNING: a suitable image for latex builder not found: ['image/svg+xml'] (https://img.shields.io/badge/arXiv-2009.04417-%3CCOLOR%3E.svg)
/home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/latest/README.md:6: WARNING: a suitable image for latex builder not found: ['image/svg+xml'] (https://static.pepy.tech/personalized-badge/mitiq?period=total&units=international_system&left_color=black&right_color=green&left_text=Downloads)
/home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/latest/README.md:6: WARNING: a suitable image for latex builder not found: ['image/svg+xml'] (https://img.shields.io/badge/GitHub-5C5C5C.svg?logo=github)
/home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/latest/README.md:6: WARNING: a suitable image for latex builder not found: ['image/svg+xml'] (https://img.shields.io/badge/Supported%20By-Unitary%20Fund-FFFF00.svg)
/home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/latest/README.md:6: WARNING: a suitable image for latex builder not found: ['image/svg+xml'] (https://img.shields.io/badge/dynamic/json?color=blue&label=Discord&query=approximate_presence_count&suffix=%20online.&url=https%3A%2F%2Fdiscord.com%2Fapi%2Finvites%2FJqVGmpkP96%3Fwith_counts%3Dtrue)
/home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/latest/README.md:6: WARNING: a suitable image for latex builder not found: ['image/svg+xml'] (https://mybinder.org/badge_logo.svg)
done
writing... /home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/latest/README.md:1: WARNING: document title is not a single Text node
done
copying images... [  3%] https://github.com/unitaryfund/mitiq/blob/master/docs/source/img/mitiq-logo.png?raw=true
copying images... [  7%] https://raw.githubusercontent.com/quantumlib/Cirq/master/docs/images/Cirq_logo_color.png
copying images... [ 11%] https://qiskit.org/images/qiskit-logo.png
copying images... [ 14%] https://www.rigetti.com/uploads/Logos/logo-rigetti-gray.jpg
copying images... [ 18%] https://a0.awsstatic.com/libra-css/images/logos/aws_logo_smile_1200x630.png
copying images... [ 22%] https://pennylane.ai/img/xanadu_x.png
copying images... [ 25%] img/factory-plot_fit.png
copying images... [ 29%] _build/jupyter_execute/guide/zne-3-options_42_0.png
copying images... [ 33%] img/zne_workflow2_steps.png
copying images... [ 37%] _build/jupyter_execute/guide/zne-4-low-level_13_0.png
copying images... [ 40%] img/zne_global_folding.png
copying images... [ 44%] img/zne_local_folding.png
copying images... [ 48%] img/zne_pulse_stretching.png
copying images... [ 51%] img/pec_workflow2_steps.png
copying images... [ 55%] img/cdr_workflow2_steps.png
copying images... [ 59%] img/cdr_diagram2.png
copying images... [ 62%] _build/jupyter_execute/examples/braket_mirror_circuit_12_0.png
copying images... [ 66%] _build/jupyter_execute/examples/braket_mirror_circuit_26_0.png
copying images... [ 70%] _build/jupyter_execute/examples/simple_landscape_13_0.png
copying images... [ 74%] _build/jupyter_execute/examples/simple_landscape_17_0.png
copying images... [ 77%] _build/jupyter_execute/examples/simple_landscape_23_0.png
copying images... [ 81%] _build/jupyter_execute/examples/maxcut-demo_48_1.png
copying images... [ 85%] _build/jupyter_execute/examples/maxcut-demo_51_1.png
copying images... [ 88%] _build/jupyter_execute/examples/maxcut-demo_55_2.png
copying images... [ 92%] img/vqe-cirq-pauli-sum-mitigation-plot.png
copying images... [ 96%] img/unitary_fund_logo.png
copying images... [100%] _build/jupyter_execute/examples/template_9_1.png

copying TeX support files... copying TeX support files...
done
build succeeded, 28 warnings.

The LaTeX files are in _build/latex.
Run 'make' in that directory to run these through (pdf)latex
(use `make latexpdf' here to do that automatically).
WARNING: Missing searchtools: /home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/latest/docs/source/_build/latex/_static/searchtools.js

[rtd-command-info] start-time: 2022-01-06T15:09:37.049257Z, end-time: 2022-01-06T15:09:37.119863Z, duration: 0, exit-code: 0
cat latexmkrc
$latex = 'latex ' . $ENV{'LATEXOPTS'} . ' %O %S';
$pdflatex = 'pdflatex ' . $ENV{'LATEXOPTS'} . ' %O %S';
$lualatex = 'lualatex ' . $ENV{'LATEXOPTS'} . ' %O %S';
$xelatex = 'xelatex --no-pdf ' . $ENV{'LATEXOPTS'} . ' %O %S';
$makeindex = 'makeindex -s python.ist %O -o %D %S';
add_cus_dep( "glo", "gls", 0, "makeglo" );
sub makeglo {
 return system( "makeindex -s gglo.ist -o '$_[0].gls' '$_[0].glo'" );
}
</details>

**Comment by nathanshammah** [comment]
The build on RTD/latest has not been completed since the merge of #1075, but the docs from the #1075 PR render correctly:
https://mitiq--1075.org.readthedocs.build/en/1075/guide/zne.html

**Comment by nathanshammah** [comment]
The tests in #0175 seem to be killed due to memory consumption and timeout. 
What if we cache notebooks?
Also, now we could directly use `jupyter-book` in RTD. 
https://jupyterbook.org/content/execute.html

**Comment by andreamari** [comment]
Hi @nathanshammah, actually the tests in #1077 show that the there is a latex problem localized zne-3-options.myst that I am trying to fix. (See description of #1077)

Memory consumption in RTD happens when there simultaneous commits, but it is unrelated to the present issue.

**Comment by nathanshammah** [comment]
Reopening this, we should close only once https://mitiq.readthedocs.io/en/latest/guide/guide.html shows the latest docs.

**Comment by nathanshammah** [comment]
Now [showing up](https://mitiq.readthedocs.io/en/latest/guide/zne.html) correctly on RTD.
