### ISSUE TITLE
Idle qubits get lost in conversions

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#1085]
## Description

[Originally raised in [discord](https://discord.com/channels/764231928676089909/773957956659052605/928804814475915364).] 

Any Qiskit (and presumably other frontends) circuit with idle qubits produces unexpected behavior in round-trip (Qiskit -> Cirq -> Qiskit) conversions - namely, the idle qubits are discarded, causing operations to appear out of order or on the wrong qubits. E.g.:

```python
import qiskit
from mitiq.interface import convert_from_mitiq, convert_to_mitiq

circuit = qiskit.QuantumCircuit(3); circuit.x([0, 2]); print(circuit)
#      ┌───┐
# q_0: ┤ X ├
#      └───┘
# q_1: ─────
#      ┌───┐
# q_2: ┤ X ├
#      └───┘

print(convert_from_mitiq(*convert_to_mitiq(circuit)))
#      ┌───┐
# q_0: ┤ X ├
#      ├───┤
# q_1: ┤ X ├
#      └───┘
```

This happens because a Cirq circuit is a collection of operations; since there is no operation on the `q_1` qubit, there is no `q_1` qubit:

```python
cirq_circuit, _ = convert_to_mitiq(circuit)
print(cirq_circuit)
# q_0: ───X───

# q_2: ───X───

print(cirq_cirq.all_qubits())
# frozenset({cirq.NamedQubit('q_0'), cirq.NamedQubit('q_2')})
```

(Note: In converting back to Qiskit, the qubits get renamed to `q_0` and `q_1`.)

## Proposed fix

This is another fundamental difference between certain packages and, in my opinion, should be handled as a special case after atomic conversions in https://github.com/unitaryfund/mitiq/blob/2c5686be0fdfc3975675c4c0fbf26b5c92bd04e8/mitiq/interface/conversions.py#L235-L293

Namely, adding a check if there are idle qubits and re-inserting them if so.

**Comment by rmlarose** [comment]
Looking for one maintainer LGTM on proposed fix and/or alternate proposed fixes.

**Comment by willzeng** [comment]
LGTM though am adding other maintainers to get a quick review from folks closer

**Comment by vprusso** [comment]
LGTM as well. I am curious if "Frontend -> Cirq -> Frontend" conversions for frontends other than Qiskit also cause an ordering issue. Out of scope for this issue, but it would be worth:

- Verifying that ordering is respected for other frontends
- Add some test cases to ensure ordering for Qiskit -> Cirq -> Qiskit is respected post-fix.

**Comment by andreamari** [comment]
LGTM. I am not sure this is a _priority0_ issue (high-priority label) but the proposed fix seems reasonable to me.
I agree with @vprusso that a similar issue may also happen for other frontends. The fix would be in any case frontend-specific I guess.

**Comment by rmlarose** [comment]
> I am curious if "Frontend -> Cirq -> Frontend" conversions for frontends other than Qiskit also cause an ordering issue.

The idle qubits issue is certainly there since that's a Cirq thing. Haven't seen ordering issues for other packages besides Qiskit, but its possible and should be tested more.

> I am not sure this is a _priority0_ issue (high-priority label) but the proposed fix seems reasonable to me.

I'll move to p1. It's definitely buggy behavior, but not common usage.

**Comment by andreamari** [comment]
As discussed in the Mitiq call, @Rahul-Mistri will look into this. Thanks!

**Comment by crazy4pi314** [comment]
@Rahul-Mistri do you still have time to work on this one? If not that's all good!

**Comment by Rahul-Mistri** [comment]
@rmlarose Could we chat sometime about this issue? I just have a few questions to ask the proposed fix

**Comment by rmlarose** [comment]
Sure, can you join the Mitiq meeting today @Rahul-Mistri?
