### ISSUE TITLE
Unitary folding methods does not work for sx gates (Qiskit)

### ISSUE THREAD

**Issue by amrit-11** [unitaryfund/mitiq#1092]
SX gates are part of the native gate set that are implemented by IBMQ devices, but when I try to scale errors by unitary folding using fold_global method or even folding from left or right, it throws the exception:

QasmException: Unknown gate "sx" at line 5

This is followed by a CircuitConversionError.

CircuitConversionError: Circuit could not be converted to an internal Mitiq circuit. This may be because the circuit contains custom gates or Pragmas (pyQuil). If you think this is a bug or that this circuit should be supported, you can open an issue at https://github.com/unitaryfund/mitiq.

The circuit I have been trying to fold is given below:

'
from mitiq import zne as mz
from qiskit import *
qr = QuantumRegister(n)
qc_basis = QuantumCircuit(qr)
qc_basis.sx([0,2,4])
qc_basis.cx([0,2], [1,3])
qc_basis.cx([2,4], [1,3])
qc_basis.rz(np.pi+beta, 0)
qc_basis.rz(np.pi-beta, 2)
qc_basis.sx([0,2,4])
qc_basis.measure_all()
qc_folded = mz.scaling.fold_global(qc_basis, scale_factor=3.)
`

**Comment by rmlarose** [comment]
Thanks @amrit-11 for reporting. We are aware of this issue and tracking it in #1073, so I will close this one as a duplicate.

In the meantime, you can do `qiskit.transpile(qc_basis, basis_gates=["u1", "u2", "u3"])` and then you should be able to fold the circuit.
