### ISSUE TITLE
[unitaryhack-bounty] Improve H2 example

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#1094]
The current H2 example could be improved in two different aspects:

- [ ] The numerical values of the Hamiltonian coefficients _g_j(R)_ are hard-coded from data extracted from a paper. It would be nice to derive them using some chemistry package e.g.: [PySCF](https://pyscf.org/) or [OpenFermion](https://github.com/quantumlib/OpenFermion). Ideally (but only if not too complicated), it would be better to use the same Hamiltonian in order to reproduce the same results of the Mitiq paper. 
- [ ] Use a `mitiq.Observable` for the Hamiltonian, and just use `mitiq_cirq.compute_density_matrix` for the executor. See the docs for more details on how to define and use observables.

If you only fixed one of the two aspects, please don't close this issue but just mark the corresponding item in the above list.

**Comment by nathanshammah** [comment]
+1 for adding a bounty on UH.

**Comment by andreamari** [comment]
@obliviateandsurrender, thanks! Please note that there is already a PR by @lockwo for the same issue.
On the other hand, it is interesting that both of you solved the issue but in very different ways: @lockwo with OpenFermion and you with PennyLane. So we may decide to keep both examples!

Next week we'll discuss internally and let you know if we'll keep both examples and, if so, how it works with the unitaryhack bounty.

**Comment by andreamari** [comment]
Hi @obliviateandsurrender, I have some good news!
We discussed about this and decided to also keep your H2 example in addition to the previous one by @lockwo. 
If both PRs will be accepted and merged, both of you will the bounty!
