### ISSUE TITLE
Draft a MEP or RFC for Dynamical Decoupling.

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#1103]
### Description
This issue can be closed once we have a MEP/RFC for implementing Dynamical Decoupling (DD).
The document can drafted in the form of a shared google document and linked as a comment in the main issue related to DD #822.

For an example and a template, see the RFC linked  in #821.

### MEP document

Shared Google document on dynamical decoupling: 
https://docs.google.com/document/d/1cRwFCTn6kUjI1P0kNydtevxIYtE4r8Omd_iWK0Pe8qo/edit?usp=sharing

Note: The old [doc](https://docs.google.com/document/d/1_hASDgxvir2QNHCv6Yeo1z6Q1lYP2EGAV1CTn1Orps8/edit?usp=sharing) by @andreamari is superseded since its content now merged into the doc by @Aaron-Robertson linked above.

**Comment by Aaron-Robertson** [comment]
Here's the draft so far @andreamari https://docs.google.com/document/d/1cRwFCTn6kUjI1P0kNydtevxIYtE4r8Omd_iWK0Pe8qo/edit?usp=sharing

**Comment by andreamari** [comment]
Great @Aaron-Robertson I also shared a document in the description of this issue. Tomorrow we can try to merge things into a unique one.

**Comment by Aaron-Robertson** [comment]
Sounds good!

**Comment by Aaron-Robertson** [comment]
Per our offline conversation I updated the link I provided to merge yours in and do some cleanup on content order. Edits are welcome!

**Comment by crazy4pi314** [comment]
This will be accepted Tuesday Mar 2 unless there are further comments/blockers.

**Comment by andreamari** [comment]
Thanks @crazy4pi314, I thought the correct date was today February 22 instead of March 2, such that we could close this issue before the release which is planned for next Friday.

I noticed the date mismatch only now, so I propose we shift the "acceptance-unless-blockers-day" to tomorrow February 23.

**Comment by crazy4pi314** [comment]
@andreamari sorry! I was looking at the calendar during the meeting and got the current date wrong... Tomorrow is great 👍

**Comment by crazy4pi314** [comment]
Discussed and accepted! Thanks @andreamari and @Aaron-Robertson for the proposal 🎉

**Comment by nathanshammah** [comment]
Great work everyone for feedback and especially @Aaron-Robertson and @andreamari. Looking forward to begin prototyping this from the next Milestone.
