### ISSUE TITLE
Cannot call `execute_with_zne` with gate fidelities for folding

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#1125]
Folding functions support a [fidelities keyword argument](https://github.com/unitaryfund/mitiq/blob/master/mitiq/zne/scaling/folding.py#L531-L561), but there is no way to pass this information through via `zne.execute_with_zne`.

https://github.com/unitaryfund/mitiq/blob/c818e44858b401b45f1f09e021c49ba24c5dd4a1/mitiq/zne/zne.py#L67-L69

It would be nice to support this kwarg in `zne.execute_with_zne` so one doesn't have to call the folding function "manually" with a fidelities argument, then do the fitting separately.

**Comment by andreamari** [comment]
One can set the `fidelities` and other folding options to use with `execute_with_zne` as shown here:
https://mitiq.readthedocs.io/en/stable/guide/zne-3-options.html#running-zne-with-advanced-options

We often do similar things with the `executor` options.

But maybe this is not practical enough for the user?

**Comment by rmlarose** [comment]
I think that's fine and even preferable because that's the strategy for executor options as you note. I could've sworn there used to be an keyword arg for this, but maybe I'm mistaken.
