### ISSUE TITLE
ASV report as a part of docs

### ISSUE THREAD

**Issue by crazy4pi314** [unitaryfund/mitiq#1136]
We have setup ASV as a part of our testing pipelines, and it can generate benchmarking webpages like: https://pv.github.io/numpy-bench/

Is this something we want for Mitiq? It can also give diffs of benchmarks from commit to commit.

@rmlarose I think you were using this the most, thoughts?

**Comment by rmlarose** [comment]
+1 from me. I like the idea of expanding the current benchmarks and hosting the results online (whether in the documentation or on a separate page). asv makes it quite easy to do.

**Comment by crazy4pi314** [comment]
I think the first step for this is to separate out the running of ASV from the regular test suite, then have a separate action to trigger this part of the gh pages site to build.
