### ISSUE TITLE
Support latest version of Qiskit

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#1138]
Unlike other less-urgent software packages, supporting the latest versions of quantum libraries (Qiskit, PyQuil, PennyLane, Braket, etc.) is quite important for the usability of Mitiq.

The scope of this issue is to support the latest version of Qiskit in our `dev_requirements.txt` file.
In practice one should find a way to fix the tests that are failing in #1126.

**Comment by crazy4pi314** [comment]
This I think should be handled by #1164, we can close this when that's merged

**Comment by crazy4pi314** [comment]
Closed by #1195
