### ISSUE TITLE
Raise error if executor and observable are not compatible

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#1140]
Issue Description
-----------------

If an `executor` returns expectation values as `float` variables, Mitiq should always be used with `observable=None` (default),
since in this case the observable is implicitly defined and measured in the `executor`.

From a Discord discussion, it seems that no error is raised for incompatible settings.

Solution
-----------------

- Raise an error if the `observable` argument is not `None` and the executor doesn't return a `MeasurementLike`  result (bitstrings).

**Comment by Misty-W** [comment]
@andreamari is this the Discord conversation referenced in this issue: https://discord.com/channels/764231928676089909/773957956659052605/945976347937882172 ?

**Comment by andreamari** [comment]
> @andreamari is this the Discord conversation referenced in this issue:
Yes, thanks!
