### ISSUE TITLE
Add citiation file for the repo

### ISSUE THREAD

**Issue by crazy4pi314** [unitaryfund/mitiq#1154]
Issue Description
-----------------

Last year, GH added support for a citation file that then adds UI elements to the repo pages to help folks generate a citation for the project. Blog announcing: https://github.blog/2021-08-19-enhanced-support-citations-github/

Proposed Solution
-----------------

Add a `.cff` file for the mitiq paper.

Additional References
---------------------
Docs for the feature: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files#about-citation-files

**Comment by RubidgeCarrie** [comment]
Hi Sarah @crazy4pi314, I am still new to open-source so I decided to give this a try to start out. Please let me know if there is any additional information you want in the citation file.
