### ISSUE TITLE
Latest master merge failing

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#1155]
Upon merging #1151 that updated the version of the action via dependabot, the test-docs checks are failing. 
Not sure this is related, looking at the [log here](https://github.com/unitaryfund/mitiq/runs/5407556788?check_suite_focus=true) it seems to be due to `linkcheck`.

**Comment by andreamari** [comment]
It's due to the Discord link not working properly: https://discord.unitary.fund/
I assumed it was a temporary problem, but it is still broken.

Maybe @crazy4pi314 knows?

**Comment by crazy4pi314** [comment]
The link is not https, just http for the discord short link. Hope that helps!

**Comment by andreamari** [comment]
Link works now, problem self-solved :-)

**Comment by crazy4pi314** [comment]
I probably didn't realize at the time, but Discord and a lot of other major services have had outages over the last 36h...  Glad it fixed itself :)
