### ISSUE TITLE
Upgrade to numpy 1.23

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#1156]
Issue Description
-----------------
Check-type validation raises several errors in [type-arg] for missing ndarray. See discussion in #1118.

**Comment by Misty-W** [comment]
Removed #1156 from 0.15.0 milestone - solve #1214 in 0.15.0 milestone instead (incremental fix).

**Comment by natestemen** [comment]
Upgrading numpy to a version greater than 1.21 will also fix the one security vulnerability we have open.
