### ISSUE TITLE
Add built-in dynamical decoupling sequences for the ddd technique.

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#1162]
Implement the built-in digital dynamical decoupling sequences via `rules` (e.g. xx_rule, xy_rule) described in the [RFC for dynamical decoupling](https://docs.google.com/document/d/1cRwFCTn6kUjI1P0kNydtevxIYtE4r8Omd_iWK0Pe8qo/edit?usp=sharing). 

They are necessary to determine how to fill slack windows (holes with idling qubits) in a circuit.

Implementation ideas with pseudo-code are present in the [RFC](https://docs.google.com/document/d/1cRwFCTn6kUjI1P0kNydtevxIYtE4r8Omd_iWK0Pe8qo/edit?usp=sharing) but, of course, a different approach can be used as long as general planned features are achieved:

1. easy to use
2. easy to customize for the user
3. compatible with non-deterministic sequences

**Comment by Aaron-Robertson** [comment]
@andreamari this one looks like a good candidate for next steps on `ddd`? I'm happy to pick it up for milestone `0.15`!

**Comment by andreamari** [comment]
Sure, thanks @Aaron-Robertson!
