### ISSUE TITLE
Add support to the GH pages documentation pipeline for selecting different mitiq versions

### ISSUE THREAD

**Issue by crazy4pi314** [unitaryfund/mitiq#1168]
Pre-Request Checklist
---------------------

- [x] I checked to make sure that this feature has not already been requested.

Issue Description
-----------------

One of the main features that RTDs provides is versioning of project documentation they host.
This is not generally available for basic sphinx workflows that host docs on GitHub pages.

We could use this project/sphinx plugin has support for this feature:
https://pydata-sphinx-theme.readthedocs.io/en/v0.8.0/user_guide/configuring.html#add-a-dropdown-to-switch-between-docs-versions

**Comment by andreamari** [comment]
@crazy4pi314,  does it make sense to label this with `uhbounty` ?

**Comment by crazy4pi314** [comment]
Yeah, great idea @andreamari 💖🙏

**Comment by nathanshammah** [comment]
+1 for making it a uh bounty
