### ISSUE TITLE
Avoid ignoring silently bad inputs in `fold_gates_at_random`

### ISSUE THREAD

**Issue by nelimee** [unitaryfund/mitiq#1179]
Pre-Request Checklist
---------------------

- [x] I checked to make sure that this feature has not already been requested.

Issue Description
-----------------

The following code
```py
from qiskit import QuantumCircuit
from mitiq.zne.scaling.folding import fold_gates_at_random

circuit = QuantumCircuit(1)
circuit.rx(0, 0)

fold_gates_at_random(circuit, scale_factor=2, fidelities={"invalid_gate_name": 0.06, "rx": 0.1})
```
does not:
1. Warn the user that `invalid_gate_name` and `rx` are not in the valid gates that are allowed in `fidelities` (see the [documentation](https://mitiq.readthedocs.io/en/latest/apidoc.html#mitiq.zne.scaling.folding.fold_gates_at_random) to get this list).
2. Warn the user that, because `rx` is not in the valid gates, the weight that will be used internally by `mitiq` is **not** the expected `1 - 0.1` (i.e. the infidelity, as written in the documentation) but rather the default weight that is here `1 - 0.99**n = 0.01`.

Proposed Solution
-----------------

In order of personal preference:
1. Ideally, the restriction on the allowed gate names that are allowed in `fidelities` should be removed. I am not very familiar with `mitiq` internals but I suspect that this restriction is related to an internal implementation detail of `mitiq` and it might not be easy to remove.
2. Raise an exception if `fidelities` contains gates that are not allowed.
3. Raise an exception if `fidelities` contains gates that are not allowed and at least one of these gate is used in the circuit to fold, leading to the situation "the weight used internally by `mitiq` does not correspond to the weight the caller wrote" which is super unintuitive in my opinion.
4. Write a note in the documentation of the function explaining this behaviour.

Additional References
---------------------

*None*

**Comment by purva-thakre** [comment]
I think a warning in the case of a gate that's not in the input circuit but has fidelities provided could be useful here. 

If `invalid_gate_name` was used in the initial circuit, then either `qiskit` would have raised an error that the gate is not recognized or `mitiq` would have raised an error that the input circuit cannot be folded because[ `has_unitary(circuit)`](https://github.com/unitaryfund/mitiq/blob/d58c8fe015ab9d50db8c2e940b2582c9c8612ec2/mitiq/zne/scaling/folding.py#L52) will fail.

**Comment by andreamari** [comment]
Thanks @nelimee, this is a very useful issue. I guess it was not easy to isolate the problem/bug but you did it in a very clear way!

- I think the first thing to do in Mitiq is to raise an error if any `invalid_gate_name` is used, where `invalid_gate_name` is any name which is not in the supported set of names. So, for example an error should be triggered in both the following cases:

`fidelities={"invalid_gate_name": 0.06})
`
`fidelities={"rx": 0.1})
`

- The second thing to do is probably to support more gates, e.g. rotation gates.

@purva-thakre , I agree that fidelity is easier to measure for Clifford gates but, in principle, it can also be defined for non-Clifford gates too. So I would not enforce this restriction in Mitiq. In practice, it can be useful to set custom infidelities for non-Clifford gates, e.g.,  `rx` or  `rz`  gates.

**Comment by purva-thakre** [comment]
Thanks for the correction ! I was under the mistaken assumption that the gates were restricted to that set because of them being the generators of Clifford group.

**Comment by nelimee** [comment]
In fact it was quite easy: I started by reading the doc, the restriction on gates was not convenient for my use case so I tried anyway expecting an error, nothing happened and a folded circuit was returned, so I dug into `mitiq` code to understand what was going on and why no error was returned.

I completely agree with your points: an explicit error is better than an implicit unintuitive behaviour without any warning. Eventually, more gates will have to be supported for this function to be useful in real cases, but I have no idea how complex this might be. I would even prioritise some gates over others, for example supporting `{"cx", "rz", "sx"}` is enough to be able to fold any IBM-hardware-compliant quantum circuit and any circuit that has been transpiled with `qiskit.transpile` for a real backend.

In the mean time I have made my own Qiskit-compatible version, leaving it here if anyone finds this issue and needs it:
```py
import typing as ty

from qiskit import QuantumCircuit, QuantumRegister
from qiskit.providers.ibmq import IBMQBackend
from qiskit.providers.models.backendproperties import BackendProperties
from mitiq.zne.scaling.folding import _create_fold_mask


def _apply_fold_mask(
    circuit: QuantumCircuit,
    fold_mask: ty.List[int],
    scale: float,
) -> QuantumCircuit:
    circuit_name: str = f"{circuit.name}_{scale:.2f}"
    if abs(scale - 1) < 1e-2:
        circuit_name = f"{circuit.name}"
    output: QuantumCircuit = QuantumCircuit(
        *(circuit.qregs + circuit.cregs), name=circuit_name
    )
    for fold_nums, (instruction, qubits, clbits) in zip(fold_mask, circuit.data):
        output.compose(instruction, qubits=qubits, clbits=clbits, inplace=True)
        for _ in range(fold_nums):
            output.compose(instruction, qubits=qubits, clbits=clbits, inplace=True)
            output.compose(
                instruction.inverse(), qubits=qubits, clbits=clbits, inplace=True
            )
    return output


def fold_randomly(
    circuit: QuantumCircuit, scale: float, backend: IBMQBackend, seed=None
) -> QuantumCircuit:
    properties: BackendProperties = backend.properties()
    qreg: QuantumRegister = circuit.qregs[0]
    gate_error_rates: ty.List[float] = [
        (
            properties.gate_error(instruction.name, [qreg.index(q) for q in qubits])
            if instruction.name not in {"measure", "barrier"} # Probably not exhaustive
            else 0  # means "do not fold this gate"
        )
        for instruction, qubits, _ in circuit.data
    ]
    fold_mask: ty.List[int] = _create_fold_mask(
        weight_mask=gate_error_rates,
        scale_factor=scale,
        folding_method="at_random",
        seed=seed,
    )

    return _apply_fold_mask(circuit, fold_mask, scale)
```
There is a little bit of noise around circuit naming because I needed specific names, and I am pretty sure the set of instructions that should be ignored for folding is larger (in fact it might be better to filter the other way around, something like `if in hardware_gates`). But it works, and it should be quite straightforward to adapt if any error comes out or if another method is needed.

**Comment by purva-thakre** [comment]
@nelimee Just wanted to check if you are planning on working on[ the suggestions](https://github.com/unitaryfund/mitiq/issues/1179#issuecomment-1076511698) ? If not, I was thinking of working on them.

**Comment by nelimee** [comment]
> @nelimee Just wanted to check if you are planning on working on[ the suggestions](https://github.com/unitaryfund/mitiq/issues/1179#issuecomment-1076511698) ? If not, I was thinking of working on them.

I will be way too busy in the next few weeks due to several deadlines, so I will not work on this soon. You can work on this if you want to, and I will check the advance when I can. Have fun! :)

**Comment by nelimee** [comment]
@purva-thakre any news on this? :)

**Comment by purva-thakre** [comment]
@nelimee I haven't finished working on this yet. I did get started but left halfway because I got caught up in something else.
