### ISSUE TITLE
Implement `insert_ddd_sequences()` function for dynamical decoupling

### ISSUE THREAD

**Issue by Aaron-Robertson** [unitaryfund/mitiq#1189]
Implement the `insert_ddd_sequences()` function described in the [RFC for dynamical decoupling](https://docs.google.com/document/d/1cRwFCTn6kUjI1P0kNydtevxIYtE4r8Omd_iWK0Pe8qo/edit?usp=sharing).

This function serves to fill slack windows of idling qubits with the optionally provided dynamical decoupling rule, and defaults to the random rule (i.e. a semi-random sequence of spin echoes).

An implementation skeleton with pseudo-code is present in the [RFC](https://docs.google.com/document/d/1cRwFCTn6kUjI1P0kNydtevxIYtE4r8Omd_iWK0Pe8qo/edit?usp=sharing) but, of course, a different approach can be used.

**Comment by andreamari** [comment]
Chronologically, this issue should be addressed after #1162 is implemented.
