### ISSUE TITLE
MEP description in docs needs to be updated

### ISSUE THREAD

**Issue by purva-thakre** [unitaryfund/mitiq#1194]
Considering most of the accepted enhancement proposals so far have been in docs, I think it's better to link to [another template in docs](https://docs.google.com/document/d/1adomheXpbqp4YIBFQ49IsAJzuJKWyr75GRO1NeWg0Fo/edit?usp=sharing). 

It would also be better to avoid the confusion between RFC and MEP by updating[ the documentation](https://mitiq.readthedocs.io/en/stable/contributing.html#proposing-a-new-feature-to-mitiq). I propose keeping both the `md` and `doc` versions just in case. 

The `md` template also has a missing [link](https://github.com/unitaryfund/mitiq/blob/master/docs/mep/0000-feature-proposal-TEMPLATE.md#references-and-footnotes) to another MEP. 

![image](https://user-images.githubusercontent.com/66048318/160828665-1ba183ce-4250-40c3-8a1c-eb690a03aa5d.png)

**Comment by nathanshammah** [comment]
Interesting related news: Markdown supported in google docs https://workspaceupdates.googleblog.com/2022/03/compose-with-markdown-in-google-docs-on.html
