### ISSUE TITLE
Redundant information in citation file

### ISSUE THREAD

**Issue by natestemen** [unitaryfund/mitiq#1227]
Github creates a bibtex entry for the repository now that a citation file has been added (https://github.com/unitaryfund/mitiq/pull/1200). However, it looks as though the `name-particle` attribute may have been misused. The bibtex entry Github creates as of https://github.com/unitaryfund/mitiq/commit/4359166d7a9df1c8488520e2d6060d5c6f998b53 is

```bib
@software{Ryan_LaRose_LaRose_Mitiq_A_software_2021,
author = {Ryan LaRose LaRose, Ryan and Dr. Andrea Mari Mari, Andrea and Dr. Sarah Kaiser Kaiser, Sarah and Peter Karalekas Karalekas, Peter and Andre Alves Alves, Andre and Dr. Piotr Czarnik Czarnik, Piotr and Mohamed El Mandouh Mandouh, Mohamed and Max Gordon Gordon, Max and Yousef Hindy Hindy, Yousef and Aaron Robertson Robertson, Aaron and Purva Thakre Thakre, Purva and Dr. Nathan Shammah Shammah, Nathan and Dr. William Zeng Zeng, William},
license = {GPL-3.0},
month = {8},
title = {{Mitiq: A software package for error mitigation on noisy quantum computers}},
url = {https://github.com/unitaryfund/mitiq},
version = {0.9.3},
year = {2021}
}
```

As you can see, the `author` field is quite redundant. I believe the fix is remove everything after `Dr.` in the `name-particle` lines. More details about this attribute can be found [here](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#definitionspersonname-particle).

As a slight aside, I've never seen citations explicitly include the degrees of the authors. Is there a reason they are included here?

**Comment by andreamari** [comment]
Thanks @natestemen!
I would propose that we just remove all the `name-particle:` fields.

I am also not sure if it is good to share all personal email adresses in plain text. This has pros and cons.
