### ISSUE TITLE
Add function to generate random circuits in mitiq.benchmarks

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#1229]
Pre-Request Checklist
---------------------

- [x] I checked to make sure that this feature has not already been requested.

Issue Description
-----------------

Currently we have several functions that crate benchmark circuits, i.e., circuits that can be used to test error mitigation techniques.
The existing functions are:
```
generate_rb_circuits
generate_mirror_circuit
generate_ghz_circuit
```

Feature Request
-----------------------

All current benchmarks are based on Clifford circuits. It would be nice to have a new function called e.g.:
`generate_random_circuit` or `generate_volume_circuit` . 
The output should be a random non-Clifford circuit, possibly a 2-design. A good example is given by the circuits that are typically used in quantum volume experiments.

**Note:** The first thing to do, before reinventing the wheel, is checking if Cirq already has a similar function that can be adapted for the tasks of this issue. As far as I know, this is not the case at the moment.

Optional Features
------------------------

- The function `generate_random_circuit` could return as a second argument the associated list of *heavy bitstrings* in a similar way in which the existing function `generate_mirror_circuit` returns the correct bitstring. This is useful to benchmark the performance of error mitigation methods.
- The gate set is quite arbitrary. We can fix an arbitrary gate set or we could give a couple of options.

**Comment by nickdgardner** [comment]
I would like to work on this issue.
