### ISSUE TITLE
Add a function to generate random Clifford-plus-T circuits.

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#1230]
Pre-Request Checklist
---------------------

- [x] I checked to make sure that this feature has not already been requested.

Issue Description
-----------------

Currently we have several functions that crate benchmark circuits, i.e., circuits that can be used to test error mitigation techniques.
The existing functions are:
```
generate_rb_circuits
generate_mirror_circuit
generate_ghz_circuit
```

Feature Request
-----------------------

All current benchmarks are based on Clifford circuits. It would be nice to have a new function called e.g.:
`generate_random_clifford_t_circuit()`. 
The output should be a random non-Clifford circuit composed of Clifford gates (H, S, CNOT or CZ), and T gates.  

Note: this issue is very similar to #1229 .   The main difference is the specific gate set and the possibility of controlling the number
of T gates.

Nice-to-have features
-----------------------------

- It would be nice to have the possibility of setting the following numbers:
     - The number of single-qubit clifford gates.
     - The number of two-qubit Clifford gates (e.g. how many CNOTs)
     - The number of T gates (typically called t-count). 
     
If having all the three options is not practical, at least we should have the possibility of setting the number of T gates.

Optional feature
---------------------
- It would be great (but not crucial) if the circuits generate states with a sufficient level of randomness. E.g. if they can form a 2-design. - Optionally, we could return the list of heavy bitstrings as discussed for the generic random circuit function proposed in #1229.

**Comment by ZhaoyiLi-HekJukZaaiZyuJan** [comment]
I would like to work on this issue.
