### ISSUE TITLE
ZNE generated circuits creating gates different than original circuits

### ISSUE THREAD

**Issue by anhdpham** [unitaryfund/mitiq#1236]
The circuits generated for ZNE methods somehow change the gates as the circuits depth expand. Here is my code and output

from pyquil import Program, get_qc, list_quantum_computers
from pyquil.gates import *
import numpy as np
mitiq_test = Program()
ro = mitiq_test.declare("ro", "BIT", 1)
mitiq_test += X(0)
mitiq_test += X(0)
mitiq_test += X(0)
mitiq_test += X(0)
mitiq_test += MEASURE(0, ro[0])

import mitiq
from mitiq import zne

scale_factors = [1., 2., 3.]
folded_circuits = [
        zne.scaling.fold_gates_at_random(mitiq_test, scale)
        for scale in scale_factors]

print(folded_circuits[0])
DECLARE ro BIT[1]
X 0
X 0
X 0
X 0
MEASURE 0 ro[0]

print(folded_circuits[1])
DECLARE ro BIT[1]
X 0
RX(-pi) 0
X 0
X 0
X 0
RX(-pi) 0
X 0
X 0
MEASURE 0 ro[0]

print(folded_circuits[2])
DECLARE ro BIT[1]
X 0
RX(-pi) 0
X 0
X 0
RX(-pi) 0
X 0
X 0
RX(-pi) 0
X 0
X 0
RX(-pi) 0
X 0
MEASURE 0 ro[0]

!pip list
Package                       Version
----------------------------- -------------------
alembic                       1.4.3
appdirs                       1.4.4
argon2-cffi                   20.1.0
async-generator               1.10
attrs                         20.3.0
backcall                      0.2.0
backports.functools-lru-cache 1.6.1
beautifulsoup4                4.9.3
bleach                        3.2.1
blinker                       1.4
bokeh                         2.2.3
Bottleneck                    1.3.2
brotlipy                      0.7.0
cached-property               1.5.1
cachetools                    4.2.4
certifi                       2021.5.30
certipy                       0.1.3
cffi                          1.14.4
chardet                       3.0.4
charset-normalizer            2.0.12
cirq                          0.14.1
cirq-aqt                      0.14.1
cirq-core                     0.14.1
cirq-google                   0.14.1
cirq-ionq                     0.14.1
cirq-pasqal                   0.14.1
cirq-rigetti                  0.14.1
cirq-web                      0.14.1
click                         7.1.2
cloudpickle                   1.6.0
colorama                      0.4.4
conda                         4.9.2
conda-package-handling        1.7.2
cryptography                  3.2.1
cycler                        0.10.0
Cython                        0.29.21
cytoolz                       0.11.0
dask                          2.30.0
decorator                     4.4.2
defusedxml                    0.6.0
dill                          0.3.3
distlib                       0.3.4
distributed                   2.30.1
dlx                           1.0.4
docplex                       2.20.204
duet                          0.2.5
entrypoints                   0.3
fastcore                      1.3.29
fastdtw                       0.3.4
fastjsonschema                2.15.3
filelock                      3.6.0
fsspec                        0.8.4
gitdb                         4.0.9
GitPython                     3.1.27
gmpy2                         2.1.0b1
google-api-core               1.31.5
google-auth                   1.35.0
googleapis-common-protos      1.55.1b1
grpcio                        1.45.0rc1
h11                           0.9.0
h5py                          3.1.0
HeapDict                      1.0.1
httpcore                      0.11.1
httpx                         0.15.5
idna                          2.10
imagecodecs                   2020.5.30
imageio                       2.9.0
importlib-metadata            3.1.1
inflection                    0.5.1
ipykernel                     5.3.4
ipympl                        0.5.8
ipython                       7.32.0
ipython-genutils              0.2.0
ipywidgets                    7.5.1
iso8601                       0.1.16
jedi                          0.17.2
Jinja2                        2.11.2
joblib                        0.17.0
json5                         0.9.5
jsonschema                    3.2.0
jupyter-client                6.1.7
jupyter-core                  4.7.0
jupyter-telemetry             0.1.0
jupyterhub                    1.2.2
jupyterlab                    2.2.9
jupyterlab-git                0.23.2
jupyterlab-pygments           0.1.2
jupyterlab-server             1.2.0
kiwisolver                    1.3.1
lark                          0.11.3
llvmlite                      0.34.0
locket                        0.2.0
lxml                          4.8.0
Mako                          1.1.3
MarkupSafe                    1.1.1
matplotlib                    3.3.3
matplotlib-inline             0.1.3
mistune                       0.8.4
mitiq                         0.14.0
mock                          4.0.2
more-itertools                8.12.0
mpmath                        1.1.0
msgpack                       0.6.2
multitasking                  0.0.10
nb-conda-kernels              2.3.0
nbclient                      0.5.1
nbconvert                     5.6.1
nbdev                         1.1.3
nbdime                        2.1.1
nbformat                      5.0.8
nest-asyncio                  1.4.3
networkx                      2.5
notebook                      6.1.5
ntlm-auth                     1.5.0
numba                         0.51.2
numexpr                       2.7.1
numpy                         1.20.3
oauthlib                      3.0.1
olefile                       0.46
packaging                     20.4
pamela                        1.0.0
pandas                        1.1.4
pandocfilters                 1.4.2
parso                         0.7.1
partd                         1.1.0
patsy                         0.5.1
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        8.0.1
pip                           20.3.1
plotly                        4.13.0
ply                           3.11
prometheus-client             0.9.0
prompt-toolkit                3.0.8
protobuf                      3.13.0
psutil                        5.7.3
ptyprocess                    0.6.0
py                            1.11.0
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pybind11                      2.9.1
pycosat                       0.6.3
pycparser                     2.20
pycurl                        7.43.0.6
pydantic                      1.8.2
Pygments                      2.7.2
PyJWT                         1.7.1
pyOpenSSL                     20.0.0
pyparsing                     2.4.7
pyquil                        3.0.1
pyrsistent                    0.17.3
PySocks                       1.7.1
python-constraint             1.4.0
python-dateutil               2.8.1
python-editor                 1.0.4
python-json-logger            2.0.1
python-rapidjson              1.6
pytz                          2020.4
PyWavelets                    1.1.1
PyYAML                        5.3.1
pyzmq                         20.0.0
qcs-api-client                0.8.0
qiskit                        0.27.0
qiskit-aer                    0.8.2
qiskit-aqua                   0.9.2
qiskit-ibmq-provider          0.14.0
qiskit-ignis                  0.6.0
qiskit-rigetti                0.4.5
qiskit-terra                  0.17.4
Quandl                        3.7.0
requests                      2.27.1
requests-ntlm                 1.1.0
retry                         0.9.2
retrying                      1.3.3
retworkx                      0.11.0
rfc3339                       6.2
rfc3986                       1.5.0
rpcq                          3.9.2
rpy2                          3.3.6
rsa                           4.8
ruamel-yaml-conda             0.15.80
ruamel.yaml                   0.16.12
ruamel.yaml.clib              0.2.2
scikit-image                  0.17.2
scikit-learn                  0.23.2
scipy                         1.7.3
seaborn                       0.11.0
Send2Trash                    1.5.0
setuptools                    49.6.0.post20201009
simplegeneric                 0.8.1
six                           1.16.0
smmap                         5.0.0
sniffio                       1.2.0
sortedcontainers              2.3.0
soupsieve                     2.0.1
SQLAlchemy                    1.3.20
statsmodels                   0.12.1
sympy                         1.7
tables                        3.6.1
tblib                         1.6.0
terminado                     0.9.1
testpath                      0.4.4
threadpoolctl                 2.1.0
tifffile                      2020.11.26
toml                          0.10.2
toolz                         0.11.1
tornado                       6.1
tqdm                          4.54.0
traitlets                     5.0.5
typing-extensions             3.7.4.3
tzlocal                       2.1
urllib3                       1.25.11
vincent                       0.4.4
virtualenv                    20.2.1
wcwidth                       0.2.5
webencodings                  0.5.1
websocket-client              1.3.1
wheel                         0.36.0
widgetsnbextension            3.5.1
xlrd                          1.2.0
yfinance                      0.1.70
zict                          2.0.0
zipp                          3.4.0

**Comment by andreamari** [comment]
Hi @anhdpham,

`RX(-pi)` is, up to a global phase, equal to X^-1, which is also equal to X for this particular gate. So, if I am not wrong, this is the expected behavior of unitary folding. Note that unitary folding maps a unitary G to G G^-1 G.

I agree that it would be nice to see `X^-1` or  `X` instead of `RX(-pi)` in the printed output, but I don't think this depends on Mitiq. It looks more like PyQuil aspect.

Please reopen this issue if you disagree.
