### ISSUE TITLE
New technique: Add a function to implement Randomized Compiling

### ISSUE THREAD

**Issue by tozbilgin** [unitaryfund/mitiq#1245]
Issue Description
-----------------

Gate errors are one of the major sources of noise in quantum circuits and can be classified in two groups: Coherent and incoherent errors. Coherent errors occur due to some miscalibration of circuit parameters and do not destroy the state purity. This can be a serious problem since similar errors occur in consecutive executions leading to a bias. It is easier to handle incoherent errors using what is known as randomized compiling (RC). We can convert coherent errors to incoherent errors by introducing a set of randomizing single qubit gates.

Mitiq is missing this mitigation technique.

Proposed Solution
-----------------

Adding `randomized_compiling`  function implementing RC.

Additional References
---------------------

Rosenberg, E., Ginsparg, P. and McMahon, P.L., (2021). Experimental error mitigation using linear rescaling for variational quantum eigensolving with up to 20 qubits. [arXiv:2106.01264](https://arxiv.org/pdf/2106.01264.pdf).

Urbanek M., Nachman B., Pascuzzi V.R., He A., Bauer C.W., de Jong W.A., (2021). Mitigating depolarizing noise on quantum computers with noise estimation circuits. [arXiv:2103.08591](https://arxiv.org/pdf/2103.08591.pdf)

Wallman J.J., (2016) Noise tailoring for scalable quantum computation via randomized compiling.  [arXiv:1512.01098](https://arxiv.org/abs/1512.01098)

**Comment by andreamari** [comment]
Thanks @tozbilgin! Randomized compiling is indeed a very interesting technique. It is in our wish list even if not
explicitly planned for the 2022 roadmap (https://github.com/unitaryfund/mitiq/wiki#mitiq-2022-roadmap).

Anyone interested is welcome to write an RFC for planning the addition of randomized compiling to Mitiq. You can find similar documents that we did for other techniques at [this link](https://github.com/unitaryfund/mitiq/projects/7).

**Comment by natestemen** [comment]
@tozbilgin just FYI in case you haven't seen we recently added some functionality in this direction in #1774. It's a rather simplified take on full randomized compiling, but it's a start. If you have any comments let us know!

**Comment by natestemen** [comment]
Pauli Twirling `mitiq.pt` has now been added to Mitiq in somewhat limited functionality, but it should hopefully satisfy the requirements to turn coherent errors into incoherent ones. Find more details on the [Pauli Twirling user guide](https://mitiq.readthedocs.io/en/stable/guide/pt.html).
