### ISSUE TITLE
Interfacing Qibo with mitiq

### ISSUE THREAD

**Issue by shangtai** [unitaryfund/mitiq#1247]
Issue Description
-----------------

Qibo is an open-source high-level API provided by Qilimanjaro, written in Python and capable of running a quantum algorithms on top of different quantum computers and simulators. It currently supports the IBM real and virtual machines, the Rigetti virtual machine, and Qilimanjaro’s virtual machine called VQMlite.  A key goal is to provide a standard interface that can be applied to many different backends.

Currently if we pass a Qibo circuit to Mitiq, we obtain the following message:

```
mitiq.interface.conversions.UnsupportedCircuitError: Circuit from module qibo.core.circuit is not supported.

Circuit types supported by Mitiq are
{'cirq': 'Circuit', 'pyquil': 'Program', 'qiskit': 'QuantumCircuit', 'braket': 'Circuit', 'pennylane': 'QuantumTape'}
```

I hope that we can add a new frontend to Mitiq that works well with Qibo.

Proposed Solution
-----------------

As a workaround now, we can convert a Qibo circuit to QASM such as here https://github.com/unitaryfund/mitiq/pull/1232 

Additional References
---------------------

Here is more information about qibo: https://qibo.readthedocs.io/en/stable/

**Comment by renatomello** [comment]
I second this suggestion.

**Comment by natestemen** [comment]
Thanks for the first stab at this issue in #1232 @shangtai. Are you interested in working on this further?

We also have a feature coming out in the next release of Mitiq that allows one to define their own `to_mitiq`/`from_mitiq` functions that can hook into our code. That might be an acceptable workaround for the time being.

**Comment by renatomello** [comment]
> We also have a feature coming out in the next release of Mitiq that allows one to define their own `to_mitiq`/`from_mitiq` functions that can hook into our code [#1850]. That might be an acceptable workaround for the time being.

If I understood correctly, It's true that it would be a workaround for circuits that only contain `qasm` gates. However, a more specific implementation would still be necessary for general `qibo` circuits. We could work on that together in the near future.

**Comment by natestemen** [comment]
Ah okay yeah I'm not familiar with Qibo, so if there are lots of operations that are not able to convert into cirq circuits then that can cause problems as cirq is our underlying frontend that mitiq is written in.
