### ISSUE TITLE
Make mitigate_executor compatible with batched executor functions

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#1253]
### Description
All error mitigation techniques in Mitiq have the associated `mitigate_executor` function. E.g. `mitiq.zne.mitigate_executor()`.
The current implementation for ZNE, PEC and CDR assumes an executor that is not batched, i.e., that takes a single circuit
and returns a single result.
Only for the DDD technique, `mitigate_executor` is now compatible with batched executors.

 ### How to fix
- Apply a solution similar to the code of `mitiq.ddd.mitigate_executor()` to `mitiq.[xxx].mitigate_executor()` for `xxx in [zne, pec, cdr]`.
- Add a test for each technique to make sure it works.

**Comment by Misty-W** [comment]
hi @nylewong, let me know if you need help solving this issue or opening a PR.
