### ISSUE TITLE
Consider dropping support for complex expectation values.

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#1254]
We currently assume that observables are generic and so expectation values can be complex. 
This has some pros and cons.

**Pros:**
- More general setting

**Cons:**
- The code and the annotations of functions are less readable. Often there is confusion between floats and complex return values.
- Most importantly, some techniques are not compatible with the mitigation of complex expectation values and
often suspicious warnings like the following appear when using mitiq:
```
 /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
    return array(a, dtype, copy=False, order=order)
```
Two alternative solutions are proposed below.

## Proposed solution A (real expectation values)

- Always assume that user-defined executors return real expectation values or list of real expectation values.
- Always assume that `Executor.evaluate()` returns real expectation values.
- Always assume that a `mitiq.Observable` is Hermitian, such that its expectation value is real.
- Raise an error if the user defines an non-Hermitian observable.

## Note
The user can still decompose any non hermitian observable A as a linear combination of two Hermitian observables (A1, A2), such that: A = A1+ i A2 .
So the restriction to Hermitian observables is not strong as it seems.

## Proposed solution B (complex expectation values)
- Keep using complex expectation values
- Make sure executors that return complex expectation values are always compatible with Mitiq
- Make sure all techniques are compatible with complex expectation values. When this is not possible, split complex expectation values into real and imaginary parts, and mitigate both terms independently. 
- Make sure that all function annotations are consistent with the possibility of complex expectation values.

**Comment by WrathfulSpatula** [comment]
For Hermitian observables, I believe expectation values are _strictly theoretically real-valued_, by the way. Is there even a need for non-Hermitian operator expectation values? I'm not sure that would make sense, in the context of quantum theory.

**Comment by natestemen** [comment]
I found this review comment thread from last year on this issue: https://github.com/unitaryfund/mitiq/pull/1001#discussion_r736396474.
