### ISSUE TITLE
[unitaryhack-bounty] Add thumbnail images to documentation examples.

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#1283]
Issue Description
-----------------

Currently we have thumbnail images only for a fraction of the examples in the docs: https://mitiq.readthedocs.io/en/v0.15.0/examples/examples.html

It would be good to have thumbnail images for all examples.

Proposed Solution
-----------------

There are different ways of adding thumbnail images with sphinx gallery:

- Adding an hard-coded image, not necessarily plots produced by the associated example. 
- Using a self-generated plot produced by the example during the docs build.
- Adding an hard-coded image of a plot generated by the example. This may be useful for zooming or other image edits.

Any option is fine. What is important is having a final result that looks good and clear.

For an example a gallery that looks good see, e.g.,  https://pennylane.ai/qml/demonstrations.html

**Comment by nathanshammah** [comment]
Agreed!

**Comment by divshacker** [comment]
Hey, I would like to work on this issue.

**Comment by andreamari** [comment]
Great, thanks @divshacker!
