### ISSUE TITLE
Implement Error Mitigation examples using various frontends

### ISSUE THREAD

**Issue by Rahul-Mistri** [unitaryfund/mitiq#1287]
Pre-Request Checklist
---------------------

- [x] I checked to make sure that this feature has not already been requested.

Issue Description
-----------------

Currently most of our examples are written with only one [frontend](https://mitiq.readthedocs.io/en/latest/guide/frontends-backends.html). It would be easier for our users to have this example written in their preferred frontend, and would make Mitiq more accessible.

Proposed Solution
-----------------

Each example should be written in the other supported frontends. The following checklist is a link to an issue for a particular example and frontend.
- [x] #1329 
- [x] #1331
- [x] #1330
- [x] #1332
- [x] #1333 
- [x] #1334

**Comment by natestemen** [comment]
Since all of the sub-tickets have been completed here, I'm going to close this. Nice work, and thank you to all of @andreamari, @Misty-W, @deji725, @dubeyPraY, and @nickdgardner for your work here!
