### ISSUE TITLE
Test Mitiq with more recent versions of Python

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#1292]
Mitiq is currently tested with Python 3.7 and Python 3.8.
It would be good, if possible, to upgrade versions by one or two steps. 
I.e., testing Mitiq with:

- Python 3.8 and 3.9
or
- Python 3.8, 3.9 and 3.10

This issue is not just about _testing_ but also about _fixing_  possible issues that will emerge when testing recent Python versions.
For example, dependency conflicts may happen as reported in #1285

**Comment by saki-zapata** [comment]
Any plan to upgrade the `numpy` version to make it compatible with `python 3.10` (#1285)?

**Comment by andreamari** [comment]
This is quite important indeed. I'll add it to the next milestone but I am not sure if it's going to be an easy fix.
