### ISSUE TITLE
Warn users about incompatible frontends and backends

### ISSUE THREAD

**Issue by Misty-W** [unitaryfund/mitiq#1312]
Pre-Request Checklist
---------------------

- [X] I checked to make sure that this feature has not already been requested.

Issue Description
-----------------

From question raised by @natestemen on Discord: https://discord.com/channels/764231928676089909/979109444602449970

Ensure users receive helpful error messages for incompatible frontend and backend combinations.

Thanks for helping us improve Mitiq! 🙂

Proposed Solution
-----------------

Let us know what you'd like to see happen, and be sure to mention
any alternatives that you've considered.

Additional References
---------------------

If applicable, provide some references that will help us better understand the request.

**Comment by andreamari** [comment]
We close this and we use https://github.com/unitaryfund/mitiq/issues/1313 to keep track of the problem.
