### ISSUE TITLE
Investigate slow docs build

### ISSUE THREAD

**Issue by natestemen** [unitaryfund/mitiq#1321]
## Description

The docs take a _very_ long time to build. Since this can be an effective way to get feedback on a PR/commit, speeding up this loop could be beneficial for the team. Current build times are roughly 15 minutes.

**Comment by andreamari** [comment]
I am not sure this issue has a solution since I guess it's important to run the example notebooks in order to test that they work.

**Comment by natestemen** [comment]
Good point. I was thinking we could potentially cache the builds, and not rebuild the docs when the changes don't modify them. However, our code changes could potentially affect how the docs build/run, so maybe that's not such a good idea.

Since this has been open since may, and we don't have any good ideas for how to improve this, I'm going to close it.

Can always revisit if we come up with something.
