### ISSUE TITLE
Add Error Mitigation example with PennyLane

### ISSUE THREAD

**Issue by Rahul-Mistri** [unitaryfund/mitiq#1330]
Issue Description
-----------------
Currently we only have one example on [_Error Mitigation_](https://mitiq.readthedocs.io/en/stable/examples/ibmq-backends.html) which is written with Qiskit as the frontend. PennyLane users would find it useful if we had the same example implemented with PennyLane as the frontend.

Proposed Solution
-----------------
- Implement a PennyLane variant of Qiskit example [(the source file can be found here)](https://github.com/unitaryfund/mitiq/blob/master/docs/source/examples/ibmq-backends.myst)

Additional References
---------------------
- Please consult the [contributing guidelines](https://mitiq.readthedocs.io/en/latest/contributing_docs.html) for specific details on contributing to the documentation, and the [general contributing guidelines](https://mitiq.readthedocs.io/en/latest/toc_contributing.html) as well.

**Comment by nathanshammah** [comment]
The guidelines for the example are:
- Keep the example "experiment" as close as possible to the original one (ZNE, scaling factors, noise level, general syntax and text).
- Change the front end to be PennyLane instead of qiskit. 
- Keep IBMQ device simulator in the back end, using as much as possible pennylane, e.g., [`qml.device`](https://pennylaneqiskit.readthedocs.io/en/latest/devices/ibmq.html)

**Comment by JLenssen** [comment]
Hi, I noticed that Pennylane already provides an example of ZNE using mitiq in their [documentation](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.transforms.mitigate_with_zne.html). 
Should an example for another technique be provided instead (with a link to the ZNE example in the docs)?

**Comment by andreamari** [comment]
Hi @JLenssen, our aim is to translate this basic ZNE example to all supported frontends, so I would keep the current ZNE + PennyLane issue in the current form.

On the other hand, additional examples for other error mitigation techniques (e.g. PEC/DDD/CDR) are welcome too!
