### ISSUE TITLE
Add Error Mitigation example with Cirq

### ISSUE THREAD

**Issue by Rahul-Mistri** [unitaryfund/mitiq#1331]
Issue Description
-----------------
Currently we only have one example on [_Error Mitigation_](https://mitiq.readthedocs.io/en/stable/examples/ibmq-backends.html) which is written with Qiskit as the frontend. Cirq users would find it useful if we had the same example implemented with Cirq as the frontend.

Proposed Solution
-----------------
- Implement a Cirq variant of Qiskit example [(the source can be found here)](https://github.com/unitaryfund/mitiq/blob/master/docs/source/examples/ibmq-backends.myst)

Additional References
---------------------
- Please consult the [contributing guidelines](https://mitiq.readthedocs.io/en/latest/contributing_docs.html) for specific details on contributing to the documentation, and the [general contributing guidelines](https://mitiq.readthedocs.io/en/latest/toc_contributing.html) as well.

**Comment by nathanshammah** [comment]
The guidelines for the example are:
- Simplify the existing example by removing the Cirq section 
- create a new example just with the Cirq frontend (and IBMQ backend)

**Comment by Misty-W** [comment]
I can work on this issue.
