### ISSUE TITLE
Add Braket example on mitigating the energy landscape of a variational circuit

### ISSUE THREAD

**Issue by Rahul-Mistri** [unitaryfund/mitiq#1332]
Issue Description
-----------------
The example [_Mitigating the energy landscape of a variational circuit with Mitiq_](https://mitiq.readthedocs.io/en/stable/examples/simple-landscape-cirq.html) is implemented using Cirq as a frontend. We ought to implement this using Braket as an example for our users.

Proposed Solution
-----------------
- Implement a Braket variant of the example [(the source can be found here)](https://github.com/unitaryfund/mitiq/blob/master/docs/source/examples/simple_landscape.myst)

Additional References
---------------------
- Please consult the [contributing guidelines](https://mitiq.readthedocs.io/en/latest/contributing_docs.html) for specific details on contributing to the documentation, and the [general contributing guidelines](https://mitiq.readthedocs.io/en/latest/toc_contributing.html) as well.

**Comment by nickdgardner** [comment]
I can work on this issue

**Comment by deji725** [comment]
Just wanted to comment that the link in the Issue is broken: 

This is the new link for [_Mitigating the energy landscape of a variational circuit with Mitiq_](https://mitiq.readthedocs.io/en/stable/examples/simple-landscape-cirq.html)

The source can be found [here](https://github.com/unitaryfund/mitiq/blob/master/docs/source/examples/simple-landscape-cirq.md)

**Comment by natestemen** [comment]
Thanks Deji, I've updated the issue! Any interest in working on this?

**Comment by deji725** [comment]
Hi @natestemen I can work on this.

**Comment by natestemen** [comment]
No worries! Of course you can! Purva has assigned you, so others know it's being worked on. Don't hesitate to let us know if you have any questions, or need any help in getting things set up.
