### ISSUE TITLE
Add PennyLane example on mitigating the energy landscape of a variational circuit

### ISSUE THREAD

**Issue by Rahul-Mistri** [unitaryfund/mitiq#1333]
Issue Description
-----------------
The example [_Mitigating the energy landscape of a variational circuit with Mitiq_](https://mitiq.readthedocs.io/en/stable/examples/simple_landscape.html) is implemented using Cirq as a frontend. We ought to implement this using PennyLane as an example for our users.

Proposed Solution
-----------------
- Implement a PennyLane variant of the example [(the source can be found here)](https://github.com/unitaryfund/mitiq/blob/master/docs/source/examples/simple_landscape.myst)

Additional References
---------------------
- Please consult the [contributing guidelines](https://mitiq.readthedocs.io/en/latest/contributing_docs.html) for specific details on contributing to the documentation, and the [general contributing guidelines](https://mitiq.readthedocs.io/en/latest/toc_contributing.html) as well.

**Comment by deji725** [comment]
I can work on this issue as well.

**Comment by Misty-W** [comment]
@dubeyPraY
