### ISSUE TITLE
Add Qiskit example on mitigating the energy landscape of a variational circuit

### ISSUE THREAD

**Issue by Rahul-Mistri** [unitaryfund/mitiq#1334]
Issue Description
-----------------
The example [_Mitigating the energy landscape of a variational circuit with Mitiq_](https://mitiq.readthedocs.io/en/stable/examples/simple_landscape.html) is implemented using Cirq as a frontend. We ought to implement this using Qiskit as an example for our users.

Proposed Solution
-----------------
- Implement a Qiskit variant of the example [(the source can be found here)](https://github.com/unitaryfund/mitiq/blob/master/docs/source/examples/simple_landscape.myst)

Additional References
---------------------
- Please consult the [contributing guidelines](https://mitiq.readthedocs.io/en/latest/contributing_docs.html) for specific details on contributing to the documentation, and the [general contributing guidelines](https://mitiq.readthedocs.io/en/latest/toc_contributing.html) as well.

**Comment by nickdgardner** [comment]
I can work on this issue

**Comment by nickdgardner** [comment]
@natestemen Here is my initial notebook for this issue. I thought I'd upload it here for feedback/review before submitting a PR to change the documentation, but let me know if I should do something else. Thanks!

https://github.com/nickdgardner/mitiq/blob/master/docs/source/examples/simple-landscape-qiskit.ipynb
https://github.com/nickdgardner/mitiq/blob/master/docs/source/examples/simple-landscape-qiskit.myst

**Comment by natestemen** [comment]
Nice work Nick! I'd say just go ahead and open a PR and I can start giving you more concrete feedback from there.
