### ISSUE TITLE
pip install too old version

### ISSUE THREAD

**Issue by genyaprog** [unitaryfund/mitiq#1339]
Pre-Report Checklist
--------------------

- [ ] I am running the latest version of mitiq
- [ ] I checked to make sure that this bug has not already been reported

Issue Description
-----------------

When mitiq is installed via pip install mitiq too old version (0.5.0) is installed

How to Reproduce
----------------
pip install mitiq

**Comment by genyaprog** [comment]
Asked qustion in Discord

**Comment by andreamari** [comment]
For other users with a similar problem, two alternative things that can solve the problem are:

- `pip install -upgrade pip` followed by `pip install mitiq`
or
- `pip install mitiq==0.16.0 --force-reinstall` (where 0.16.0 can be any other Mitiq version)
