### ISSUE TITLE
Titles on examples page are being clipped

### ISSUE THREAD

**Issue by natestemen** [unitaryfund/mitiq#1343]
There is some great work ongoing in https://github.com/unitaryfund/mitiq/pull/1338 to replace the default mitiq logo with example-specific logos. While reviewing that I realized there is the separate problem of the titles being clipped.

<img width="350" alt="Screen Shot 2022-06-07 at 5 23 33 PM" src="https://user-images.githubusercontent.com/12703123/172505668-aba2af1a-0f2f-48a1-95ac-2ef091bee8e3.png">

**Comment by nathanshammah** [comment]
good point!
