### ISSUE TITLE
RFC for Readout Error Mitigation

### ISSUE THREAD

**Issue by Misty-W** [unitaryfund/mitiq#1387]
Pre-Request Checklist
---------------------

- [X] I checked to make sure that this feature has not already been requested.

Issue Description
-----------------

Review and approve [RFC for Readout Error Mitigation (REM)]
(https://docs.google.com/document/d/1buO5PrO5sS02VXjcaYf37RuR0rF6xpyr4J9H1tI4vN4/edit#heading=h.c072otyej9hw)

Feature request issue #815

**Comment by Misty-W** [comment]
Tried to assign @amirebrahimi but he doesn't appear in the list of possible assignees when I type in his username.

**Comment by amirebrahimi** [comment]
Thanks for the update. I have comments in the RFC that I'll be addressing soon.

**Comment by amirebrahimi** [comment]
I've updated the RFC doc and my branch to address some of the changes requested:
https://github.com/amirebrahimi/mitiq/commit/464578b247c6c5a517b556e94f4541149528b26f
https://github.com/amirebrahimi/mitiq/commit/5d7e51e878c3dd8a3e0c2f1e9a80b585505f4e0c

**Comment by andreamari** [comment]
Thanks @amirebrahimi, I left some comments on the RFC document. 
**For my side, the current version of the RFC can be accepted**! 
However a formal acceptance decision can only be taken after a proper discussion with other members of the Mitiq team. I'll keep you posted!

**Comment by natestemen** [comment]
Nice job Amir, this looks really great. I've made a comment about naming similar to Andrea's, but this is ready to move on to the next steps from me. I've marked it as accepted. Congrats! 🥳 🎉 

I'll close this out now as this ticket was just for tracking the RFC, and we can use https://github.com/unitaryfund/mitiq/issues/815 for the implementation whenever we decide to do that.
