### ISSUE TITLE
Clarify how CDR training circuits are generated

### ISSUE THREAD

**Issue by AminHosseinkhani** [unitaryfund/mitiq#1393]
An important aspect of Clifford Data Regression is how the training circuits are constructed. In the original publication cited by Mitiq as the reference, [Quantum 5, 592 (2021)](https://quantum-journal.org/papers/q-2021-11-26-592/), the implementation of the methods is done via Markov Chain Monte Carlo (MCMC). 

In the Mitiq cdr code, on the other hand, the training circuits are constracted using a simpler method based on how close the non-Clifford gates are to the set of Clifford gates. While this simplere technique is also mentioned in the original publication, as indicated before, all of the results presented in the original publication are obtained via MCMC. 

To avoid possible confusion here, it would be very appropriate if the documentary of mitiq.cdr could be updated to clarify this issue and to explicitly mention that mitiq.cdr does not implement MCMC, but rather the simpler technique.

**Comment by AminHosseinkhani** [comment]
An important aspect of Clifford Data Regression is how the training circuits are constructed. In the original publication cited by Mitiq as the reference, [Quantum 5, 592 (2021)](https://quantum-journal.org/papers/q-2021-11-26-592/), the implementation of the methods is done via Markov Chain Monte Carlo (MCMC). 

In the Mitiq cdr code, on the other hand, the training circuits are constracted using a simpler method based on how close the non-Clifford gates are to the set of Clifford gates. While this simplere technique is also mentioned in the original publication, as indicated before, all of the results presented in the original publication are obtained via MCMC. 

To avoid possible confusion here, it would be very appropriate if the documentary of mitiq.cdr could be updated to clarify this issue and to explicitly mention that mitiq.cdr does not implement MCMC, but rather the simpler technique.

**Comment by andreamari** [comment]
Hi @AminHosseinkhani, thanks for your useful feedback on CDR! 

Based on your comments, there are two things that we can do:

1. Updating the documentation with a warning based on your comment. Issue (this one): #1393 .
2. Actually implementing the more advanced appraoch (Markov Chain Monte Carlo) for the generation of training circuits. I just opened a new issue dedicated to this aspect. Issue: #1399

@AminHosseinkhani, your are super welcome to take any of the above issues. If you are interested just leave a comment under the corresponding issue. Of course this is optional, no pressure.

**Comment by natestemen** [comment]
Scope of this issue is to update the docs to reflect we don't currently use MCMC to generate CDR training circuit since #1399 is open to implement the more advanced technique in code.
