### ISSUE TITLE
Automatically generate package and add code tree

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#141]
### Package Tree
A tree of the `mitiq/mitiq` package contents is added in the [readme file](https://github.com/unitaryfund/mitiq#contents). 
However, this was done "by hand". It may be nice to:
- automatically generate it
- add information in the contributing to mitiq how-to (#109) about the fact that such tree needs to be regenerated and updated in the readme once the package is updated in structure.

To do such thing, I think in linux one has the `tree` command. I haven't found one in Mac yet, but maybe there is one that is platform agnostic. However the tree could be updated only when there is a release, adding that info in the readme printout, to simplify code development. 

### Code Tree
  It can be very useful (for sldes, etc.) and beautiful (to include an image of it in the documentation) to add a code tree. It does provide an intuitive way of how the library has developed in scope. I can copy the script from QuTiP's and pennylane.

**Comment by rmlarose** [comment]
I think this should be closed as #167 was closed. Please reopen if this isn't the case.
