### ISSUE TITLE
Allow passing the scale_factor as an argument to the executor

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#142]
With the current setting, `mitiq` is responsible for adding noise to the input circuit using `scale_noise` functions. However sometimes it could be easier if one can directly pass the `scale_factor` parameter to the executor which would be responsible for scaling the noise with an arbitrary method decided by the user.  With this approach the executor could scale the noise at a lower physical level, e.g. acting on the execution time, physical pulses, etc..

**Comment by willzeng** [comment]
Do we have a use case for this @andreamari now that we've found an alternative for #276

**Comment by crazy4pi314** [comment]
This is a pretty old issue, is it still relevant/interesting @andreamari?

**Comment by andreamari** [comment]
I think the same result can be indirectly achieved with the existing methods `run_classical` (or  `extrapolate`)  of a `Factory`. So I agree that we can close this.
