### ISSUE TITLE
Insert the GGI summer school "ZNE exercice" notebook into the Examples section of the docs

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#1426]
Issue Description
-----------------
On July 2022, we gave some lectures on error mitigation and Mitiq at the [GGI Summer School - SQMS](https://www.ggi.infn.it/showevent.pl?id=436). We made an ["exercise notebook"](https://www.ggi.infn.it/talkfiles/bonuses/bonus6073.zip) for learning how to apply ZNE to a GHZ state with Mitiq.

In the last Mitiq community call, @nathanshammah suggested to port this notebook into the Mitiq docs, in the Examples section.

Proposed Solution
-----------------
To address this issue, the exercise notebook should be transformed into a `myst` file, perhaps modified,  and finally included in the docs.

**Comment by purva-thakre** [comment]
@andreamari @nathanshammah Looking at the files in the linked folder, there are two `ipnyb` - one is to-dos and one is with solutions. 

Is the goal of this issue to add one tutorial with a section for to-do practice and then another section for the intended solution ?

**Comment by andreamari** [comment]
Good question. I am not sure. What do you think?

What about if we put the half-filled exercise notebook in the examples section of the docs and at the bottom of the exercise notebook we add a link to the solution notebook (which is instead invisible from the examples section of the docs) ?

**Comment by purva-thakre** [comment]
Would it be better to create a separate `Practice with Mitiq` page in the documentation ? We can also add more practice exercises here. 

I am not too familiar with `.myst` but there should be a way to hide the solution until the user clicks on it or also provide hints without giving the full solution.

**Comment by natestemen** [comment]
My proposed solution would be to add the tutorial notebook (in myst form) with missing code to the examples, and add the full version to the examples directory as well, but not list it in the gallery. This way we could put a link to the full version in the tutorial notebook and still have it live on our docs, but not have it be as discoverable as when it's listed in the gallery. WDYT?

**Comment by purva-thakre** [comment]
Just wanted to comment, I should be able to work on this before the next milestone. 

I might not be able to attend the community call this Friday. Please don't reassign this !

**Comment by Misty-W** [comment]
hi @purva-thakre, still planning to work on this in this milestone?

**Comment by purva-thakre** [comment]
Yep !
