### ISSUE TITLE
Allow the executor to (optionally) execute a batch of input circuits.

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#143]
As noted by @rmlarose, it is more efficient to run non-adaptive extrapolation methods by executing all the noise-scaled circuits in a single batch. This is fact is particularly important when using real hardware.

Mitiq could automatically inspect the signature of the executor and, if this is compatible with a list of circuits, it could use a batched approach. Otherwise, if the executor is compatible with a single input circuit, mitiq can use the (current) sequential approach.

**Comment by willzeng** [comment]
I believe this is superseded by #317 If not please re-open
