### ISSUE TITLE
Make suppression of "No representation found for ideal_operation" warnings an option

### ISSUE THREAD

**Issue by Misty-W** [unitaryfund/mitiq#1440]
Pre-Request Checklist
---------------------

- [X] I checked to make sure that this feature has not already been requested.

Issue Description
-----------------

In the case where not all operations have `OperationRepresentation`s associated with them, the user is warned every time `execute_w_pec` is called. In the case that `execute_w_pec`is called many times, as in learning-based PEC, this results in numerous warning messages, which users already should know because they are learning representations one operation at a time.

Proposed Solution
-----------------

Create an option in `execute_w_pec` to turn off the representation warnings. The warnings can be on by default, but the user should be able to turn them off :)

**Comment by natestemen** [comment]
I'm used to seeing people ignore warnings using the `warnings` package as [documented here](https://stackoverflow.com/questions/11175388/ignoring-python-warnings):
```py
import warnings
warnings.simplefilter("ignore", UserWarning)

import the_module_that_warns
```

Is there a reason that we should allow users to ignore these more easily? I'm not sure of the original intention, but presumably the warnings are there for a reason.

**Comment by nathanshammah** [comment]
Log from the Mitiq office hours discussion with @natestemen @Misty-W: 

More context on `OperationRepresentation` is given in the documentation on PEC, [here](https://mitiq.readthedocs.io/en/latest/guide/pec-5-theory.html#quasi-probability-representations).

We are discussing whether to 
1. suppress these warnings with an option in `execute_with_pec` or 
2. suppress the the warnings using the `warnings` package within the learning function to avoid the many print out messages from the loop, ([link](https://stackoverflow.com/questions/5644836/in-python-how-does-one-catch-warnings-as-if-they-were-exceptions))

Option 2 to be explored by @Misty-W.

**Comment by Misty-W** [comment]
Solution: use warnings filter instead of explicit option in PEC.
