### ISSUE TITLE
REM: Write documentation

### ISSUE THREAD

**Issue by amirebrahimi** [unitaryfund/mitiq#1448]
Per #815, write the documentation sections for the RFC approved in #1387.

**Requirements**:
Write documentation for the following sections:
1. How do I use REM?
1. When should I use REM?
1. What additional options are available when using REM?
1. What happens when I use REM?
1. What is the theory behind REM?

These are the corresponding sub-issues:
- [x] #1451 
- [x] #1452
- [x] #1453
- [x] #1454
- [x] #1455

**Considerations**:
- A rough outline for the documentation is [here](https://docs.google.com/document/d/1buO5PrO5sS02VXjcaYf37RuR0rF6xpyr4J9H1tI4vN4/edit?pli=1#heading=h.m66w3ecdwtem)

**Comment by nathanshammah** [comment]
Thanks @amirebrahimi! This looks great. Possibly this could be a "super-issue" with sub-issues for each of the five sections, see for example https://github.com/unitaryfund/mitiq/issues/1210.

**Comment by amirebrahimi** [comment]
> Thanks @amirebrahimi! This looks great. Possibly this could be a "super-issue" with sub-issues for each of the five sections, see for example #1210.

Thanks. I've added the sub-issues.

**Comment by amirebrahimi** [comment]
@Misty-W - could you please assign this super ticket and sub-issues to me?

**Comment by Misty-W** [comment]
> @Misty-W - could you please assign this super ticket and sub-issues to me?

Done!

**Comment by amirebrahimi** [comment]
All sub-tasks complete, so closing this ticket.

**Comment by andreamari** [comment]
Thanks @amirebrahimi for all the code and docs support on REM!
