### ISSUE TITLE
Update allcontributors list and contributions

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#1463]
1. Update allcontributors list. On the contributors page by github at this moment 47 contributors are credited (incl. allcontributors and dependabot). In the Readme, allcontributors lists much fewer ones. 

2. We should update the contributions credited. Some of the credited contributors contributed more features than the initial ones, e.g., @Aaron-Robertson adding code and not being currently credited for that. 

Probably both things can be partially automated just by looking up missing contributors and then invoking allcontributors with the comment: "@allcontributors please add[ @natestemen](https://github.com/natestemen) for infrastructure, documentation, tests and code" in a PR

**Comment by natestemen** [comment]
@all-contributors please add @Aaron-Robertson for ideas, code, and documentation
