### ISSUE TITLE
Identity Scaling in ZNE Documentation

### ISSUE THREAD

**Issue by purva-thakre** [unitaryfund/mitiq#1470]
This issue is to keep track of all changes needed for adding Identity Scaling to existing ZNE documentation. 

The PR for the identity scaling functions is [here](https://github.com/unitaryfund/mitiq/pull/1442) and the RFC was approved in #335. 

Changes for adding identity scaling in existing documentation are : 

- [x] #1471
- [x]  #1472 
- [x] #1473
- [ ] #1474
- [ ] #1475
- [ ] #1546

**Comment by andreamari** [comment]
Hi @purva-thakre, thanks for this issue and sorry for replying so late. 

Identity scaling is a new noise scaling method that is complementary to existing ones like fold gates at random or fold global.  I don't think we need to create all the docs sections that you listed above, as if we were introducing a completely new error mitigation technique.

What we probably need is just a short subsection in this [ZNE options page]( https://mitiq.readthedocs.io/en/stable/guide/zne-3-options.html#noise-scaling-functions) where we mention the identity scaling function.

**Comment by purva-thakre** [comment]
@andreamari Ok. That is fine with me for the sections not discussed in this comment. I was proposing changes to existing ZNE docs because there's a difference in how the number of layers are inserted. All the examples are using a unitary folding method. 

I think in addition to the options page, the 'theory' might need some information about identity scaling and some information about decoherence.

I think 'What happens when I use ZNE' section will be the best for this but there needs to be a discussion on how the same scale factor would lead to different number of layers inserted for the two scaling methods.

**Comment by andreamari** [comment]
@purva-thakre When reading this issue I had the wrong impression that you wanted to document Identity Scaling as a fully new technique. But I was wrong! Sorry for creating this confusion.  Updating the existing ZNE docs wherever you think is more appropriate sounds good for me.
