### ISSUE TITLE
Identity Scaling : Additional Options

### ISSUE THREAD

**Issue by purva-thakre** [unitaryfund/mitiq#1473]
https://mitiq.readthedocs.io/en/stable/guide/zne-3-options.html

Same as [Unitary Folding method ](https://mitiq.readthedocs.io/en/stable/guide/zne-3-options.html#unitary-folding)described in the documentation, add a subsection for the identity insertion method.

- [ ]  General description of how the layers are inserted
- [ ] Difference between integer scale and float factors - uniform layers vs random layers

**Comment by natestemen** [comment]
I believe this is done now. If it's not, please provide a description of what else is to be completed and reopen!
