### ISSUE TITLE
Identity Scaling : What happens when I use ZNE ?

### ISSUE THREAD

**Issue by purva-thakre** [unitaryfund/mitiq#1474]
https://mitiq.readthedocs.io/en/stable/guide/zne-4-low-level.html

First step is only for using unitary folding. Make changes for identity scaling. 

Heere, add a table (or diagram) differentiating between Unitary Folding and Identity Insertion methods.

**Comment by natestemen** [comment]
closed by https://github.com/unitaryfund/mitiq/pull/1759
