### ISSUE TITLE
Update sphinx config

### ISSUE THREAD

**Issue by natestemen** [unitaryfund/mitiq#1493]
When running `make docs` I'm getting some deprecation warnings:
```
WARNING: 'jupyter_execute_notebooks' is deprecated for 'nb_execution_mode' [mystnb.config]
WARNING: 'execution_timeout' is deprecated for 'nb_execution_timeout' [mystnb.config]
WARNING: 'nb_render_priority' is deprecated for 'nb_mime_priority_overrides'mystnb.config
```

These will need to be updated in [`docs/source/conf.py`](https://github.com/unitaryfund/mitiq/blob/a48f35f9ba7fab2f491c2baac2a905b6f3706b40/docs/source/conf.py). Documentation is [here](https://www.sphinx-doc.org/en/master/usage/configuration.html).

**Comment by nathanshammah** [comment]
Nice find.
