### ISSUE TITLE
Make docs compatible with latest version of sphinx-gallery

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#1498]
In https://github.com/unitaryfund/mitiq/pull/1497 the version of `sphinx-gallery` has been pinned to `0.10.1` since, with later
versions, the gallery examples [doesn't look good](https://mitiq.readthedocs.io/en/v0.18.0/examples/examples.html).

After pinning `sphinx-gallery`, it [looks ok](https://mitiq--1497.org.readthedocs.build/en/1497/examples/examples.html), but it would be nice of the Mitiq documentation was compatible with the latest version of `sphinx-gallery`.

**Comment by natestemen** [comment]
This problem is being tracked in https://github.com/sphinx-gallery/sphinx-gallery/issues/984. Once there is a solution there we should be able to upgrade.

**Comment by natestemen** [comment]
Once a newer version (>0.8.12) of [`nbsphinx`](https://github.com/spatialaudio/nbsphinx) is released this should be good to go.
