### ISSUE TITLE
Add IonQ native gates

### ISSUE THREAD

**Issue by yitchen-tim** [unitaryfund/mitiq#1500]
## Issue Description
Amazon Braket now supports [verbatim compilation](https://aws.amazon.com/blogs/quantum-computing/amazon-braket-now-supports-verbatim-compilation-and-native-gates-with-ionq/?tag=local002-20) now for IonQ. But when I tired to run this [example](https://mitiq.readthedocs.io/en/latest/examples/zne-braket-ionq.html) with verbatim compilation and native gates, I got the validation error that the gate does not exist. 

`ValueError: Unable to convert the instruction Instruction('operator': GPi('angle': 0.0, 'qubit_count': 1), 'target': QubitSet([Qubit(0)])) to Cirq. If you think this is a bug, you can open an issue on the Mitiq GitHub at https://github.com/unitaryfund/mitiq.`

## Proposed Solution

Add IonQ native gates, GPi, GPi2 and MS, as part of the supported gates of Mitiq. 

## Additional References
Amazon Braket's [Developer Guide](https://docs.aws.amazon.com/braket/latest/developerguide/braket-devices.html#braket-qpu-partner-ionq)
IonQ's [doc](https://docs.ionq.com/#section/Native-Gates)

**Comment by andreamari** [comment]
Hi @yitchen-tim, thanks for reporting this. 
Mitiq does support GPi gates and many other platform-specific gates.
I think there are two alternative paths that you could try:

- Applying Mitiq before the final verbatim compilation into native gates. In practice this means to insert the compilation in the body of the usual Mitiq `execute` function such that all the Mitiq circuit workflow happens with "standard gates" until the final step in which circuits are compiled right before entering the IonQ backend.
- Alternatively, you can try to define a custom folding function, similar to those in `mitiq.zne.scaling`, but compatible with your native gates. I am not sure if this will work, it's just an idea.

**Comment by yitchen-tim** [comment]
Thanks for the pointers to alternatives. Adding compilation as the final step of `execute` function sounds like the best way for those who want to use Mitiq with IonQ native gates today. But, for long term, I feel like adding native gates is still the best solution. I am happy to contribute to add the gates. I already started to do so, but I ran into issue that the inverse of IonQ native gates are not implemented in Cirq. I am looking into how to solve this. Any idea how I can bypass this issue besides implementing the inverse method in Cirq?

**Comment by yitchen-tim** [comment]
Opened a [PR](https://github.com/quantumlib/Cirq/pull/5889) in Cirq to implement the inverse of these gates. Once Cirq is updated, I will implement the Braket-Cirq translation in Mitiq.

**Comment by andreamari** [comment]
Perfect! thanks @yitchen-tim

**Comment by yitchen-tim** [comment]
@andreamari The PR for gate conversion is out #1525 !

**Comment by andreamari** [comment]
This issue was actually closed by [#5889 ](https://github.com/unitaryfund/mitiq/pull/1525)
