### ISSUE TITLE
Clean up issue/PR labels

### ISSUE THREAD

**Issue by natestemen** [unitaryfund/mitiq#1518]
We currently have 40(!) labels to use for issues/PRs. I suggest trimming this down so that labels can be found more easily, and used more effectively. I've put together a google sheet with the labels, and my proposed actions [here](https://docs.google.com/spreadsheets/d/1NV3hKzgrlSOD56WUwW0Atm6bG7QLsFigWL0A27mZ-qY/edit?usp=sharing).

---

For reference, here is the following python script I used to get the counts of the labels:
```py
import json
import subprocess
from collections import Counter

all_uses = []

for i in range(1, 1510):
    if i == 1074:
        continue
    if i % 10 == 0:
        print(f"iteration {i}")
    cmd = f"gh issue view {i} --json labels"
    process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE)
    output, error = process.communicate()
    labels = map(lambda obj: obj["name"], json.loads(output)["labels"])
    all_uses.extend(labels)
print(i)


print(all_uses)
print(Counter(all_uses))
```

**Comment by andreamari** [comment]
Fine for me. maybe I would keep `executors` and `observable` since like `zne`, `pec`, etc... they are Mitiq modules.

**Comment by natestemen** [comment]
Thanks Andrea, I've updated the sheet to keep those. WDYT @nathanshammah @Misty-W?

**Comment by natestemen** [comment]
I've removed the ones we agreed on in the google sheet.

At some point I'd like to go through the closed issues with label `stale` to ensure the bot didn't close anything that we actually want, but I think this is okay for now.
