### ISSUE TITLE
Codecov non-deterministically failing in CI

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#1523]
E.g.: https://github.com/unitaryfund/mitiq/actions/runs/3146490388/jobs/5115626902#step:7:1

Possible solutions:

- Downgrading the version of the GitHub codecov action (i.e. reverting [this](https://github.com/unitaryfund/mitiq/pull/1496/commits/87856a9c058bc5f6d20277e29df97721bec8f52d))? 

- No idea...

**Comment by natestemen** [comment]
This seems to have resolved itself. Happy to close?
