### ISSUE TITLE
Calibration tools RFC: explore solutions for calibration capabilities

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#1540]
## Issue Description

Mitiq provides several [error mitigation techniques](https://mitiq.readthedocs.io/en/stable/guide/guide.html) (ZNE, PEC, CDR, DDD, …).
Moreover, each technique has several options (hyper-parameters) that can be set by the user, e.g.: folding method, extrapolation method, quasi-probability representations, DDD sequences, CDR learning strategy, etc… 
This variety of possibilities is good and it’s one of the key features of Mitiq. However, it also generates an important practical issue for a typical Mitiq user that we can summarize by the following question:

_**“What error mitigation technique and what options should I use in my specific situation?**_ 

In the question above by specific situation we mean both the specific quantum computation to be run and the specific noisy backend to be used.

The scope of this RFC is to explore existing methods, to propose new methods, and to compare alternative solutions to the calibration problem.

## Proposed Solution

This is a very exploratory RFC: we need to identify the best way to solve the calibration problem.
The actual final software implementation could emerge as a natural evolution of this RFC or could be planned in a new dedicated RFC focused on the actual implementation. 

## Collaborative work

The RFC document will be developed in a collaborative way. 
Every member of the Mitiq team is encouraged to participate with comments, ideas and text content in the shared Google doc linked below. 
Contributions from anyone beyond the Mitiq team are welcome too!

## Additional References - LINK TO RFC BELOW

Link to editable [RFC shared document](https://docs.google.com/document/d/1otUHnTlyNS-0rxGAxltHLF1iD5C9qT9oEZ3jn8VHWgw/edit?usp=sharing).

**Comment by natestemen** [comment]
Most likely going with the incremental approach, starting with 1 outlined in the RFC above. @andreamari to create a new issue detailing the implementation of this solution.
