### ISSUE TITLE
Identity Insertion Example for Docs

### ISSUE THREAD

**Issue by purva-thakre** [unitaryfund/mitiq#1546]
How should the identity scaling examples be added ? [On this page](https://mitiq.readthedocs.io/en/stable/examples/ibmq-backends.html), there are some examples for ZNE via Unitary folding. 

1. Create separate examples for identity scaling 
2. Limit the examples to what already exists but separate them into two sections : ZNE via Unitary Folding and ZNE via Identity Scaling

**Comment by andreamari** [comment]
Maybe a separate short example in which unitary folding and identity scaling are compared?
(I would consider this as a nice but not urgent addition, since we already have a lot of ZNE examples.)

**Comment by natestemen** [comment]
Just trying to clean up some issues. I think other issues cover this?

**Comment by purva-thakre** [comment]
@natestemen Not really. The way I see the docs are structured, there's the Users Guide and then there are separate examples for ZNE with different backends etc. I created this issue for the `Examples` page.
