### ISSUE TITLE
CI is failing on non-linux tests

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#1552]
## Issue Description
CI is failing on non-linux tests.

An example is given by the last commits of #1442
But it's happening in many other PRs too. 

I am re-running tests on #1442 to see if it was just a temporary problem. 

If you have any ideas on how to solve this, please comment here.

**Comment by purva-thakre** [comment]
If no one is working on this, I can take it. 

I am not familiar with Github Actions. So, I have been spending some time trying to figure out the differences between the linux and non-linux tests in the workflow file.

**Comment by natestemen** [comment]
I'm hoping this will be fixed by https://github.com/unitaryfund/mitiq/pull/1486, but the only evidence for that is that the builds passed on the numpy upgrade PR.

**Comment by natestemen** [comment]
Looks like this was fixed by #1486. If this pops up again, feel free to re-open.
