### ISSUE TITLE
Add glossary of QEM concepts to docs

### ISSUE THREAD

**Issue by nickdgardner** [unitaryfund/mitiq#1582]
Feedback/suggestions very welcome, especially on: 
- the lists of **candidate terms** ("definitely" and "maybe" lists are both provisional)
- the lists under **additional references**

Overleaf doc for drafting, additional notes: https://www.overleaf.com/7945521889pgjpnsvkjzyd

## Issue Description
Coverage of certain core concepts necessary for understanding and motivating quantum error mitigation is not adequate in standard intro to QC resources currently (the coverage is variously too basic or advanced or dispersed). This makes Mitiq less accessible than it could be.

## Proposed Solution
Add a single-page glossary of concepts that are important for understanding/motivating QEM but aren't covered adequately (for Mitiq's purposes) in the standard intro QC resources. 

Each concept/term could consist of:

- a short paragraph (1-4 sentences) defining the term
- where appropriate/helpful, links to one or a few good free resources for people who want to dig deeper (good open-access survey paper, wikipedia article, explanation elsewhere online (e.g. one of Pennylane's detailed [glossary](https://pennylane.ai/qml/demos/tutorial_qaoa_intro.html) articles))

### Candidate terms for glossary 
For concepts that are intrinsically complex and/or have complicated formalisms, I think **the aim while writing a definition** should be to define it informally but as precisely as possible in a few sentences. 

As for the **imagined audience** (lowest level of presumed background), I am thinking (but other suggestions welcome): someone with basic knowledge of quantum computing (not a total beginner) who may have heard of error mitigation and variational algorithms but who does not know what they are.

The **goal of a glossary definition** should be to provide a person from the imagined audience with additional background they need to follow the core Mitiq documentation and the examples.

#### Definitely Include
1. Circuit Depth
2. Clifford Data Regression (CDR)
3. Digital Dynamical Decoupling (DDD)
4. Expectation Value
5. Gate Fidelity
6. Global Folding
7. Local Folding
8. Observable
9. Probabilistic Error Cancellation (PEC)
10. Quantum Error Mitigation (QEM)
11. Quantum Error Correction (QEC)
12. Readout Error Mitigation (REM)
13. Sampling Overhead
14. Zero Noise Extrapolation (ZNE)

#### Maybe Include
1. Ansatz
2. Circuit Size
3. Hamiltonian
4. Monte Carlo Estimation
5. Near-term Algorithm
6. Noise Model
7. Pulse Stretching
8. Quantum Approximate Optimization Algorithm (QAOA)
9. Quantum Channel
10. Quasi-Probability Decomposition
11. Variational Quantum Algorithm (VQA)
12. Variational Quantum Eigensolver (VQE)

### Action items
1. Scan through [Users Guide](https://mitiq.readthedocs.io/en/stable/guide/guide.html#) and [Examples ](https://mitiq.readthedocs.io/en/stable/examples/examples.html) looking for (1) concepts that should be defined (for the imagined audience of Mitiq users) and (2) where in the documentation they are already defined (or note if they are not yet defined)

#### Papers (especially surveys)
If resource is a paper, should be included in [Mitiq references](https://mitiq.readthedocs.io/en/stable/bibliography.html) and linked through there. TODO: clean up, add links
- unitary folding paper
- surveys of QEM (UF benchmarking paper, Cai et al survey)
- surveys of near-term algorithms (Bharti et al)

### Models/inspiration from other documentation
- Pennylane [glossary of key concepts](https://pennylane.ai/qml/glossary.html)
- [scQubits docs](https://scqubits.readthedocs.io/en/latest/index.html) mentioned by Nathan

**Comment by natestemen** [comment]
Nice start Nick! Let's try to keep this limited to error mitigation specific terms and concepts for now. We have the common acronyms wiki page [here](https://github.com/unitaryfund/mitiq/wiki/Common-Acronyms), which could be a source of info.

I think starting small and building from there is the way to go for this.

**Comment by nickdgardner** [comment]
Ok sounds good! I'll put a link to a doc on the agenda ahead of Friday's meeting with some draft definitions for people to look at.

**Comment by Misty-W** [comment]
Link to Overleaf (thanks Nick!): https://www.overleaf.com/7945521889pgjpnsvkjzyd

**Comment by nathanshammah** [comment]
Thanks @nickdgardner, looks great. Can we move to discuss porting the "Definitely Include?" list? It could be good to assign some terms to others. But to begin, this issue could be resolved by adding the glossary to the docs quickly and creating the scaffolding for populating more terms.
