### ISSUE TITLE
Gather all accepted RFC's in one section ?

### ISSUE THREAD

**Issue by purva-thakre** [unitaryfund/mitiq#1583]
Since the topic of the RFC template came up at the start of the meeting, I think it would be better to gather up all the accepted RFC's in one section. 

Option 1 : List all of the accepted RFC's with links in [this section](https://mitiq.readthedocs.io/en/stable/contributing.html#proposing-a-new-feature-to-mitiq) of the docs where the template exists. 

Option 2 : Wiki page 

Feel free to add another option as well.

**Comment by nathanshammah** [comment]
+1 for Option 1.

**Comment by natestemen** [comment]
option 1️⃣

**Comment by Misty-W** [comment]
@purva-thakre , @andreamari, @amirebrahimi we can start by linking accepted RFCs on this issue.

**Comment by amirebrahimi** [comment]
Sure, RFC for REM is #1387. Did you want me to create a separate PR adding it to the documentation, @Misty-W? And is there a preferred format for the docs (e.g. bulleted list)?

**Comment by natestemen** [comment]
We're just looking to collect the accepted PRs in this issue. Once they're all here someone can add them all at once. Thanks for linking yours!

**Comment by andreamari** [comment]
Two additional accepted RFCs: 

- [Dynamical decoupling RFC](https://docs.google.com/document/d/1cRwFCTn6kUjI1P0kNydtevxIYtE4r8Omd_iWK0Pe8qo/edit?usp=sharing)

- [Calibration generic plan RFC:](https://docs.google.com/document/d/1otUHnTlyNS-0rxGAxltHLF1iD5C9qT9oEZ3jn8VHWgw/edit?usp=sharing)

**Comment by nathanshammah** [comment]
- [Identity scaling](https://docs.google.com/document/d/1hbd9frjYiSy0WujA0iCccc-oMO4Q-kZc2G4b3lkJHdk/edit)
- [Documentation Reorganization](https://docs.google.com/document/d/13un5TZPknSOhmOBkrL2rsofjGfdp2jDnd-DywLpGFPc/edit#heading=h.mckr847qq60k)
- [RFC Template](https://docs.google.com/document/d/1nrg--pMBUNf7mqf3p1FV_q7Yx--YyCUq4d8UMBvNI1w/edit)
- [Calibration (solution 1)](https://docs.google.com/document/d/1EZUJyEEUQUH33UOgSIzCCvXyxP0WLOQn11W0x4Ox4nY/edit#heading=h.4wr9qx2m833b)

**Comment by Misty-W** [comment]
[Learning-based PEC RFC](https://docs.google.com/document/d/1VItesy6R5SlUa_YXW1km7IjFZ8kzyFeHUepHak1fEh4/edit)

**Comment by nathanshammah** [comment]
I will take this issue
