### ISSUE TITLE
Codecov upload fails intermittently

### ISSUE THREAD

**Issue by Misty-W** [unitaryfund/mitiq#1584]
Codecov upload fails intermittently on python 3.10

Error message:

> [2022-11-07T22:47:33.789Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
> Error: Codecov: Failed to properly upload: The process '/home/runner/work/_actions/codecov/codecov-action/v3.1.1/dist/codecov' failed with exit code 255

**Comment by natestemen** [comment]
Can you link to an example of this happening?

**Comment by Misty-W** [comment]
https://github.com/unitaryfund/mitiq/actions/runs/3414551571/jobs/5682658859

**Comment by Misty-W** [comment]
Another example: https://github.com/unitaryfund/mitiq/actions/runs/3365792242/jobs/5581622895

**Comment by Misty-W** [comment]
There might be more, these are two I could find in the recent workflow history.

**Comment by natestemen** [comment]
Looks like codecov is aware of this issue and is [working](https://github.com/codecov/codecov-action/issues/837#issuecomment-1302609100) on a fix: https://github.com/codecov/codecov-action/issues/837.

**Comment by Misty-W** [comment]
Thanks for looking into this @natestemen! As a temporary workaround we could consider adding a retry if upload fails, which is what Codecov seems to recommend. Right now our workflow doesn't allow us to retry upload by itself, so the whole test has to be re-run and can only be re-run after all others finish (which is another matter).

**Comment by natestemen** [comment]
Can you link to where that's recommended? From what I see they are recommending using a token: https://github.com/codecov/codecov-action/issues/837#issuecomment-1265726923. This has the downside of not running on PRs opened from forks. The other option is to make the token public, which is not ideal, but could be okay if we really want to close this.

I'm fine with re-running the tests occasionally and so happy to wait for an upstream fix. Understand if you/others want a quicker fix, however.

**Comment by natestemen** [comment]
This should hopefully be fixed by https://github.com/unitaryfund/mitiq/pull/2271. Will close for now, and reopen if the token doesn't fix the issue.

cc @cosenal @nathanshammah
