### ISSUE TITLE
On API-doc page, side bar scrolling not working for "Executor"

### ISSUE THREAD

**Issue by nickdgardner** [unitaryfund/mitiq#1593]
## Issue Description
When I click on [Executors](https://mitiq.readthedocs.io/en/stable/apidoc.html#module-mitiq.executor.executor) on the [API-doc](https://mitiq.readthedocs.io/en/stable/apidoc.html) page, the visible side bar scrolling under "On this page" shows "Digital Dynamical Decoupling" highlighted instead of "Executors". The main part of the page jumps to the Executors section as intended, just the side bar seems to be broken for Executors. For other sections it works fine.

<img width="1217" alt="Screen Shot 2022-11-15 at 6 47 08 PM" src="https://user-images.githubusercontent.com/36652026/202072656-17ec3f8b-8e55-4873-8abd-7576edd1f59a.png">

## How to Reproduce
Follow this link to [Executors](https://mitiq.readthedocs.io/en/stable/apidoc.html#module-mitiq.executor.executor)

## Expected behavior

Under "On this page", "Executors" rather than "Digital Dynamical Coupling" should be highlighted. 

---

<details>
<summary>Environment Context</summary>

Use the `about()` function to summarize information on operating system, python version and dependencies.
```python
from mitiq import about
about()
```

Additional Python Environment Details (`pip freeze` or `conda list`):

```
Copy and paste the output of `pip freeze` or `conda list` here.
```

</details>

**Comment by purva-thakre** [comment]
Closing this as a duplicate. 

https://github.com/unitaryfund/mitiq/issues/2331#issuecomment-2176747582
