### ISSUE TITLE
Add W-state/QPE benchmarking circuits

### ISSUE THREAD

**Issue by natestemen** [unitaryfund/mitiq#1597]
We'd like to add (in [`mitiq/benchmarks`](https://github.com/unitaryfund/mitiq/tree/master/mitiq/benchmarks)) support for two new benchmarking circuits.
- **W state circuits**: $W_n = \frac{1}{\sqrt{n}} |10\cdots 00\rangle + |010\cdots0\rangle + \cdots + |0\cdots 01\rangle$. The circuit for creating these is described here: https://arxiv.org/abs/1807.05572
- **Quantum Phase Estimation**: circuits described on [wikipedia](https://en.wikipedia.org/wiki/Quantum_phase_estimation_algorithm).

**Comment by nathanshammah** [comment]
+1 for W state circuits. It can be similar to the ghz state ones, https://mitiq.readthedocs.io/en/stable/apidoc.html#module-mitiq.benchmarks.ghz_circuits.

**Comment by purva-thakre** [comment]
Does this need to be finished by the end of the current milestone ? If not, I can take it for the next one. 

My proposal is close to being accepted by the end of next week. So, I know I will have more time on my hand as well.

**Comment by purva-thakre** [comment]
Sure ! I can unassign one for now because I got lost and stopped working on it. #746

 I haven't had the chance to look at what has been completed by you and Misty in the documentation for identity scaling. 

#1426 is a quick one but I was waiting for a comment on where to put the tutorial in the docs. 

#987 and #513 are two WIP proposals currently.

**Comment by Misty-W** [comment]
hi @purva-thakre, still planning to work on this in this milestone?

**Comment by purva-thakre** [comment]
Yep !

**Comment by natestemen** [comment]
Removing this from the 0.25 milestone. A major portion of this ticket is now completed with #1723.

**Comment by purva-thakre** [comment]
@natestemen @andreamari For the QPE circuit, is better to restrict the input U to be a `cirq.Gate` ? 

I was thinking of also allowing `np.array` and then using [`cirq.deconstruct_single_qubit_matrix_into_angles`](https://quantumai.google/reference/python/cirq/deconstruct_single_qubit_matrix_into_angles) to describe the unitary in terms of valid quantum gates. This does increase the size of the circuit. 

The other option would be to create a custom gate with the provided input array. I had tried this with the W-state circuit and noticed there were quite a few issues to fix when I created a controlled-U version of my custom gate.

**Comment by andreamari** [comment]
Hi @purva-thakre, we mainly need circuits for benchmarking Mitiq techniques and not for applicaitons, so I would keep it as simple as possible. For example, by setting $U=R_Z(\theta)$, where `theta` is the a phase which is supposed to be estimated by the QPE circuit.

**Comment by purva-thakre** [comment]
Maybe I was complicating things for myself unnecessarily. 

But based on the example you provided, is U only supposed to be a 1-qubit unitary ?

**Comment by natestemen** [comment]
Woohoo! Congrats on getting both of these done Purva! It would be great if they were also added to the [API doc](https://mitiq.readthedocs.io/en/latest/apidoc.html#benchmarks) to ensure they are more discoverable.
