### ISSUE TITLE
Add simple PEC tutorial to documentation

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#1602]
## Issue Description

It would be great to add a brief PEC tutorial to the documentation in the form of a `.myst` file so that it shows up in the [examples index page](https://mitiq.readthedocs.io/en/latest/examples/examples.html).  
## Proposed Solution

I propose to simplified version of the PEC section of the research workload contained in existing supporting material for [this paper](https://arxiv.org/abs/2210.07194). For simplicity I suggest using an IBM Fake device as backend.

## Additional References

https://arxiv.org/abs/2210.07194

**Comment by Misty-W** [comment]
hi @vprusso, I added this to milestone 0.21, which closes a week from today, Nov 30. Let me know if there's anything I can do to help get this closed by then 🙂

**Comment by vprusso** [comment]
Sounds good! I will put up a draft. Any input/tweaks/etc to that draft would be much appreciated once I put up a PR. Thanks, @Misty-W !
