### ISSUE TITLE
Support (publicly) executors with bitstring output

### ISSUE THREAD

**Issue by natestemen** [unitaryfund/mitiq#1639]
Despite executors supporting functions which output acceptable forms of bit strings, there is not public method to get bit string output once the user-defined function is converted to an executor. We do have the [`executor._run`](https://github.com/unitaryfund/mitiq/blob/8aa81350f4550421f9a4cb3bbdda46fa80f4f0df/mitiq/executor/executor.py#L224-L229) function, but this is still semi-private. We should upgrade this function, or write a new one as suggested in https://github.com/unitaryfund/mitiq/pull/1614#discussion_r1052466906 to allow for this functionality.

**Comment by nathanshammah** [comment]
Community call decision is to upgrade the current function.
