### ISSUE TITLE
Use more appropriate references for REM in README

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#1654]
## Issue Description

In the [README](https://github.com/unitaryfund/mitiq#readme) file we list the error mitigation techniques that are supported in Mitiq. 
For each technique we select 1 or 2 scientific papers as references.  
Given the large number of good papers for each technique, the selection is not easy but some good preference criteria are the following:

- papers that have a clear explanation of the technique
- papers focused on the technique, instead of just using it for some application
- papers that originally introduced the technique

## Proposed Solution

Based on the previous criteria, I propose to replace the current REM references with the following two papers:

- [arXiv:1907.08518](https://arxiv.org/abs/1907.08518)
- [arXiv:2006.14044](https://arxiv.org/abs/2006.14044)

Unless there are good reasons for keeping current references, which are very good papers but not directly focused on REM.

**Comment by nathanshammah** [comment]
I can take this issue.
