### ISSUE TITLE
Calibration: `Full_output`  option for `execute_with_mitigation`

### ISSUE THREAD

**Issue by Misty-W** [unitaryfund/mitiq#1683]
A very nice-to-have suggestion: a full_output option that when `True`, `execute_with_mitigation` also returns the `best_strategy`, `improvement_factor`, etc.
Could save for future milestone, not blocking from my POV.

_Originally posted by @Misty-W in https://github.com/unitaryfund/mitiq/pull/1676#discussion_r1084760599_

**Comment by nathanshammah** [comment]
Is this closed by `cal.run(log=True)`?

**Comment by Misty-W** [comment]
> Is this closed by `cal.run(log=True)`?

Yes, the information requested in this issue can be obtained from cal.run(log=True)`.
