### ISSUE TITLE
Revamp Mitiq demo page on unitary.fund

### ISSUE THREAD

**Issue by natestemen** [unitaryfund/mitiq#1734]
We have a nice Mitiq demo page at https://unitary.fund/mitiq.html (whose code can be found [here](https://github.com/unitaryfund/unitary-fund/blob/master/mitiq.html)), but it's gotten quite out of date. This scope of this ticket is to complete the following:

1. Write some new, but similarly short, copy where needed
1. Update any resources/links
1. Create new demo code
    1. Both in Cirq and Qiskit
    1. Demo should be use [calibration workflow](https://mitiq.readthedocs.io/en/stable/guide/calibrators.html)
1. Create animations of demo code, as exist in current page. These should be short, sweet, and show an immediate improvement using Mitiq.

**Comment by nathanshammah** [comment]
I propose to update the Docs with more information about the functions and classes that have been added. One way to include them is with `autosummary`, as done [here](https://mitiq.readthedocs.io/en/stable/guide/zne-3-options.html#extrapolation-methods-factory-objects) for ZNE's Factories in the User Guide.
Example of the autosummary code:
```{eval-rst}
.. autosummary::
   :nosignatures:

   ~mitiq.zne.inference.LinearFactory
   ~mitiq.zne.inference.RichardsonFactory
   ~mitiq.zne.inference.PolyFactory
   ~mitiq.zne.inference.ExpFactory
   ~mitiq.zne.inference.PolyExpFactory
   ~mitiq.zne.inference.AdaExpFactory
```
It could be nice to also add more details about the Settings options and the `log=True` option.

I also propose to include a link to the tutorial, once it gets added.

**Comment by natestemen** [comment]
@nathanshammah I revamped the mitiq demo page on unitary.fund in https://github.com/unitaryfund/unitary-fund/pull/309. I'm not sure your comment landed on the right issue, but would you mind taking care of the requirements you added?

**Comment by Misty-W** [comment]
UF page is done. Remaining task to add Calibration paragraph in docs.
