### ISSUE TITLE
Test Calibration module

### ISSUE THREAD

**Issue by natestemen** [unitaryfund/mitiq#1735]
Let's put the [calibration](https://github.com/unitaryfund/mitiq/tree/master/mitiq/calibration) module to the test. The testing should include the following workflow as a minimum.

1. Define an executor using an IBMQ mock device (using a simulator, similar to [this tutorial](https://qiskit.org/documentation/tutorials/simulators/2_device_noise_simulation.html))
1. Define calibrator object with default `ZNESettings`
1. Run `execute_with_mitigation`

How does it perform compared to what you can get running single ZNE experiments after some manual tweaking?

Other testing that could be done:

1. The above but on a real IBMQ device
2. Modified `Settings` objects, to take full advantage of the hardware. Maybe running larger circuits, or with more scale factors, etc.

Completion of this ticket will likely be a jupyter notebook in the (private) [`mitiq-internal`](https://github.com/unitaryfund/mitiq-internal/) repo, along with hopefully some issues opened on GitHub for some potential improvements to the calibration module.

---

**Nate's request**: Ideally I'd like someone else on the Mitiq team to take this issue as it will get more eyes on the calibration API, and hopefully then more feedback as well.

**Comment by Misty-W** [comment]
I think it would be easier to make progress on this issue if there were a concrete deliverable. Not necessarily a tutorial or a major improvement to the existing one. I thought of two options for this PR:
1. Linking to the tutorial improvement PR- moving the existing workflow into the regime where calibration improves the results
2. Maintaining a Google doc of test cases and results, publishing details TBD.

**Comment by natestemen** [comment]
Much of what was spelled out in this ticket's description was completed by Nathan in the [calibration tutorial](https://mitiq.readthedocs.io/en/stable/examples/calibration-tutorial.html), and so I agree that we need something more concrete to strive for moving forward.

I prefer point 1 over 2 as I'm afraid point 2 would be recreating the [benchmarking paper](https://arxiv.org/abs/2210.07194). Maybe you have a different set of experiments in mind.

**Comment by Misty-W** [comment]
Point 1 sounds good, especially given we have some other big items in the milestone.

**Comment by Misty-W** [comment]
My apologies that I won't be able complete this in milestone 0.26.0. Happy to pick this up in the next milestone if the next MM agrees.
