### ISSUE TITLE
Calibration blog post

### ISSUE THREAD

**Issue by natestemen** [unitaryfund/mitiq#1754]
As part of the calibration launch at the end of the month, we should announce it more widely, including on https://unitary.fund/blog.html.

Details to include:
- what is calibration
- who should use it
- video snippet from Nathan's demo @ Qiskit demo day (@nathanshammah can you create the video?)
- links to docs/examples

**Comment by nathanshammah** [comment]
@natestemen here is the video, audio is not fantastic but I think it's ok...? It's still unlisted on YT.
https://youtu.be/dB_3R84ewig

**Comment by nathanshammah** [comment]
@natestemen the video is now public (not unlisted).
