### ISSUE TITLE
Review qosf challenge notebook

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#1758]
This is a reminder to review the QOSF challenge notebook by @MaldoAlberto (stored in a private repository because it contains solutions).
Deadline: March 29, but I guess earlier is better :-)

**Comment by natestemen** [comment]
public notebook: https://github.com/qosf/monthly-challenges/blob/main/challenge-2023.03-mar/challenge-2023.03-mar.ipynb
