### ISSUE TITLE
Pauli Twirling of CNOT Gate

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#1774]
## Issue Description
It could be useful to include tools to implement randomized compiling (RC), as noted already in #1245, as the technique is proving useful and widely adopted. 
## Proposed Solution
A simple approach could be that of applying a subset of the fully general technique, limiting to applying RC to CNOT gates with the introduction of Pauli rotations. 

<img width="743" alt="randomized-compiling" src="https://user-images.githubusercontent.com/14573436/230027966-5d6caf54-c313-4c85-9506-1d1da81212e2.png">

Pseudocode below
```
mitiq.rcc.execute_with_randomized_compiling(circuit, executor, rule="cnot")
```
where the protocol is similar to digital dynamical decoupling (DDD): it finds, based on a rule, the gates to substitute. It has a difference with respect to DDD, more similar to ZNE or PEC, in the sense that it generates multiple circuits based on one original and includes an extrapolation part (simple average) after the execution.

## Additional References
- "Hypothesis Testing for Error Mitigation: How to Evaluate Error Mitigation" https://arxiv.org/abs/2301.02690; the slides (relevant snapshot above) from @natestemen talk in the journal club of [Quantum Wednesday](https://github.com/unitaryfund/quantum-wednesday). 

- "Mitigating depolarizing noise on quantum computers with noise-estimation circuits", https://arxiv.org/abs/2103.08591

**Comment by purva-thakre** [comment]
I can take this as part of [my previous attempt at a RFC](https://docs.google.com/document/d/1TORbBhvJfSaPykAmqX2BersOQHwiUD2Gn3Aum4rDa2g/edit?usp=sharing). 

I have got one issue that I am currently working on and after that I was planning on linking a newer version of the randomized compiling RFC anyway. This was my plan for the upcoming milestone.

**Comment by nathanshammah** [comment]
Focusing sounds great to me, @purva-thakre!

**Comment by purva-thakre** [comment]
@nathanshammah What was your motivation behind using `rule="cnot"` ? 

To me, it looks like you want to apply randomized compiling to the CNOT gate only ? Or just 1 layer in the circuit ?

**Comment by Misty-W** [comment]
Consider reusing PEC modules- idea of replacing a gate. 
@natestemen, @purva-thakre, @Aaron-Robertson, @andreamari
