### ISSUE TITLE
DDD tutorial broken thumbnail

### ISSUE THREAD

**Issue by natestemen** [unitaryfund/mitiq#1783]
Navigate to the [examples](https://mitiq.readthedocs.io/en/stable/examples/examples.html) and scroll to the bottom. The [DDD with Qiskit on GHZ circuits](https://mitiq.readthedocs.io/en/stable/examples/ddd_on_ibmq_ghz.html) demo has a broken thumbnail.

<img width="204" alt="Screenshot 2023-04-12 at 1 30 25 PM" src="https://user-images.githubusercontent.com/12703123/231577227-32438e5a-75fe-47f0-b939-48f985450d6b.png">

@Misty-W

**Comment by Misty-W** [comment]
Thanks for alerting me @natestemen, I'm guessing an update is needed in `conf.py`, TBC. Plan to fix as part of PR #1762, as it's a cleanup anyway.
