### ISSUE TITLE
Tutorial : Use ZNE to simulate quantum many body scars (QMBS)

### ISSUE THREAD

**Issue by purva-thakre** [unitaryfund/mitiq#1797]
Proposed solution to close this issue is in #1773 

https://arxiv.org/abs/2203.08291

ZNE (dynamical decoupling + readout error mitigation technique) is used to mitigate results in Fig 3.

**Comment by DHuybrechts** [comment]
In case this still needs to be solved, I would like to try my hand at it.

**Comment by purva-thakre** [comment]
Assigned it to you @DHuybrechts
