### ISSUE TITLE
PEC removes measurement gates from circuits

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#1805]
PEC removes measurement gates from circuits

## To reproduce

- create a circuit with measurement gates.

```
import cirq
from mitiq.benchmarks import generate_rb_circuits

circuit = generate_rb_circuits(2, 1)[0]
circuit.append(cirq.measure(circuit.all_qubits()))
```
- apply `pec.sample_circuit(circuit, ...)`

The output has no measurement gates but it should.

**Comment by purva-thakre** [comment]
Can I take this for the next Milestone?

**Comment by andreamari** [comment]
Hi @purva-thakre, actually I am working on this and I was planning to make a PR soon. Sorry for the late info, I should have self-assigned earlier.
