### ISSUE TITLE
Implement main utility functions for QSE

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#1811]
Implement main utility functions for quantum subspace expansion (QSE).

This is a sub-issue of #818.

Create a new module: `mitiq/qse` 
Insert necessary files.
Insert main utility functions for QSE.
Do not insert, high level functions such as `execute_with_qse` at this stage.

**Comment by nathanshammah** [comment]
@bubakazouba thanks for addressing the first issue (#1810), we think that this issue could come next, to simplify porting the full functionality of QSE step by step. We included it in the current milestone just to make sure we have time to review any possible PR. In case you happen to be able to work on it, this month or the next, please feel free to reach out for help in review or guidance.
