### ISSUE TITLE
Debugger warning about frozen modules in docs build

### ISSUE THREAD

**Issue by Misty-W** [unitaryfund/mitiq#1826]
The following warning occurs at every notebook execution in the docs build:

> 0.00s - Debugger warning: It seems that frozen modules are being used, which may
> 0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
> 0.00s - to python to disable frozen modules.
> 0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.

See https://github.com/unitaryfund/mitiq/actions/runs/4921156704/jobs/8790708057?pr=1745 for an example.

See https://stackoverflow.com/questions/75114841/debugger-warning-from-ipython-frozen-modules for solution options.

**Comment by natestemen** [comment]
Best practice to link to the line in the build where the warning is occurring so future us don't have to go looking for it: https://github.com/unitaryfund/mitiq/actions/runs/4921156704/jobs/8790708057?pr=1745#step:6:43
