### ISSUE TITLE
Make mitiq compatible with latest version of Qiskit

### ISSUE THREAD

**Issue by natestemen** [unitaryfund/mitiq#1835]
Currently Mitiq is built using [Qiskit 0.41.1](https://github.com/unitaryfund/mitiq/blob/b5f3a06069a5b72a19b8b799a4f17803b7ed5589/dev_requirements.txt#L2), and [Qiskit 0.43.0](https://github.com/Qiskit/qiskit-metapackage/releases/tag/0.43.0) has been released. Dependabot [opened a PR](https://github.com/unitaryfund/mitiq/pull/1822) to upgrade our support, but the tests are failing [[example](https://github.com/unitaryfund/mitiq/actions/runs/4958942450/jobs/8872435802)].

Resolution of this issue will amount to upgrading the qiskit version, and making the necessary API changes to qiskit functions so that code coverage remains the same, and the tests pass.

We've also ran into some deprecation warnings in the past in https://github.com/unitaryfund/mitiq/issues/1533. Resolving those would be an added bonus is they are still deprecation warnings in Qiskit 0.43.0.

**Comment by andre-a-alves** [comment]
If not spoken for, could you assign this issue to me, please? I should be able to take care of it this week or next if no one else is working on it, yet.

**Comment by natestemen** [comment]
Hey André, I didn't want to reply until now because this is one of the bounties that are up for unitaryHACK 2023! Feel free to have a go. It's worth [$80](https://unitaryhack.dev/projects/mitiq).
