### ISSUE TITLE
Draft PR workflow handles separated tests improperly

### ISSUE THREAD

**Issue by Aaron-Robertson** [unitaryfund/mitiq#1851]
## Issue Description

When a change is made to `/mitiq/interface/conversions.py` testing will fail (and likely applies to any change where tests are separate from the code, i.e. code tested in `/mitiq/tests/`).

## How to Reproduce

See the draft PR workflow runs from #1850.

## Suggested Solution

We should make sure to ignore pyquil tests, and in draft PRs may want to either ignore the `/mitiq/tests/` directory, or run it by default.

**Comment by Misty-W** [comment]
Nice to have, not sure if possible/practical: Codecov report (at least the “patch” coverage report) on draft PRs.

**Comment by natestemen** [comment]
We removed the draft PR workflow in https://github.com/unitaryfund/mitiq/pull/2019, closing.
