### ISSUE TITLE
ZNE test failing non-deterministically

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#1896]
The `test_with_observable_batched_factory` test is quite old but, for some reason, it seems to fail more often in the last weeks.
See e.g.:
https://github.com/unitaryfund/mitiq/actions/runs/5423886272/jobs/9862463130#step:5:3881

I would suggest to have a look under the hood  to check that everything works as expected, e.g. what circuits are executed, what results are obtained, etc.. 

If everything works, we should probably modify this test to make it deterministic.

**Comment by purva-thakre** [comment]
The linked logs have expired.

**Comment by cosenal** [comment]
Copying over @purva-thakre's report from #2442, which has got non-stale logs.

---
Noticed the failure here: https://github.com/unitaryfund/mitiq/actions/runs/9814019705/job/27101033866#step:6:4363

If I rerun the workflow, the test passes. 

![image](https://github.com/unitaryfund/mitiq/assets/66048318/328732a8-e757-4f5c-bc3d-f6516735f688)

https://github.com/unitaryfund/mitiq/blob/e61c058777b11cc34b81be05e78b1c4bc91d7775/mitiq/zne/tests/test_zne.py#L81-L101

https://github.com/unitaryfund/mitiq/blob/e61c058777b11cc34b81be05e78b1c4bc91d7775/mitiq/interface/mitiq_cirq/cirq_utils.py#L17

**Comment by Shivansh20128** [comment]
Hey! This error resurfaced again [here](https://github.com/unitaryfund/mitiq/actions/runs/11798888714/job/32866119137#step:6:4421).
