### ISSUE TITLE
Docs freeze at scars example

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#1911]
## Issue Description

The documentation is stuck at building, seemingly things freeze at the many body scars example. It is running on my laptop since 10 minutes at least. 
```
~github/mitiq/docs/source/examples/quantum_simulation_scars_ibmq.md: Executing notebook using local CWD [mystnb]
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
```

## How to Reproduce

1. ...
2. ...
3. ...

## Expected behavior

---

<details>
<summary>Environment Context</summary>

Use the `about()` function to summarize information on operating system, python version and dependencies.
```python
from mitiq import about
about()
```

Additional Python Environment Details (`pip freeze` or `conda list`):

```
Copy and paste the output of `pip freeze` or `conda list` here.
```

</details>

**Comment by purva-thakre** [comment]
This might be related to the previous discussion in an issue related to another tutorial raising similar warnings locally. 

https://github.com/unitaryfund/mitiq/issues/1846#issuecomment-1607944101

I don't see the same warning being raised in the docs build for the tutorial's PR.

https://github.com/unitaryfund/mitiq/actions/runs/5442916617/jobs/9898765261#step:6:1

Maybe we need to figure out a proper solution to disabling checks on a user's local device.

**Comment by natestemen** [comment]
@nathanshammah can you provide notes on how to reproduce or more context? I cannot reproduce this issue.

**Comment by natestemen** [comment]
This doesn't seem to be an issue anymore (as far as I can tell by running `rm -rf docs/build && make docs`). If it is, please reopen with steps to reproduce
