### ISSUE TITLE
PT+ ZNE Tutorial and Pauli Transfer Matrix (PTM) in Cirq

### ISSUE THREAD

**Issue by purva-thakre** [unitaryfund/mitiq#1914]
Add tutorial combining ZNE with PT and show this via PTM. 

To show that pauli twirling has worked and the noise has been tailored, PTM superoperator could be used. 

If twirling is done perfectly, the off-diagonal terms in this superoperator should be suppressed. An example of this is in Sec VII of the supplemental material of https://arxiv.org/abs/2010.00215

before:
![image](https://github.com/unitaryfund/mitiq/assets/66048318/9b42e03e-cb44-4bf3-b98b-bcd537168bfd)

after:

![image](https://github.com/unitaryfund/mitiq/assets/66048318/a2db365e-b262-47f9-b1d0-dc23de8dd753)

This superoperator is defined in Qiskit : https://qiskit.org/documentation/stubs/qiskit.quantum_info.PTM.html

Use PTM in cirq to show `execute_with_pauli_twirling` has worked as expected.

**Comment by purva-thakre** [comment]
I have got a crude working code for finding the PTM matrix in the first screenshot of this issue's description. It depends on the channel superoperator acting on a vectorized form of Pauli matrices. 

![image](https://github.com/unitaryfund/mitiq/assets/66048318/1d2b4771-2e10-444b-bce1-6668dd941ff6)

## Imports
```python
import cirq
import numpy as np
```
## Defining functions to vectorize a matrix & to get a matrix from a vectorized array
```python
def matrix_vec(matrix):
    """Defines the vectorized form of a numpy array."""
    matrix_transpose = np.transpose(matrix)
    return(np.reshape(matrix_transpose, (-1,1)))

def matrix_no_vec(vec_matrix):
    """Defines the matrix form of a vectorized state."""
    vec_to_matrix = np.reshape(vec_matrix, (2,2))
    return(np.transpose(vec_to_matrix))
```
## Create a vectorized list of paulis
```python
pauli_list = [cirq.unitary((cirq.I)), cirq.unitary((cirq.X)), cirq.unitary((cirq.Y)), cirq.unitary((cirq.Z))]
pauli_vec_list = []
for i in range(len(pauli_list)):
    pauli_vec_list.append(matrix_vec(pauli_list[i]))
```
## Defining the PTM matrix function
```python
def ptm_matrix(circuit):
    superop = cirq.kraus_to_superoperator(cirq.kraus(circuit))
    
    ptm_matrix = np.zeros([4,4],dtype=complex)

    for i in range(len(pauli_vec_list)):
        superop_on_pauli_vec = np.matmul(superop, pauli_vec_list[i])
        superop_on_pauli_matrix = matrix_no_vec(superop_on_pauli_vec)
        ptm_matrix_row = []
        for j in range(len(pauli_list)):
            pauli_superop_pauli = np.matmul(pauli_list[j], superop_on_pauli_matrix)
            ptm_matrix_row.append(0.5*np.trace(pauli_superop_pauli))
        ptm_matrix[i] = ptm_matrix_row
    return(ptm_matrix)
```
## Testing the PTM function
```python
q0= cirq.LineQubit(0)
circuit = cirq.Circuit()
circuit.append(cirq.Rz(rads=0.25 * np.pi)(q0))

ptm_matrix(circuit)
```
```
array([[ 1.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  5.55111512e-17+0.j],
       [ 0.00000000e+00+0.j,  7.07106781e-01+0.j, -7.07106781e-01+0.j,  0.00000000e+00+0.j],
       [ 0.00000000e+00+0.j,  7.07106781e-01+0.j,  7.07106781e-01+0.j,  0.00000000e+00+0.j],
       [ 5.55111512e-17+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  1.00000000e+00+0.j]])
```

I think an easier method would be to change the basis of the superoperator to a Pauli basis. Need to plan the implementation of this as it will be easy to generalize to cases where the circuit has >1 qubits.

**Comment by purva-thakre** [comment]
@Misty-W I think using a PTM matrix would work when CNOT/CZ are the only gates contributing to the off-diagonal terms in the PTM matrix. 

My example is for a Z-rotation. The off-diagonal terms will not go away after Pauli twirling as Mitiq's method only works for CZ and CNOT gates.

**Comment by Misty-W** [comment]
hi @purva-thakre, sorry for the delayed response. Was finalizing conference submissions etc. last week. 

I prefer Option 1 for now, we can expand to Option 2 when we extend the technique.

**Comment by purva-thakre** [comment]
@Misty-W No worries. 

Will this be a function defined in the tests folder? Or a separate function `verify_pt_tailored_noise` in [mitiq/pt/pt.py](https://github.com/unitaryfund/mitiq/blob/master/mitiq/pt/pt.py) ?

**Comment by Misty-W** [comment]
> Will this be a function defined in the tests folder? Or a separate function `verify_pt_tailored_noise` in [mitiq/pt/pt.py](https://github.com/unitaryfund/mitiq/blob/master/mitiq/pt/pt.py) ?

Hmmm, my first inclination is to put it in the tests, but is there another use you have in mind for this function as a sort of PT utility?

**Comment by purva-thakre** [comment]
>  is there another use you have in mind for this function as a sort of PT utility?

If we want to demonstrate Pauli Twirling worked as expected in a tutorial or an example, use the function to compare the off-diagonal matrix entries before and after.

**Comment by Misty-W** [comment]
> > is there another use you have in mind for this function as a sort of PT utility?
> 
> If we want to demonstrate Pauli Twirling worked as expected in a tutorial or an example, use the function to compare the off-diagonal matrix entries before and after.

Got it! Let's make it a function in mitiq.pt/pt.py.

**Comment by Misty-W** [comment]
hi @purva-thakre, wanted to check if this issue will be completely solved by #1987, or only partially. If only partially, I'd suggest to move this issue out of the milestone.

**Comment by purva-thakre** [comment]
Superseded by #2374

**Comment by cosenal** [comment]
@purva-thakre apologies, I hadn't realised this was opened already. Happy to close #2374, since this has more context.

**Comment by purva-thakre** [comment]
@cosenal No worries! Sounds like you are close to completing the other issue anyway. 

I wouldn't have gotten to making a PR for this until #2346 was successfully merged.
