### ISSUE TITLE
'noise_level' of 'initialized_depolarizing_noise' correct?

### ISSUE THREAD

**Issue by lemon1256** [unitaryfund/mitiq#1918]
For this noise model:

from mitiq.interface.mitiq_qiskit.qiskit_utils import initialized_depolarizing_noise
noise_model = initialized_depolarizing_noise(noise_level=0.001)

The annotation of this function says:

Args:
        noise_level: The noise strength as a float, e.g., 0.01 is 0.1%.

Why 0.1% instead of 1%? Commonly, 0.01 is used to present 1%.

**Comment by lemon1256** [comment]
Nice

**Comment by natestemen** [comment]
Just so it's tracked properly, I will reopen this and it will be closed when #1919 is closed.
