### ISSUE TITLE
Add example on shadow estimation

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#1930]
## Issue Description
Add example on shadow estimation. 
## Proposed Solution
Use existing ipynb Jupyter notebook and transform it into myst file (.md), adding it to the Examples section of the documentation 
## Additional References
Cite PennyLane tutorial and code within the notebook.

**Comment by Min-Li** [comment]
Thanks for creating this @nathanshammah!  I'll add this file this after we merge the main function into Mitiq!  Then this could be run by merging whole shadows/ in!
