### ISSUE TITLE
Contributing doc note for zsh shell

### ISSUE THREAD

**Issue by bdg221** [unitaryfund/mitiq#1988]
## Issue Description
On step 5 of the Development environment section of the [Contributing to Mitiq](https://mitiq.readthedocs.io/en/latest/contributing.html) page, if [z shell](https://www.zsh.org/) (zsh) is used, the `.[development]` needs to have quotes around it.

## How to Reproduce

1. Set the terminal to use z-shell by running: `zsh`
2. Try to run the following command according to step 5:
  `pip install -e .[development]`
3. The following error is then seen:
  `zsh: no matches found: .[development]`

## Expected behavior

It is expected that users can simply copy and paste the provided command from the documentation and successfully install the dependencies of Mitiq.

## Proposed Solution:

Since this only effects z shell users, it is recommend that a note is added mentioning the potential error and the workaround.

Note: If the command above fails with the error: "zsh: no matches found: .[development]", this is a behavior of z shell and can be corrected by including quotes around .[development] like:
pip install -e ".[development]"

**Comment by natestemen** [comment]
Any reason not to quote the command for all users? Does quoting it break other shells? If not, lets just quote it for everyone.

BTW thanks for flagging this and opening the issue! Much appreciated.

**Comment by bdg221** [comment]
I tested with bash and it works with the quote. It does make sense to have a single solution without any notes.

**Comment by natestemen** [comment]
What about quotes with a comment saying something like "quoting needed for z-shell users"? Maybe a link to the stackoverflow post if you think it's a good idea.

**Comment by bdg221** [comment]
I think it may be a bit overkill (which isn't necessarily a bad thing.) My guess is that most users aren't hitting the error. It would just be nice if somebody did hit the error to have a quick solution readily available. So, I would say either to go with the quotes there and no note or how it currently is with a note added for z-shell users.

**Comment by natestemen** [comment]
I vote fix the problem for everyone by quoting.

**Comment by Misty-W** [comment]
Fixed by PR #1997 .
