### ISSUE TITLE
Speed up Mitiq tests

### ISSUE THREAD

**Issue by Misty-W** [unitaryfund/mitiq#1998]
## Issue Description

This is a continuation of the progress made on speeding up Mitiq's tests in milestone 0.29. 
previous issue: https://github.com/unitaryfund/mitiq/issues/1427
first PR speeding up tests: https://github.com/unitaryfund/mitiq/pull/1996

## Proposed Solution

Remove redundant tests, and look for other opportunities to reduce test time.

**Comment by natestemen** [comment]
previous issue: https://github.com/unitaryfund/mitiq/issues/1427
first PR speeding up tests: https://github.com/unitaryfund/mitiq/pull/1996
