### ISSUE TITLE
`noise_level` missing from calibrator logs

### ISSUE THREAD

**Issue by natestemen** [unitaryfund/mitiq#2013]
Running the calibration experiments with the `PECSettings` object logs the following table.
<img width="575" alt="Screenshot 2023-09-12 at 8 37 51 AM" src="https://github.com/unitaryfund/mitiq/assets/12703123/62443e10-890f-4f30-8196-23395634c84d">

It is not clear from the table how the two runs for each `circuit type` are any different. The difference comes from the `noise_level` parameter set within the strategies section of `PECSettings`:
https://github.com/unitaryfund/mitiq/blob/ee85edf48557c85c4f6d0b1e1d74d74fc882c9d4/mitiq/calibration/settings.py#L467-L486

This should be logged as part of this table.

**Comment by kozhukalov** [comment]
Please assign this to me
