### ISSUE TITLE
Error in Draft Workflow

### ISSUE THREAD

**Issue by purva-thakre** [unitaryfund/mitiq#2018]
### Discussed in https://github.com/unitaryfund/mitiq/discussions/1990

<div type='discussions-op-text'>

<sup>Originally posted by **purva-thakre** September  1, 2023</sup>
Draft Github Actions workflow was failing for all versions with error `Error: Unable to process file command 'env' successfully.`. 

https://github.com/unitaryfund/mitiq/actions/runs/6054448774/job/16431867571 

The same builds pass when the PR is not a draft.

</div>

Option 1 - remove the workflow for draft PR
Option 2 - figure out a way to allow changes to multiple files (as stated in the linked discussion)

The draft workflows don't take too long compared to a non-draft workflow as the tests are run only on the changes made in the PR. Option 2 would be a preferable solution but in case that doesn't work, option 1 would be the fallback solution.

**Comment by natestemen** [comment]
I vote to remove, and spend more time on https://github.com/unitaryfund/mitiq/issues/1998
