### ISSUE TITLE
Add section to `contributing_docs.md` about adding references 

### ISSUE THREAD

**Issue by Misty-W** [unitaryfund/mitiq#2029]
Mitiq's [contributing docs](https://mitiq.readthedocs.io/en/stable/contributing_docs.html) need a section on adding references in the [Mitiq bibliography](https://mitiq.readthedocs.io/en/stable/bibliography.html) when updating / adding documentation.

**Comment by Misty-W** [comment]
@bdg221

**Comment by bdg221** [comment]
Feel free to assign to me.

**Comment by purva-thakre** [comment]
This issue could also add details about the things to do when an example is added to the documentation. 

- Update details on how to [insert a thumbnail](https://github.com/unitaryfund/mitiq/blob/0c0b7a0fe73f582aa1974c4ab3c49b9da0b5753e/docs/source/conf.py#L334) when adding an example to the documentation. 
- Add a few lines ([or a subsection here](https://mitiq.readthedocs.io/en/stable/contributing_docs.html#build-the-documentation-locally)) on how they can view the RTD build in a PR. In short, they can click on `details` of the last line in the screenshot. 

![image](https://github.com/unitaryfund/mitiq/assets/66048318/fa2563d5-f286-463e-a0b5-90ad2625e3c4)
