### ISSUE TITLE
`pec.sample_circuit` drops idle qubits

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#2061]
## Issue Description

Circuits returned by `pec.sample_circuit` do not contain idle qubits present in the original circuit, and also have different register names.

## How to Reproduce

```python
import qiskit
from mitiq import pec

# Circuit.
qreg = qiskit.QuantumRegister(3, name="Q")
circuit = qiskit.QuantumCircuit(qreg)
circuit.h(qreg[0])
circuit.cnot(qreg[0], qreg[1])
circuit.measure_active()
print(circuit)
#            ┌───┐      ░ ┌─┐   
#       Q_0: ┤ H ├──■───░─┤M├───
#            └───┘┌─┴─┐ ░ └╥┘┌─┐
#       Q_1: ─────┤ X ├─░──╫─┤M├
#                 └───┘ ░  ║ └╥┘
#       Q_2: ───────────░──╫──╫─
#                       ░  ║  ║ 
# measure: 2/══════════════╩══╩═
#                          0  1 

# Representation.
cnot_circuit = qiskit.QuantumCircuit(qreg)
cnot_circuit.cnot(qreg[0], qreg[1])
rep = pec.represent_operation_with_global_depolarizing_noise(cnot_circuit, noise_level=0.01)

# Sample.
circuits, *_ = pec.sample_circuit(circuit, [rep])
for circuit in circuits:
    print(circuit)
#                    ┌───┐     ┌─┐   
#               q_0: ┤ H ├──■──┤M├───
#                    └───┘┌─┴─┐└╥┘┌─┐
#               q_1: ─────┤ X ├─╫─┤M├
#                         └───┘ ║ └╥┘
# m_reg_measure_0: 1/═══════════╩══╬═
#                               0  ║ 
# m_reg_measure_1: 1/══════════════╩═
#                                  0 
```

## Expected behavior

The circuit(s) returned by `pec.sample_circuit` should have the same registers and qubits as the input circuit: here, one register named "Q", the qubit "Q_2" present, and one measurement register named "measure" with two bits.

---

<details>
<summary>Environment Context</summary>

Use the `about()` function to summarize information on operating system, python version and dependencies.
```python
from mitiq import about
about()
```

```text
Mitiq: A Python toolkit for implementing error mitigation on quantum computers
==============================================================================
Authored by: Mitiq team, 2020 & later (https://github.com/unitaryfund/mitiq)

Mitiq Version:	0.30.0

Core Dependencies
-----------------
Cirq Version:	1.2.0
NumPy Version:	1.26.1
SciPy Version:	1.11.2

Optional Dependencies
---------------------
PyQuil Version:	3.2.1
Qiskit Version:	0.44.2
Braket Version:	Not installed

Python Version:	3.10.13
Platform Info:	Linux (x86_64)
```

Additional Python Environment Details (`pip freeze` or `conda list`):

```
Copy and paste the output of `pip freeze` or `conda list` here.
```

</details>

**Comment by rmlarose** [comment]
Thanks @andreamari I also identified this as the origin of the issue. I remember going through this process with ZNE and I think PEC just needs to use the fixes we implemented there. Hopefully it's fairly easy to do - perhaps a `sample_once` function which could be wrapped by the decorator and then is repeatedly called by `sample_circuit`?

**Comment by andreamari** [comment]
That could work but I am checking if it's possible to have a one-to-many decorator which would make things more efficients. In the past I remember that sampling circuits one-by-one was very slow and so we decided to sample all circuits  in a single batch.
