### ISSUE TITLE
Pytest RuntimeWarning

### ISSUE THREAD

**Issue by purva-thakre** [unitaryfund/mitiq#2103]
[Following warning](https://github.com/unitaryfund/mitiq/actions/runs/7053761686/job/19201430837#step:6:4068) is raised by pytest:

```
mitiq/rem/tests/test_inverse_confusion_matrix.py::test_closest_positive_distribution_error
  /home/runner/work/mitiq/mitiq/mitiq/rem/inverse_confusion_matrix.py:145: RuntimeWarning: invalid value encountered in divide
    init_guess /= np.sum(init_guess)
```

Test in question

https://github.com/unitaryfund/mitiq/blob/3457774734f9759c2a828d84ad5af3801eab23e1/mitiq/rem/tests/test_inverse_confusion_matrix.py#L187-L190

To close this issue, need to disable this warning as the test is expected to raise an error with an invalid input. 
https://stackoverflow.com/a/23116937

**Comment by natestemen** [comment]
More info about writing warnings filters: https://docs.python.org/3/library/warnings.html#warning-filter
