### ISSUE TITLE
Codecov build failure

### ISSUE THREAD

**Issue by purva-thakre** [unitaryfund/mitiq#2131]
Noticed 1 test consistently failing in #1936 

https://github.com/unitaryfund/mitiq/actions/runs/7254911112/job/19764545557#step:7:40

![image](https://github.com/unitaryfund/mitiq/assets/66048318/d28fade2-51e5-4eeb-8c21-09be264617b9)

Re-running the failed test does work but this has to be done for each commit triggering the CI workflow. 

It appears the test failure can be fixed by generating a new secret token. 
https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954

**Comment by natestemen** [comment]
Thanks for raising this! We should take a renewed look at it. I'm going to close this since we have a ticket open for it already here: https://github.com/unitaryfund/mitiq/issues/1584

BTW did you mean to link to #1936?

**Comment by purva-thakre** [comment]
> BTW did you mean to link to https://github.com/unitaryfund/mitiq/issues/1936?

Ah no. I meant to link to failing tests in #2034
