### ISSUE TITLE
Set up release workflow with PyPI Trusted Publishers

### ISSUE THREAD

**Issue by natestemen** [unitaryfund/mitiq#2150]
### Background

In April 2023 PyPI [released](https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/) a new publishing method using the [OpenID Connect](https://openid.net/developers/how-connect-works/) standard [[GitHub docs](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect)]. This standard is described as

> an interoperable authentication protocol based on the OAuth 2.0 framework of specifications (IETF RFC 6749 and 6750). It simplifies the way to verify the identity of users based on the authentication performed by an Authorization Server [...] **Best of all, it removes the responsibility of setting, storing, and managing passwords which is frequently associated with credential-based data breaches.**

More details can be found in the PyPI docs [here](https://docs.pypi.org/trusted-publishers/#quick-background-publishing-with-openid-connect), but because we set and store long-term passwords for use in our github actions, this is a welcome addition.

### Fix

The changes required are laid out in the [PyPI docs](https://docs.pypi.org/trusted-publishers/adding-a-publisher/). One of the suggested changes (for increased security) is to create an environment in which the release originates. This allows for further restrictions and rules to be applied as to when the release happens. GitHub docs [here](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment).

We will also need to change code in two places to use the [`pypa/gh-action-pypi-publish`](https://github.com/pypa/gh-action-pypi-publish) action:

- [`.github/workflows/publish-pypi.yml`](https://github.com/unitaryfund/mitiq/blob/master/.github/workflows/publish-pypi.yml)
- [`.github/workflows/publish-testpypi.yml`](https://github.com/unitaryfund/mitiq/blob/master/.github/workflows/publish-testpypi.yml)

This may potentially alter our [release docs](https://github.com/unitaryfund/mitiq/blob/master/docs/source/release.md) as well. If so, they should be updated accordingly.

**Comment by Misty-W** [comment]
No PR in milestone 0.34.0.
