### ISSUE TITLE
Remove unused folding functions

### ISSUE THREAD

**Issue by natestemen** [unitaryfund/mitiq#2189]
Currently we have the following folding techniques built into Mitiq:

- [`fold_all`](https://github.com/unitaryfund/mitiq/blob/50cf3be8875521110e23a8796150ab3458446fa6/mitiq/zne/scaling/folding.py#L209) (which is local folding)
- [`fold_global`](https://github.com/unitaryfund/mitiq/blob/50cf3be8875521110e23a8796150ab3458446fa6/mitiq/zne/scaling/folding.py#L270)
- [`fold_gates_from_left`](https://github.com/unitaryfund/mitiq/blob/50cf3be8875521110e23a8796150ab3458446fa6/mitiq/zne/scaling/folding.py#L543)
- [`fold_gates_from_right`](https://github.com/unitaryfund/mitiq/blob/50cf3be8875521110e23a8796150ab3458446fa6/mitiq/zne/scaling/folding.py#L628)
- [`fold_gates_at_random`](https://github.com/unitaryfund/mitiq/blob/50cf3be8875521110e23a8796150ab3458446fa6/mitiq/zne/scaling/folding.py#L713)

Since the addition of `fold_gates_from_left`/`right` [4 years ago](https://github.com/unitaryfund/mitiq/commit/540f3d664eb7c62e94e3017ff348d67fcc1b1f2f) they have not seen widespread use. We should remove these folding techniques as long as they are not used in

1. Any projects on GitHub
2. ZNE research over the past year or two

@Misty-W @andreamari any objections/comments? The one downside to removing these folding techniques is that it's one less option for a user to choose from.

**Comment by natestemen** [comment]
Misty and I did some searching today in attempt to remove `fold_gates_from_left`/`right`. We found that these two functions are used in the Mitiq paper codeblocks [here](https://github.com/unitaryfund/mitiq/blob/c5afbd4df6850cacc331a1aa1a477265d4bb584a/docs/source/examples/mitiq-paper/mitiq-paper-codeblocks.md?plain=1#L178) and [here](https://github.com/unitaryfund/mitiq/blob/c5afbd4df6850cacc331a1aa1a477265d4bb584a/docs/source/examples/mitiq-paper/mitiq-paper-codeblocks.md?plain=1#L195).

Removing these two functions would result in either breaking this page on our documentation, or modifying it to say that this code block does not run anymore because the function was removed.

**Comment by andreamari** [comment]
> Potential course of action is to remove these functions, and add a note to the codeblock documentation page saying this function was removed as of version 0.x.y.

Sounds good!

**Comment by jordandsullivan** [comment]
Do we want to keep a dummy function for these two around in order to raise a warning that they were deprecated? For instance:
```
from warnings import warn 

def fold_gates_from_left(*args):
...     warn('`fold_gates_from_left` is no longer supported. Use `fold_gates_at_random` or `fold_all` or `fold_global`', DeprecationWarning)
```

Or do we just want to delete both entirely and only add a note about the deprecation in the Mitiq whitepaper code as @Misty-W shared [here](https://github.com/unitaryfund/mitiq/blob/c5afbd4df6850cacc331a1aa1a477265d4bb584a/docs/source/examples/mitiq-paper/mitiq-paper-codeblocks.md?plain=1#L178) and [here](https://github.com/unitaryfund/mitiq/blob/c5afbd4df6850cacc331a1aa1a477265d4bb584a/docs/source/examples/mitiq-paper/mitiq-paper-codeblocks.md?plain=1#L195)?

**Comment by natestemen** [comment]
We haven't done a whole lot of deprecating here on Mitiq, so naturally I lean towards removing. Especially since they are functions that don't seem to be used much. **That said** I definitely don't think it's a bad idea and it's a nicer user experience, just a little bit more work on our end. Happy for @jordandsullivan to make the call (remove/deprecate).

**Comment by jordandsullivan** [comment]
I vote we just remove since we know these are not widely used functions.

Best,
Jordan Sullivan
