### ISSUE TITLE
Check for measurement gates in Cirq folding functions

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#22]
Folding functions should ignore measurement gates and continue to try to fold other gates. No unit tests currently check circuits with measurements in them.

**Comment by andreamari** [comment]
We should think how to do the global unitary_folding in the case in which we have measurements in the middle of the circuit (final measurements can be removed and re-appended after folding). Maybe, in this case of intermediate measurements, global folding is just impossible and we should only raise an error.

**Comment by rmlarose** [comment]
Will and I briefly discussed the possibility of new theory for folding circuits with intermediate measurements, but for now I think raising an error is the right thing to do. (And to ignore terminal measurements while folding.)

**Comment by willzeng** [comment]
I believe this was closed by #35
