### ISSUE TITLE
Server Rules

### ISSUE THREAD

**Issue by purva-thakre** [unitaryfund/mitiq#2203]
To avoid spam on the discord server, we want to make sure there are sufficient rules against spammy messages in all channels. 

https://support.discord.com/hc/en-us/articles/1500000466882-Rules-Screening-FAQ
https://www.reddit.com/r/discordapp/comments/19bqpz7/hi_how_can_i_prevent_somebody_from_posting_a_spam/
https://www.reddit.com/r/discordapp/comments/f34gxm/any_extra_measures_to_prevent_inappropriate_spam/
https://www.reddit.com/r/discordapp/comments/194dlhb/how_to_stop_spam_messages_from_bots_and/
https://www.reddit.com/r/discordapp/comments/vtvj82/invite_spam_problem/

cc: @Aaron-Robertson since you were interested in working on this

**Comment by cosenal** [comment]
@KallieFerguson I know you added some anti-spam rules on our Discord. Can you please document them here, and close this? 🙏

**Comment by KallieFerguson** [comment]
I enabled new features on Discord to help with the spam:

1. Members must actively accept the server rules (code of conduct, no spamming, etc.) before they can talk or DM.
2. messages with more than 15 unique mentions will be blocked and a message sent to mod-message channel for approval for admins before it will get posted.
3. Messages discord suspects may be spam will be blocked and an alert sent to mod-message where an admin can approve it if it's not spam.
4. Enabled the feature to block messages containing common insults, slurs, sexual content, or severe profanity with an alert sent to mod-message. 

I did not anything specific to our server, but as an FYI you can also add custom words you want blocked, in case anything comes up.

**Comment by KallieFerguson** [comment]
I don't believe I have permissions to close this issue, so please go ahead and close when you get a chance!

**Comment by purva-thakre** [comment]
Hi @KallieFerguson, I know we recently closed this but I think we need an additional set of rules. 

I don't have the permission to ban a spammer. I kicked out one person last week and another today after they pushed a spammy message to all channels. Is there a way to stop back-to-back messages in each and every channel?
