### ISSUE TITLE
Drop Python 3.9 support

### ISSUE THREAD

**Issue by purva-thakre** [unitaryfund/mitiq#2215]
`cirq` plans to [drop Python 3.9](https://github.com/quantumlib/Cirq/issues/6463) by April 2024 because that's the deadline set by `numpy`. 

![image](https://github.com/unitaryfund/mitiq/assets/66048318/d73f7023-762e-4482-9641-59fba05169ab)

We should also drop support for Python 3.9 by this deadline.

**Comment by natestemen** [comment]
It's worth noting that Python 3.9 will get security updates until Oct 2025. See https://endoflife.date/python

Before we drop support for python 3.9, we should [support python 3.12](https://github.com/unitaryfund/mitiq/pull/2066).
