### ISSUE TITLE
Add documentation on effectively scaling CDR 

### ISSUE THREAD

**Issue by natestemen** [unitaryfund/mitiq#2241]
In https://github.com/unitaryfund/mitiq/issues/712 it was proposed to to add an efficient near-Clifford simulator to Mitiq to ensure that Clifford Data Regression (CDR) scales well. In general we should adhere to the mantra of [_Make each program do **one** thing well_](https://en.wikipedia.org/wiki/Unix_philosophy). For that reason we should avoid adding a wrapper around a near-Clifford simulator inside Mitiq, but ensure we mention the need for this type of simulator when scaling CDR to larger number of qubits/layers in our documentation. It might be worth adding links to a few options out there.

I think this should go somewhere in the [CDR guide](https://mitiq.readthedocs.io/en/stable/guide/cdr.html). Potentially in [`docs/source/guide/cdr-2-use-case.md`](https://github.com/unitaryfund/mitiq/blob/671c8dbd5c26e46557c8af525f3756d9487998be/docs/source/guide/cdr-2-use-case.md).

**Comment by bdg221** [comment]
I plan to include the doc updates in the [here](https://mitiq.readthedocs.io/en/stable/guide/cdr-1-intro.html#near-clifford-simulator).
Currently, it looks like:
To use CDR at scale, an efficient near-Clifford circuit simulator must be specified. In this example, the circuit is small enough to use any classical simulator, and we use the same density matrix simulator as above but without noise.


The planned new version would look like:
To use CDR at scale, an efficient near-Clifford circuit simulator must be specified. Two examples of efficient near-Clifford circuit simulators are [Qrack with the stabilizer hybrid (Clifford+Rz)](https://github.com/vm6502q/pyqrack-jupyter/blob/main/Clifford_RZ.ipynb)  and [IBM's extended stabilizer simulator](https://qiskit.github.io/qiskit-aer/tutorials/6_extended_stabilizer_tutorial.html).

In this example, the circuit is small enough to use any classical simulator, and we use the same density matrix simulator as above but without noise.

**Comment by bdg221** [comment]
A new issue should be created for creating a tutorial which uses CDR with Qrack as the near-Clifford simulator.
