### ISSUE TITLE
Add function to get available QEM techniques

### ISSUE THREAD

**Issue by jordandsullivan** [unitaryfund/mitiq#2244]
## Issue Description

Currently there does not appear to be a way to easily retrieve all the possible QEM techniques which are available in Mitiq. 

## Proposed Solution

Two potential solutions come to mind:
1. Add this information in the [`mitiq.about()` ](https://github.com/unitaryfund/mitiq/blob/master/mitiq/_about.py) method. This is where information like current versions of various integrations are listed (e.g. amazon braket, cirq)

2. [My preferred solution] Create a new function in [mitiq/utils](https://github.com/unitaryfund/mitiq/blob/master/mitiq/utils.py) and add it to the [mitiq/__init__.py](https://github.com/unitaryfund/mitiq/blob/master/mitiq/__init__.py) called something like `mitiq.qem_methods()`. 

## Additional References

NA

**Comment by cosenal** [comment]
Out of curiosity, what would be a programmatic use case of this function? In other words, why isn't a wiki/documentation enough?

**Comment by nathanshammah** [comment]
@jordandsullivan I like your proposal, and the about is more for grep/OS informations. @cosenal as a Mitiq user for me it would come handy also to remind myself of module naming. Currently the wiki is a more static location mostly for roadmapping, or for researchers to understand areas of planned development; I see this as a useful tool for a lazy coder (like me). @jordandsullivan do you want to assign yourself to this issue? I'd say go for it!
