### ISSUE TITLE
Clarify contribution guide for integration tests 

### ISSUE THREAD

**Issue by jordandsullivan** [unitaryfund/mitiq#2247]
## Issue Description

The guidance on the [docs contribution guide](https://mitiq.readthedocs.io/en/stable/contributing.html#adding-tests) states 

> Mitiq uses a nested structure for packaging tests in directories named tests at the same level of each module. The only exception to this is that any tests requiring a QVM should be placed in the mitiq_pyquil/tests folder.

This makes sense for unit tests, but does not make it clear (at least to me) where _integration_ tests should go. 

## Proposed Solution

We could suggest they go on the top level `mitiq/tests` or create a new directory, e.g. `mitiq/tests/integration`

## Additional References

[This guide](https://briankolowitz.github.io/data-focused-python/lectures/Topic%2004%20-%20Writing%20Testable%20Code/06%20-%20Writing%20Integration%20Tests.html#:~:text=These%20types%20of%20integration%20tests%20will%20depend%20on%20different%20test,that%20it%20contains%20test%20data.) recommends the following structure:
<img width="260" alt="Screenshot 2024-03-25 at 3 51 00 PM" src="https://github.com/unitaryfund/mitiq/assets/15827191/8a843ed9-9938-4239-b6bd-3f400281f220">
which is different from our current nested structure -- i.e. `unit` in the above example doesn't exist for us. However, I think we could safely create a `mitiq/tests/integration` directory without too much trouble.

**Comment by cosenal** [comment]
Currently, for each module there is a `tests` folder. Let alone integration tests, first we would need to invert the current structure and consolidate all tests under a single root `tests` folder, with a sub-folder for each module.

**Comment by jordandsullivan** [comment]
To perfectly match the example test structure above, you're correct, but
I'm proposing something intermediary, where we just put integration tests
at the top level and leave nested tests as they are for now.

Best,
Jordan Sullivan

**Comment by natestemen** [comment]
I'm struggling to see what the difference between unit and integration tests should really look like for Mitiq. Maybe naively, I would consider [`test_execute_with_zne_transpiled_qiskit_circuit`](https://github.com/unitaryfund/mitiq/blob/e76ef0898b964c928b9a3bd8dddf698e51a7f7aa/mitiq/zne/tests/test_zne.py#L525) to be an integration test. Do you agree? Should our integration tests be "bigger" in some sense?

If these are not integration tests, then we should consider what integration tests we want to add. Where they go, I'm not sure. Top level would make sense if they aren't specific to a module.

If the above test (and others) does qualify as in integration test, wonderful! My next question would be what would be the benefit of separating these tests out into distinct folders? There totally might be, I just haven't (knowingly) ran into a pain point yet.

Lastly, it's worth noting that our documentation/examples are essentially a collection of integration tests. Right?

**Comment by jordandsullivan** [comment]
> I'm struggling to see what the difference between unit and integration tests should really look like for Mitiq. Maybe naively, I would consider [`test_execute_with_zne_transpiled_qiskit_circuit`](https://github.com/unitaryfund/mitiq/blob/e76ef0898b964c928b9a3bd8dddf698e51a7f7aa/mitiq/zne/tests/test_zne.py#L525) to be an integration test. Do you agree? 

Yes I do agree that's an integration test. 

My definitions would be as follows:
- unit test: one that doesn't call any mitiq modules outside of the one it's testing. It may use external packages and mock inputs to test functionality. 
-- An example of this would be all the tests within https://github.com/unitaryfund/mitiq/blob/main/mitiq/zne/inference.py. 
-- I would say it would be difficult (and probably not all that useful) to create unit tests for something like [calibration](https://github.com/unitaryfund/mitiq/blob/main/mitiq/calibration/tests/test_calibration.py) however.

- integration test: one which tests the way different modules within mitiq work together, or its integrations with frontends and backends. Most of the tests within mitiq currently fall into this category in my view.

As we modularize our QEM techniques (#2253), my thinking is that tests may more naturally break down into unit and integration, and if indeed it seemed useful, we could keep them nested, i.e.
`mitiq/zne/tests/unit`
and 
`mitiq.zne/tests/integration`

> Lastly, it's worth noting that our documentation/examples are essentially a collection of integration tests. Right?

This is also true and very nice!

**Comment by jordandsullivan** [comment]
I think this isn't a major issue, so I'm going to close it.
