### ISSUE TITLE
rename master branch to main

### ISSUE THREAD

**Issue by jordandsullivan** [unitaryfund/mitiq#2259]
To be more in line with default naming for primary branches in the industry: https://github.com/github/renaming

I think since github will redirect master links to main (according to https://github.com/github/renaming?tab=readme-ov-file#whats-already-changed), the best thing to do is
1. Change the name of `master` to `main` via this GUI: 
![image](https://github.com/unitaryfund/mitiq/assets/15827191/611a078d-743a-40af-94a3-319e6ad1fdcc)
Changing the name may still break CI/CD, but it should be fixed after step 3.

2. Create a branch where we'll replace all the instances of "master" with "main" in our documentation, tutorials, and actions. 

3. Merge this branch into the newly named `main` branch

**Comment by jordandsullivan** [comment]
@natestemen @FarLab @purva-thakre Happy with this plan?

**Comment by natestemen** [comment]
LGTM! I'd just add that I think step 2 should come first, and then just before merging said PR, step 1 should be taken followed by 3. Then, there could be a step 4 as well. Something like

4. Send message in `#mitiq` channel describing how to change the name of the local `master` branch to `main`.

This should help prevent things from getting into a bad state by starting the process, and not finishing it in one fell swoop.

**Comment by jordandsullivan** [comment]
Okey doke. Sounds good. So the final plan would be

- [ ] 1. ~~Create a branch~~ (#2259) where we'll replace all the instances of "master" with "main" in our documentation, tutorials, and actions.

- [ ] 2. Change the name of `master` to `main` via the GitHub GUI and **add "changed name of master branch to main" to changelog**

- [ ] 3. Merge #2259 into the newly named `main` branch

- [ ] 4. Send message in #mitiq channel in Discord describing how to change the name of the local master branch to main.

**Comment by jordandsullivan** [comment]
Do we want to leave the existing changelog saying "master" since that's what it was called when past changes were made?

**Comment by natestemen** [comment]
I think it's probably best to use `main` going forward, but not to change it in the changelog for things prior to this change. I can see reasons for both decisions, but I lean this way. Do you have a preference?

**Comment by jordandsullivan** [comment]
Yeah I agree. Use master for old entries to the change log and main going
forward.

**Comment by jordandsullivan** [comment]
I'm not quite sure a good way to update the changelog to say  we've made this change since it isn't a release. Any suggestions for format?

**Comment by cosenal** [comment]
> I'm not quite sure a good way to update the changelog to say we've made this change since it isn't a release. Any suggestions for format?

Since you have a PR with that, isn't it going to show up automatically in the changelog?

**Comment by natestemen** [comment]
Yup this will get populated in the changelog when the next release is done!
