### ISSUE TITLE
Add benchmarks to user guide

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#2274]
## Issue Description
Benchmark quantum circuit are a crucial ingredient to test empirically the performance of quantum error mitigation techniques on real or simulated devices, and can be used as a diagnostic tool when designing new techniques or modifying existing ones. They are also used in the calibrator. While some benchmarks are quite well known, as randomized benchmarking or GHZ, others have been proposed more recently, like quantum volume circuits and mirror quantum circuits. 

Mitiq provides a comprehensive list of quantum circuits that can be used for benchmarks and they are listed in the [API doc](https://mitiq.readthedocs.io/en/latest/apidoc.html#benchmarks). However, their usage may require some additional background information. Moreover, they can be of use for several tutorials and to get started with Mitiq. 

## Proposed Solution
I propose to add a section in the documentation, in the user guide, under the core concepts, listing the various quantum circuits present in the benchmarks, with some details and code blocks, and useful references.  

## Additional References
- https://mitiq.readthedocs.io/en/latest/apidoc.html#benchmarks
- https://arxiv.org/abs/2210.07194

**Comment by nathanshammah** [comment]
@FarLab I'd be happy to work on this, it could even make it into this milestone.

**Comment by Shivansh20128** [comment]
HI @purva-thakre ! Can you assign this to me.
Thanks

**Comment by purva-thakre** [comment]
@Shivansh20128 Assigned! Feel free to ask questions if you run into any problems!

Our documentation also contains information about how to add files to the docs etc.: https://mitiq.readthedocs.io/en/latest/contributing_docs.html

**Comment by Shivansh20128** [comment]
Okay. Thank you!

**Comment by Shivansh20128** [comment]
I am going through the API Doc and reading about the various benchmark circuits. But I saw that the index on the right side shows "Tools for Error Mitigation" and a sub heading "Benchmarks", but then no sub headings for each of the benchmark circuits. Maybe this is something we can add as well.
