### ISSUE TITLE
Mitiq logo not displaying correctly on documentation

### ISSUE THREAD

**Issue by natestemen** [unitaryfund/mitiq#2278]
We have the Mitiq logo in the [`README.md`](https://github.com/unitaryfund/mitiq/blob/main/README.md) which is intended to display on the landing page of `mitiq.readthedocs.io`, however it has broken (see "Mitiq logo"):
<img width="600" alt="Screenshot 2024-04-10 at 9 39 38 AM" src="https://github.com/unitaryfund/mitiq/assets/12703123/6d37835c-27a5-4104-a809-b4000eb11639">

**Comment by purva-thakre** [comment]
The following are partially related to this issue. I was not sure if I should create a separate issue as these are very low-priority and could be skipped. 

- Earlier versions of the docs were accessible from the main landing page of https://mitiq.readthedocs.io/ but this option is no longer available on the main page after the theme was changed.

    For example, see the bottom right corner of https://mitiq.readthedocs.io/en/v0.34.0/index.html 
    ![image](https://github.com/unitaryfund/mitiq/assets/66048318/372ccd2a-f7fb-424a-a04b-cd2cd023eeaa)

    This option is available on other pages of the latest version of the docs (bottom left), just not on the main page.
    ![image](https://github.com/unitaryfund/mitiq/assets/66048318/bbe1bc44-abaf-4db2-89d3-ef56a0170d08)

- The navigation option `next` from the main landing page at the bottom takes a user to the `readme` again. I think we could remove `readme.md` from the first line of the [`toctree`](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-toctree) directive in `docs/source/index.md` 
https://github.com/unitaryfund/mitiq/blob/9e1cbb5a134983f247f1ed74cbe932a0156e76d1/docs/source/index.md?plain=1#L8

  OR the [`include` directive](https://stackoverflow.com/a/78067191) for `readme.md` at the bottom of `docs/source/index.md` .
https://github.com/unitaryfund/mitiq/blob/9e1cbb5a134983f247f1ed74cbe932a0156e76d1/docs/source/index.md?plain=1#L17-L18

- On some pages, the sidebar [on the left](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/layout.html#primary-sidebar-left) appears blank while on some the sidebar [on the right](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/layout.html#secondary-sidebar-right) appears blank. Some changes to [the default options](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/layout.html#overview-of-theme-layout) allowed by the theme could be made in `conf.py`.

| Left Sidebar: [2nd Readme](https://mitiq.readthedocs.io/en/latest/readme.html)      | Right Sidebar: [User's Guide](https://mitiq.readthedocs.io/en/latest/guide/guide.html) |
| ----------- | ----------- |
| ![image](https://github.com/unitaryfund/mitiq/assets/66048318/3441ad0c-bade-45d6-abec-638f7f12cb47)| ![image](https://github.com/unitaryfund/mitiq/assets/66048318/4d9e2383-99d5-43f4-9178-2551e1bc0a39)|

**Comment by natestemen** [comment]
@purva-thakre since the issues you raise are mostly unrelated, I think they deserve issues in their own right. Also if you feel as though the changes are small, always feel free to open a PR without an issue and we can move even faster!

---

As for this issue, I think the image source URL [here](https://github.com/unitaryfund/mitiq/blob/ccb9ff6d3cd417915d5ade9d62af751984e7fb28/README.md?plain=1#L1) will need to be replaced with https://raw.githubusercontent.com/unitaryfund/mitiq/main/docs/source/img/mitiq-logo.png
