### ISSUE TITLE
Reduce notifications from `Greetings` workflow

### ISSUE THREAD

**Issue by purva-thakre** [unitaryfund/mitiq#2286]
The `.github/workflows/greeting.yml` workflow sends too many notifications for someone who is not a first-time contributor.

![image](https://github.com/unitaryfund/mitiq/assets/66048318/c90e2465-06b5-43d2-a1ff-c7d5fc6fa74c)

**Option 1:** Make changes to the workflow to work around `actions/first-interaction@v1` as the issue related to notifications is known to the maintainers and has not yet been fixed. https://github.com/actions/first-interaction/issues/15

**Option 2:** Use an alternative to `actions/first-interaction@v1` from the Github Marketplace. 

- https://github.com/marketplace/actions/cron-first-interaction
- https://github.com/marketplace/actions/welcome-new-users
- https://github.com/marketplace/actions/first-issue-greeter

**Option 3:** Remove the workflow and rely on one of the maintainers to comment with the message.

**Comment by purva-thakre** [comment]
I vote for Option 3 since we are not inundated with an extremely large number of new contributors.

**Comment by cosenal** [comment]
Are those Github notifications? Where do I see them?

**Comment by purva-thakre** [comment]
@cosenal Whenever I create an issue, I get these notifications. Each notification in the screenshot is due to adding a label, assigning it to myself, or when editing the issue description. 

https://github.com/unitaryfund/mitiq/actions/workflows/greeting.yml

**Comment by purva-thakre** [comment]
The `Do Nothing` portion of the workflow does not work that well once it's clear that it's not a first issue or a first PR.

https://github.com/actions/first-interaction/blob/41ddf9c83167223a120a277ed96cc1ad9f56dc0b/src/main.ts#L33

You can see it in action at https://github.com/unitaryfund/mitiq/issues/2208#issuecomment-1962822788 when a person is new to the repo.

**Comment by natestemen** [comment]
@purva-thakre I think this is something to do with your personal GitHub notifications. I have never received any of these notifications. I wasn't able to find anything on first glance that would apply here, but I didn't do a thorough search through the notifications documentation: https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications.

I would think you can to turn off these notifications given others are not receiving them (or set up a filter in your email).

**Comment by purva-thakre** [comment]
I think these notifications were related to the watch repo option. Not perfect but I managed to stop these by ignoring all the repo activity. 

![image](https://github.com/unitaryfund/mitiq/assets/66048318/b08ca9c1-b208-4f11-8d20-2efb98e7b244)

I'll have to play around with the custom filter. I had all the boxes checked before.
