### ISSUE TITLE
Automatically cancel actions with a superceding commit 

### ISSUE THREAD

**Issue by jordandsullivan** [unitaryfund/mitiq#2304]
## Issue Description

Since our docs builds take quite some time...
<img width="330" alt="Screen Shot 2024-04-17 at 2 37 12 PM" src="https://github.com/unitaryfund/mitiq/assets/15827191/dd257dc3-9e47-48aa-b840-83a52b30fb3c">
...it would be useful if there were a way to automatically cancel running actions which were triggered by a previous commit (i.e. not the most recent). This way if in a PR, multiple commits are submitted in quick succession, this will not clog up the Github actions server for hours.

## Proposed Solution

We can choose from several solutions mentioned here: https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre

**Comment by natestemen** [comment]
Do you know if GitHub limits resources to builds based on the number of existing concurrent builds? I did a quick search on GitHub docs and couldn't find anything, but I do recall jobs taking longer to start when there are multiple concurrent builds.

**Comment by jordandsullivan** [comment]
Speaking from personal experience, there is a limit, as actions will start queuing after you submit more than a few. I can try to grab a screenshot next time this happens.

**Comment by jordandsullivan** [comment]
Seems like workaround can just be to cancel the job manually or build docs locally.
