### ISSUE TITLE
Create `make docs-quick` that reduces docs build time

### ISSUE THREAD

**Issue by purva-thakre** [unitaryfund/mitiq#2334]
https://github.com/unitaryfund/mitiq/blob/b7b6e1ea949ef7bc77cd49e6824803ec157b75c1/Makefile#L34-L41

The above commands let us build the documentation locally. But as the docs build takes forever, working on documentation layout-related issues becomes unmanageable. For example, #2331 and #2330 are relatively minor issues that could be fixed quickly if one could make minor changes and test the build locally for the layout (repetitively). 

I think it would be better to conditionally use the [`exclude_patterns`](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-exclude_patterns) directive to create a `make docs-quick` that lets us skip the portions of the documentation that take a loooong time. This is useful if we are testing for the docs layout and not the actual material in the documentation. 

https://stackoverflow.com/a/34075856

https://github.com/unitaryfund/mitiq/blob/b7b6e1ea949ef7bc77cd49e6824803ec157b75c1/docs/source/conf.py#L87-L90

**Comment by purva-thakre** [comment]
`sphinx-needs` could be used to check which modules are to be included in the `exclude_patterns` directive: https://sphinx-needs.readthedocs.io/en/latest/performance/debug.html#runtime-debugging

**Comment by purva-thakre** [comment]
Apparently, there is an option to not execute the notebooks according to Alessandro's comment. 

https://discord.com/channels/764231928676089909/773957956659052605/1238537333964411001

This involves changing `cache` to `off` below:

https://github.com/unitaryfund/mitiq/blob/9a9033932c9fd583fdf562c217fd65319a01be0c/docs/source/conf.py#L128

https://myst-nb.readthedocs.io/en/v0.12.2/use/execute.html#triggering-notebook-execution

Closing this issue.

**Comment by cosenal** [comment]
I think `cache` is the right configuration here and one shouldn't need to switch it off. We can't trivially use caching in CI, but for local development it should work well. If for whatever reason, that's not the case for you, then we should investigate those scenarios.

@jordandsullivan you mentioned you find yourself often in the need to run `make docs-clean`, but at the same time not you don't want to run the notebooks. Can you elaborate on these scenarios?

**Comment by purva-thakre** [comment]
@cosenal If we make changes to the template, it's better to use `make docs-clean` because you can't see the changes.

**Comment by cosenal** [comment]
@purva-thakre can you elaborate even more, ideally with a concrete example? I have been making changes to the template, and `make docs` has been working just fine 🤷🏻‍♂️

**Comment by purva-thakre** [comment]
@cosenal Sure! I'll dig through my older PRs and add that example to this discussion later. 

Working on one such PR made me aware that `make docs-clean` has to be used if we are making changes to the layout, templates, etc. The changes would not show up in a local build if I used `make docs`. The older files had to be removed first.

**Comment by cosenal** [comment]
👍 Maybe we are talking about different templates that we are changing. Looking forward to those examples.
