### ISSUE TITLE
New technique: Probabilistic Error Amplification

### ISSUE THREAD

**Issue by Misty-W** [unitaryfund/mitiq#2343]
## Issue Description

Investigate Probabilisitic Error Amplification as a noise scaling technique to be applied in conjunction with Zero Noise Extrapolation. In this technique, error amplification (gate) sequences are applied probabilistically to scale the noise level of the computation. 

Reference: https://www.nature.com/articles/s41586-023-06096-3

## Proposed Solution

The scope of this issue is to investigate the technique and provide an outline for an RFC, link to document:
https://docs.google.com/document/d/1l-74EFdMA0CSFUpHjqCyQYb3ZKCmY77seB1_mOZo5Co/edit?usp=sharing

**Comment by nathanshammah** [comment]
Just adding here that the NEPEC formalism could be used to implement PEA. Basically expanding PEC representations to accommodate noise + use ZNE Factories for extrapolation. There is some [relevant code](https://github.com/unitaryfund/research/tree/main/nepec) in the research repository wrt to the [NEPEC paper](https://arxiv.org/abs/2108.02237).

**Comment by Misty-W** [comment]
Unlinked my previous notebook PR and linked RFC document which will contain code snippets from notebook.

**Comment by Misty-W** [comment]
fyi @nathanshammah we closed the RFC in 2024!
