### ISSUE TITLE
In Pauli Twirling: allow user to pass a `noise_gate` or similar to simulate noise in between the twirled gates and CNOT / CZ gates.

### ISSUE THREAD

**Issue by Misty-W** [unitaryfund/mitiq#2346]
## Problem

The Pauli Twirling module `mitiq.pt` is currently difficult to use on a simulated backend. This is because incoherent/coherent noise is usually modeled using additional layers of noise that twirling does not account for.

```py
>>> a, b = cirq.LineQubit.range(2)
>>> c = cirq.Circuit(cirq.H.on(a), cirq.CNOT.on(a, b))
>>> cn = c.with_noise(cirq.NoiseModel.from_noise_model_like(cirq.depolarize(p=0.01)))
>>> print(cn)
0: ───H───D(0.01)[cirq.VirtualTag()]───@───D(0.01)[cirq.VirtualTag()]───
                                       │
1: ───────D(0.01)[cirq.VirtualTag()]───X───D(0.01)[cirq.VirtualTag()]───

>>> print(mitiq.pt.pauli_twirl_circuit(cn, num_circuits=1)[0])
0: ───H───D(0.01)[cirq.VirtualTag()]───Y───@───X───D(0.01)[cirq.VirtualTag()]───
                                           │
1: ───────D(0.01)[cirq.VirtualTag()]───Y───X───Z───D(0.01)[cirq.VirtualTag()]───
```

Because the added twirling gates ($Y\otimes Y$ and $X\otimes Z$ in the case above) do not surround the depolarizing noise, this version of twirling does not actually tailor **coherent** noise into **incoherent** noise. In essence, this means `mitiq.pt` is useless on simulators, unless the user manually inserts noise _after_ twirling.

Because $\mathrm{CNOT}$ / $\mathrm{CZ}$ gates themselves contain noise on hardware, this does not effect using `mitiq.pt` on a QPU.

## Requested solution

1. Allow the user to pass something like a `noise_gate` to apply in between the twirled gates and the $\mathrm{CNOT}$ / $\mathrm{CZ}$ gates.

2. Clarify in the documentation that if this is used in a simulator, the user(-defined executor) has to insert a noisy version of the CZ and CNOT gates.

More background is contained in #2201

**Comment by ronitd2002** [comment]
Hello @cosenal I am Ronit Dutta, and I have working experience with google's cirq. I have been in programming in the same for my own research for 1 year. May I please be assigned this project?

**Comment by cosenal** [comment]
Hi @ronitd2002, this issue has a [UnitaryHack](https://unitaryhack.dev/projects/mitiq/) bounty attached to it. You are free to work on this issue and create a PR for it. Based on the rules of UnitaryHACK, you only get assigned to an issue once you have a PR that is close to complete the issue successfully.
