### ISSUE TITLE
Move docs version switcher to navigation bar

### ISSUE THREAD

**Issue by cosenal** [unitaryfund/mitiq#2386]
### Discussed in https://github.com/unitaryfund/mitiq/discussions/2383

<div type='discussions-op-text'>

<sup>Originally posted by **purva-thakre** May 23, 2024</sup>
https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/version-dropdown.html

RTD allows us to switch between earlier versions of mitiq's documentation. The ability to switch between earlier versions is not as easily accessible unless we scroll down to the bottom of each page and look at the bottom left corner. 
![image](https://github.com/unitaryfund/mitiq/assets/66048318/c305665f-4ab0-4e2a-b331-d6220137ba15)

This option is also not available on certain pages like https://mitiq.readthedocs.io/en/stable/

With the PyData theme, there is a convenient option of using a [version switcher](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/version-dropdown.html) in the header/navigation bar. 

![image](https://github.com/unitaryfund/mitiq/assets/66048318/abcfea93-cf37-4f86-9909-58954aedb8a0)

</div>

**Comment by purva-thakre** [comment]
Closing this as we don't need to worry about the placement of the different build versions that much. 

Newer version of RTD has put these in a conveniently accessible spot (bottom right). 

![image](https://github.com/user-attachments/assets/144d8953-d399-464e-8fd3-147e06e67c17)
