### ISSUE TITLE
API-doc has run-on sentences

### ISSUE THREAD

**Issue by purva-thakre** [unitaryfund/mitiq#2422]
As we rely on google-style docstrings, there is no convention to allow lists in the description of the [different sections](https://google.github.io/styleguide/pyguide.html#doc-function-args) of a docstring. [Portions of our API-doc](https://mitiq.readthedocs.io/en/stable/apidoc.html#module-mitiq.cdr.cdr) have run-on sentences because someone used a list in the section description which appears as badly formatted sentences publicly.

| Intended      | in API-doc |
| ----------- | ----------- |
|![image](https://github.com/unitaryfund/mitiq/assets/66048318/d8133c18-eb0d-40a9-ae48-c1909fc5b7e2)| ![image](https://github.com/unitaryfund/mitiq/assets/66048318/b81f11c7-d1d3-4465-b533-aa73fc37e9e5)|

**Comment by purva-thakre** [comment]
@natestemen Is [this](https://github.com/numpy/numpydoc/blob/1668dd9f0d36d21963410dd74d8a5c7f4e706595/doc/example.py#L69) what you were referring to?

**Comment by natestemen** [comment]
Not really. I was thinking we could take inspiration from how numpy documents `kwargs` objects, but I haven't been able to find what I was looking for. One thing I did find, however, was that for [`numpy.clip`](https://numpy.org/doc/stable/reference/generated/numpy.clip.html#numpy.clip) they redirect to a different page for info on what `kwargs` can look like. Not necessarily suggesting we do that, just worth noting.

**Comment by Kuzay3t** [comment]
I want to help, how can i assist?

**Comment by natestemen** [comment]
The goal here is to go through the docstrings and ensure `kwargs` variables are formatted properly. You can find an example where this is **not** the case in the issue description.

**Comment by cosenal** [comment]
@Shivansh20128 Thanks for testing this. Interesting that the newlines carry over in the rendered file, e.g., the one betwenn "...select the" and then "non-Clifford...".
This solution makes sense to me, let's hear from @purva-thakre as well.
We may also want a way to format this automatically.

**Comment by Shivansh20128** [comment]
So shall I make the changes I mentioned or wait for a method for automatic formatting?

**Comment by gluonhiggs** [comment]
I think natestemen has already tried to find how numpy handles this issue automatically. I have tried also, but couldn't find anything explicit. Maybe we can write a custom command in Makefile to do it.

**Comment by natestemen** [comment]
@Shivansh20128 I like what you've started so far! Let's just try to find all the cases like this for now and ensure they are correctly rendered. Since we've looked and there wasn't something that automatically formatted the docstrings easily, lets fix this and focus our efforts elsewhere.
