### ISSUE TITLE
update to latest Changelog version 

### ISSUE THREAD

**Issue by jordandsullivan** [unitaryfund/mitiq#2438]
## Issue Description

The released version of the docs, for v0.38.0 has the Changelog link commented out:
<img width="1282" alt="Screenshot 2024-07-03 at 8 57 19 AM" src="https://github.com/unitaryfund/mitiq/assets/15827191/be87f668-20f3-46bf-8775-6667a020421d">

while the latest version shows it:
<img width="1410" alt="Screenshot 2024-07-03 at 8 55 37 AM" src="https://github.com/unitaryfund/mitiq/assets/15827191/335e5108-21ef-42c8-8e73-0b84669fe4bc">

## How to Reproduce

1. ...
2. ...
3. ...

## Expected behavior

---

<details>
<summary>Environment Context</summary>

Use the `about()` function to summarize information on operating system, python version and dependencies.
```python
from mitiq import about
about()
```

Additional Python Environment Details (`pip freeze` or `conda list`):

```
Copy and paste the output of `pip freeze` or `conda list` here.
```

</details>

**Comment by cosenal** [comment]
One solution could be to have linkcheck ignore links with the prefix `https://github.com/unitaryfund/mitiq/compare/`
