### ISSUE TITLE
Create two-stage API for ZNE

### ISSUE THREAD

**Issue by natestemen** [unitaryfund/mitiq#2439]
As part of our goals to make QEM techniques more modular and composable, we'd like to use the fact that most techniques can be seen as first generating circuits, and then second combining the results from said circuits.

A first step in this direction will be allowing users to more easily access the intermediary circuits for each technique. This issue will track the implementation of this idea for ZNE.

Previous discussion: https://github.com/unitaryfund/mitiq/discussions/2394

**Comment by cosenal** [comment]
@natestemen Before jumping into a PR, please comment here with a small design of what it would like for ZNE specifically, so we can continue discussion #2394, but only in the scope of ZNE.

**Comment by natestemen** [comment]
### Suggested design

Add two new functions (up to naming) in the ZNE module (at the top level; i.e. `zne.XYZ`):

1. `scaled_circuits`
2. `combine_and_extrapolate`

I propose they have the following signatures.

```py
def scaled_circuits(
    circuit: QPROGRAM,
    scale_factors: list[float],
    scale_method: Callable[[QPROGRAM, float], QPROGRAM],
) -> list[QPROGRAM]:
    ...

def combine_results(
    scale_factors: list[float],
    results: list[float],
    extrapolation_method: Callable[[list[float]], float],
) -> float:
    ...
```

### Imagined workflow

```py
# user generates the circuits and inspects them (can even change them if desired;
# although this would mess with the results (but maybe that's what they want!))
zne_scaled_circuits = scaled_circuits(...)

# user executes circuits as desired, storing the results in a list
results = []
for circuit in zne_scaled_circuits:
    results.append(circuit.execute(...))

# user combines results from runs using desired extrapolation
zne_value = combine_results(..., results, ...)
```

### Considerations

I wish we had a better way to store results together with the QEM configuration that was used with them. In "normal" mitiq workflows we have full control over the protocol and hence can keep everything nice and clean. This suggestion moves a lot more control to the user (which IMO is needed as this stage of NISQ), but means that we have to rely on users building potentially complicated objects. If they use an executor this problem can be mitigated since the executor stores results and the circuits that were run (but not QEM config as far as I'm aware).

**Comment by cosenal** [comment]
Thanks for the suggested design overview. Some observations: 

1. How is this going to interplay with [Factories](https://mitiq.readthedocs.io/en/stable/guide/zne-3-options.html#extrapolation-methods-factory-objects)?
2. I understand why we want to expose the scaled circuits, but what's the benefit of decoupling execution and extrapolation? That is, can't we do executing inside your `combine_result` function?
3. In the proposed design we have x = scale_factors, and y = results, and we are leaving it to the user to use it in a cohesive way, whereas it would be safer to have some encapsulation of x and y in a data structure that contains both, e.g., [(x1, y1), (x2, y2), ...]. The function `scaled_circuits` should definitely return an object such as [(scaled_circuit1, scale_factor1), (scaled_circuit2, scale_factor2),...], we can't just rely on implicit order.
4. As I suggested at the last Mitiq Coding call, it would be mindful to see what a "dry run" function, which estimates cost of running circuits, would look like in pseudocode, so that we are more confident on the api of `scaled_circuits`.

**Comment by natestemen** [comment]
Thanks for the helpful questions Alessandro! I'm answering these questions after pairing this morning with @FarLab, so answers are guided by some of what we wrote/found.

> 1. How is this going to interplay with [Factories](https://mitiq.readthedocs.io/en/stable/guide/zne-3-options.html#extrapolation-methods-factory-objects)?

The design should allow users to easily use our existing factories. So the `extrapolation_method` argument in the `combine_results` function above should be able to take the factory itself, or the `factory.extrapolate` method.

> 2. ... can't we do executing inside your `combine_result` function?

That's a good question and partly depends on how we want to approach technique-composability (see answer below). Having the users method of execution completely separate from our code is a big departure from how Mitiq was designed to be a thin layer between user and backend, but experimenting in the opposite direction (having no involvement in execution) could be interesting.

> 3. ... it would be safer to have some encapsulation of x and y in a data structure that contains both, e.g., [(x1, y1), (x2, y2), ...]. The function `scaled_circuits` should definitely return an object such as [(scaled_circuit1, scale_factor1), (scaled_circuit2, scale_factor2),...], we can't just rely on implicit order.

I agree this is much safer. The one downside I see to making this results object more complex is that it makes it slightly harder for a user to combine techniques using this workflow. E.g. if a user wants to combine ZNE and DDD, they need to pull out the circuits to then call `ddd.intermediary_circuits`[^1]. We should do more thinking about how this workflow impacts composability.

> 4. ... a "dry run" function, which estimates cost of running circuits, would look like in pseudocode, so that we are more confident on the api of `scaled_circuits`.

Do you mean something like this?

```py
from mitiq import zne

circuit = ...
ZNE_config = ... # setting scale factors, noise scaling, extrapolation technique, etc (not necessarily in a single object, just for simple pseudocode

zne.cost_estimate(circuit, ZNE_config)

>>> Number of calls to executor: 7
Number of distinct circuits: 7
```


[^1]: Future thinking.

**Comment by natestemen** [comment]
@cosenal since I think you still wanted to take a look at this PR, feel free to give it a review and we can make further improvements from new issues.
