### ISSUE TITLE
Organize tutorials

### ISSUE THREAD

**Issue by purva-thakre** [unitaryfund/mitiq#2463]
During the mitiq retrospective, @bdg221 pointed out the docs examples are not well organized. I agree.

I think we could use [`sphinx-tags`](https://sphinx-tags.readthedocs.io/en/latest/) to create clickable tags for each technique and frontend.

**Comment by cosenal** [comment]
They could also be organized according to difficulty, from, say, «Basic» to «Advcanced».

**Comment by bdg221** [comment]
I think the tags are a great idea!

I imagine there are two types of users coming to the examples section. The first type has something in mind already and is looking for an existing implementation. The second type is browsing (either to learn more in general or to see the different options of techniques/frontends/backends.)

@purva-thakre The first user type is most likely looking for specific techniques and/or frontends.

@cosenal  The second user type, who is browsing, would appreciate the organization by difficulty.

Looking at [one of the examples](https://tradingstrategy.ai/docs/programming/strategy-examples/index.html#tags) which implements `sphinx-tags`, I like how the tags are used in the navigation menu on the left. 

We could use tags for techniques and frontends, then organize the results by difficulty. Some examples would appear in multiple places (ie. under ZNE and Qiskit), but it should make things easy for users.
