### ISSUE TITLE
Observable class missing methods in API-doc

### ISSUE THREAD

**Issue by natestemen** [unitaryfund/mitiq#2524]
Currently, the only method of `Observable` which is displaying in our API-doc is `matrix`. Not sure why this is, but the class has many other handy methods which should also be displayed!

**Links**

- [Live API-doc](https://mitiq.readthedocs.io/en/stable/apidoc.html#mitiq.observable.observable.Observable)
- [`Observable`](https://github.com/unitaryfund/mitiq/blob/411e234894eb6329783d032dc12c144d89b99f12/mitiq/observable/observable.py#L19) class definition
- [Observable section in API-doc](https://github.com/unitaryfund/mitiq/blob/411e234894eb6329783d032dc12c144d89b99f12/docs/source/apidoc.md?plain=1#L323-L326)

**Comment by natestemen** [comment]
So the reason the many other methods are not appearing in the API-doc is that they are not documented! To close this issue we should document the following methods.

1. `measure_in`
2. The arguments of `matrix` should be flushed out using the `Args: ...` pattern.
3. `expectation`
4. `partition`
5. `from_pauli_string_collections`

**Comment by bdg221** [comment]
@natestemen 
Looks like a duplicate of #2324

**Comment by natestemen** [comment]
Good catch. moved a comment over there, and will close this.
