### ISSUE TITLE
LRE error with qiskit circuit

### ISSUE THREAD

**Issue by purva-thakre** [unitaryfund/mitiq#2584]
When attempting to get the sample matrrix of a qiskit circuit, the process fails with `AttributeError: 'QuantumCircuit' object has no attribute 'are_all_measurements_terminal'`.  This error should not be raised as the circuit of interest does not contain any measurements.

The error points to the following line where the scale factor vectors are generated and used by the sample matrix function:

https://github.com/unitaryfund/mitiq/blob/be6a76ce940033ddd58538f3fe9e989b8e536850/mitiq/lre/inference/multivariate_richardson.py#L97-L99

The function to generate the scale factor vectors relies on 

https://github.com/unitaryfund/mitiq/blob/be6a76ce940033ddd58538f3fe9e989b8e536850/mitiq/lre/multivariate_scaling/layerwise_folding.py#L39

### Code

```py
ghz_circuit = generate_ghz_circuit(4, "qiskit")
circuit = ghz_circuit.compose(ghz_circuit.inverse())
print(circuit)

     ┌───┐                              ┌───┐
q_0: ┤ H ├──■────────────────────────■──┤ H ├
     └───┘┌─┴─┐                    ┌─┴─┐└───┘
q_1: ─────┤ X ├──■──────────────■──┤ X ├─────
          └───┘┌─┴─┐          ┌─┴─┐└───┘     
q_2: ──────────┤ X ├──■────■──┤ X ├──────────
               └───┘┌─┴─┐┌─┴─┐└───┘          
q_3: ───────────────┤ X ├┤ X ├───────────────
                    └───┘└───┘               


sample_matrix(circuit, 2, 2)
```

**Comment by purva-thakre** [comment]
To resolve this issue, we should add the corresponding unit tests in `mitiq/lre/tests/test_multivariate_richardson.py`. 

Compatibility of LRE with non-Cirq frontends was ensured in #2547 

This is definitely related to https://github.com/unitaryfund/mitiq/pull/2542#discussion_r1821942480

**Comment by natestemen** [comment]
> This is definitely related to https://github.com/unitaryfund/mitiq/pull/2542#discussion_r1821942480

Ahhh 🙈 sorry! Since I worked on this previously, would it be easiest if I take it?
