### ISSUE TITLE
Add a qiskit executor example for exact density matrix simulation

### ISSUE THREAD

**Issue by willzeng** [unitaryfund/mitiq#269]
This is similar to the other executor examples in the docs. It isn't clear if qiskit has direct support for this.

**Comment by nathanshammah** [comment]
This example does not close the issue, or does it? 
https://mitiq.readthedocs.io/en/stable/guide/guide-executors.html#qiskit-density-matrix-simulation-with-depolarizing-noise-and-sampling. By exact it is meant without noise?

**Comment by rmlarose** [comment]
Still open - it's the [todo](https://mitiq.readthedocs.io/en/stable/guide/guide-executors.html#qiskit-density-matrix-simulation-with-depolarizing-noise) above that example. "Exact" means without sampling.

**Comment by Aaron-Robertson** [comment]
I'd love to get involved and this seems like as good a place as any to start! Am I wrong in thinking this case is handled by shots=1 from the sampled executor? Then with a density matrix snapshot serving as more appropriate return?

I'm happy to submit the PR, unless there's a better suggestion for return. Thanks!
Sources: [[1](https://qiskit.org/documentation/stubs/qiskit.providers.aer.extensions.SnapshotDensityMatrix.html)][[2](https://github.com/Qiskit/qiskit-aer/issues/908)]

**Comment by rmlarose** [comment]
The density matrix snapshot indeed seems like the way to do this in Qiskit - I've never seen this before, thanks. I can't tell from the docs exactly what this is, but it's at least close. The goal of this issue has having the Qiskit analogue of [this Cirq execute function](https://mitiq.readthedocs.io/en/stable/guide/guide-executors.html#cirq-density-matrix-simulation-with-depolarizing-noise). 

Please feel free to open a PR!

**Comment by Aaron-Robertson** [comment]
Great, it did take some digging to find so I'm glad! The structure of the Qiskit snapshot seems likely to change, though.

PR submitted, and tagged for next release in the changelog (if I understood the release cycle correctly).
