### ISSUE TITLE
Add an example of a custom adaptive factory

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#270]
This was suggested by @karalekas in #248. 
I agree that it would be useful but requires some time to find a good example: it should be adaptive but at the same time it should also be very simple to fit in the docs.
Since this is perhaps less urgent than #248, I created this independent issue.

**Comment by andre-a-alves** [comment]
I'd like to take this one on as my first real issue if no one has done it, yet. It will probably take me a couple of weeks, but I think given this issue's age that is probably acceptable.

**Comment by rmlarose** [comment]
You got it @andre-a-alves, thanks!

**Comment by andre-a-alves** [comment]
Just to confirm: the intent behind this issue is an example of a simple implementation of a custom adaptive factory within the ZNE portion of the user guide, correct? Or is the intent a full example that belongs in Mitiq Examples?

**Comment by rmlarose** [comment]
> Just to confirm: the intent behind this issue is an example of a simple implementation of a custom adaptive factory within the ZNE portion of the user guide, correct? Or is the intent a full example that belongs in Mitiq Examples?

@andreamari what do you think?

**Comment by andre-a-alves** [comment]
We discussed this at a meeting, but I didn't post the conclusion here. Sorry about that.
The idea is a full example that will belong in Mitiq Examples. I'm happy to do it, and I will learn a lot from it. It will just take a bit longer as I enter the semester exam period but will get done this summer.
