### ISSUE TITLE
Make mitiq notation consistent with the ZNE theory paper

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#280]
In the [digital ZNE paper](https://arxiv.org/abs/2005.10921) we use the following names and notation:

- _Unitary folding_: generic name for appending inverse gates. This is already consistent with `mitiq` notation.
- _Gate folding_: unitary folding applied to gates. In the mitiq docs and paper draft this is sometimes called _local folding_. 
- _Circuit folding_: unitary folding applied to the circuit. In mitiq code, docs and paper, this is called _global folding_.
- \lambda: relative scale factor. In mitiq paper and docs, the symbol `c` is used, while \lambda is used for the absolute noise.

What about we make everything consistent with the notation of the ZNE paper? This would mainly correspond to minor changes to the docs and to the mitiq paper. At the level of code, the only function which would be renamed is `global_folding` --> `circuit_folding`. The current functions `fold_gate_from_something` are already consistent.

@rmlarose @nathanshammah

**Comment by willzeng** [comment]
I saw this a bit late after our paper submission. I'm supportive of the update @andreamari suggests
