### ISSUE TITLE
rename private repo mitiq-examples and create a new public mitiq-examples

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#300]
Issue Description
-----------------

Currently the _mitiq-examples_ repository is private and contains informal notebooks with internal tests and other non-reviewed code. 

Proposed Solution
-----------------
Rename _mitiq-examples_ and keep it private.
Create a new public _mitiq-examples_ , to be filled with a select choice of examples.

**Comment by nathanshammah** [comment]
+1.

**Comment by willzeng** [comment]
Examples are certainly good to have. Do they need to be in a separate repo? 

An advantage of adding these examples into the docs is that they are then continually tested with CI and so are easier to maintain.

**Comment by willzeng** [comment]
Spoke with @rmlarose and sounds like there's consensus on keeping things in one repo for now. We can re-open discussion if needed.
