### ISSUE TITLE
Remove init from test directories and make test file names unique

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#305]
No tests should ever be imported and so test directories shouldn't have init files.

However removing init files causes test collection to fail because (I think) text files don't unique names. For example, there is `test_conversions.py` for both `mitiq_qiskit` and `mitiq_pyquil`. See below.

Proposed fix is to get rid of all init files from test directories and make test filenames unique, e.g. `test_pyquil_conversions.py` and `test_qiskit_conversion.py`.

```
==================================== ERRORS ====================================
________ ERROR collecting mitiq/mitiq_qiskit/tests/test_conversions.py _________
import file mismatch:
imported module 'test_conversions' has this __file__ attribute:
  /home/runner/work/mitiq/mitiq/mitiq/mitiq_pyquil/tests/test_conversions.py
which is not the same as the test file we want to collect:
  /home/runner/work/mitiq/mitiq/mitiq/mitiq_qiskit/tests/test_conversions.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
```

**Comment by andreamari** [comment]
+1
