### ISSUE TITLE
Add qutip integration example or API

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#307]
Issue Description
-----------------
Since QuTiP's `qutip.QubitCircuit` class is now connected to OpenQASM's standard import and export format ([PR 1318](https://github.com/qutip/qutip/pull/1318) and [1291](https://github.com/qutip/qutip/pull/1291) that will be included in QuTiP's 4.5.3+ version release), it may be nice to add some integration with it on mitiq's side. 

Proposed Solution
------------------
1. At very simple level, an executor's example could be added to the documentation
2. At more complex level, an API function could be added to simplify integration between the libraries, e.g. in a `mitiq_qutip` module
3. Notwithstanding whether it would require adding code to the code base, it may be nice to explore qutip's noise simulation features against zero noise extrapolation:
   - different noise mechanisms
   - the possibility to include continuous-time evolution of a quantum state as it evolves in a quantum circuit as well as pulse-level control. 

Additional References
---------------------
- GSoC 2020 blog by Sidhant, https://sarsid.wordpress.com/tag/gsoc2020/
- QASM notebook https://github.com/qutip/qutip-notebooks/pull/111

**Comment by Aaron-Robertson** [comment]
@nathanshammah Is this issue still under discussion? I'm still reading through some of the [QuTiP QIP docs](http://qutip.org/docs/latest/guide/guide-qip.html) but it looks like I could follow the `mitiq_qiskit/` example and start on a `mitiq_qutip/` folder, testing, and docs here.

**Comment by nathanshammah** [comment]
Hi @Aaron-Robertson, thanks it is. I do have some code already on a private repository. I think this may require some discussion first.
