### ISSUE TITLE
Create circuit conversion from allowed frontends (Qiskit for now) to mitiq representation (Cirq for now)

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#31]
For the purpose of unitary folding (which inputs Cirq circuits). In the future, we should allow for many front-end circuit types, including

- [ ] Qiskit
- [ ] pyQuil

and others. For the pre-alpha, release, we will focus on Qiskit QuantumCircuit's as the primary allowed front-end and Cirq Circuits as the underlying representation used to fold gates.

**Comment by willzeng** [comment]
Since Cirq is the underlying representation we should also accept cirq front ends and back ends yes? @rmlarose I figure this is what you had in mind but would be good to make this workflow explicit as well.

**Comment by rmlarose** [comment]
Yeah definitely accept Cirq frontends, even I can convert a Cirq circuit to a Cirq circuit. Also support for Google backends is easy :)
