### ISSUE TITLE
Add information in readme and documentation on installations of pyquil, qiskit for non devs

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#312]
Right now, the readme and documentation simply refer to a development install for users interested in pyquil and qiskit. 

However, imagine that a non-dev user is interested (as a user, not as a contributor to mitiq) in using mitiq + pyquil or mitiq + qiskit, then he/she has no clear information on the version requirements for these libraries, i.e. from the `requirements.txt` 
```
# third-party integration
pyquil~=2.18.0
qiskit~=0.16.2
```
Such user would not be able to run the tests without these information. 

Proposed feature
-----------------
Add information about this in the readme and in the documentation, e.g., 

"""
#### Using mitiq with Qiskit

If you are willing to use mitiq to mitigate Qiskit circuits, make sure to have qiskit~=0.16.2 installed:
```
pip install qiskit~=0.16.2 mitiq
```

"""
Also, if we decide to do this, we could reference this back in the documentation's guide when such 3rd party executors are mentioned.

**Comment by willzeng** [comment]
+1
