### ISSUE TITLE
Batch circuit executions in BatchedFactories

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#317]
To speed up runs when running on, e.g., IBMQ, all scaled circuits should be generated and then sent as a single job to execute. As opposed to scaling a single circuit then single a single circuit as a job to execute.

**Comment by andreamari** [comment]
I think this is quite useful and it will be even more important for PEC.
If we agree to do it, we should decide between:
1. allowing executors to be both single-circuit or batched (maybe with some new keyword `batched=True/False`).
2. requiring executors to always be batched (always mapping array of circuits to array of expectation values). In the case in which batching is not applicable (e.g. adaptive factories) the executor can still be called with a batch size of 1. E.g. `expval = executor([circ])[0]`

**Comment by rmlarose** [comment]
I think there's two changes that need to be made here:

1. Allowing executors to input either (a) a single circuit or (b) a sequence of circuits.
2. Re-designing batched factories to do the batching.

For (1), I don't think it's easy to allow for either option. For example, `qiskit.execute` returns different output depending on whether a single circuit or a list of circuits is input. Thus the post-processing would have to be different in each case, so it may not be possible to have a single function that can do both options.

For (2), I have an idea how to do this. It's a non-trivial change, but not a breaking change I don't think. A sketch of my idea is as follows:

1. Rename `Factory` -> `AdaptiveFactory` and only inherit adaptive factories from this.
2. Redefine `BatchedFactory` such that:
    - It doesn't inherit from `AdaptiveFactory` (formerly `Factory`). 
    - It pre-computes all folded circuits.
    - It batch submits all folded circuits.

The `BatchedFactory` should be usable with both types of executors -- i.e., executors that input a single circuit and executors that input a list of circuits. The `AdaptiveFactory` should only be usable with executors that input a single circuit.

What do people think? Discussion + other ideas welcome.

**Comment by andreamari** [comment]
+1. I like it! 

With the suggested setting, we could also consider the possibility of requiring executors to always be batched. I.e.:
```def executor(circuits: List[QPROGRAM]) -> List[float]:``` independently of the extrapolation method.
This can reduce confusion and the user can test adaptive or non-adaptive factories with the same executor. Adaptive methods would just use the executor with a batch size equal to 1.

If instead you we prefer to support both batched and non-batched executors, then I would make also `AdaptiveFactory` compatible with both.

**Comment by rmlarose** [comment]
Thanks @andreamari. I will start on re-defining `BatchedFactory`.

To summarize the other point and get more feedback, there are two options:

1. Redefine the signature of **every** executor to be

```python
def executor(circuits: List[QPROGRAM]) -> List[float]:
```

2. Allow for both executor types

```python
def executor(circuit: QPROGRAM) -> float:

def batched_executor(circuits: List[QPROGRAM]) -> List[float]:
```

Both have pros and cons. Thoughts @willzeng @karalekas @nathanshammah?

**Comment by willzeng** [comment]
I lean towards #2. As batched is the more advanced feature, we won't want to make the simple executor signature awkward for a single program. Hypothesis is that advanced users would be happy to just call a different method.

**Comment by nathanshammah** [comment]
I'll switch this to @rmlarose, given #364.
