### ISSUE TITLE
Move qiskit_utils and pyquil_utils to benchmarks

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#320]
As far as I can tell, the contents of these files are all utilities for benchmarking. I don't think they would ever be used otherwise. Thoughts?

**Comment by rmlarose** [comment]
Also these files don't have unit tests (?) and pyquil_utils.py sets a global seed "for testing"...

**Comment by willzeng** [comment]
Nice catch. Some cleanup of these files would be good.

Some reasoning about their location structurally is that they are for distinctly testing the different front/backends for mitiq. Benchmarks is for testing mitiq in its native representation (Cirq). Having these are separate modules makes it easier to extend or drop support for different ones. For example if someone didn't want to install the whole pipeline to test every platform, then they could pick and choose.

**Comment by rmlarose** [comment]
Closed in favor of #589
