### ISSUE TITLE
Create support for IBMQ Backends

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#33]
We should have functionality to submit jobs to IBMQ for the pre-alpha release. The most basic functionality includes submitting a job to a designated backend, which we should focus on for now. 

The key obstacle I can see is handling API keys and registered accounts for IBMQ. I don't see a clear best way to do this yet, hopefully there is at least a good way.

In the future, we can build on the basic support here to batch jobs, target the backend with smallest queue, print status updates, etc.

**Comment by andreamari** [comment]
Do we need/want to directly send jobs to backends ?
The current structure of Mitiq assumes that the user creates a function to execute circuits which is passed as an argument (`executor`) to our error mitigation functions.
The initial idea of this approach was make Mitiq as backend-independent as possible, apart from  the necessary conversions between different circuit types.

**Comment by rmlarose** [comment]
That's right. This Issue should be updated to fix and streamline that functionality (i.e., using an "executor"). I will close this issue and create a new one with details.
