### ISSUE TITLE
Add executor example with TensorFlow Quantum

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#334]
Issue Description
-----------------

An example with TensorFlow Quantum could be added to the executors' part of the user guide in the documentation.

**Comment by willzeng** [comment]
I believe @k-m-schultz is starting on this issue.

**Comment by karalekas** [comment]
Assigning myself as I'm handling the PR review

**Comment by karalekas** [comment]
@nathanshammah to get this merged over the weekend
