### ISSUE TITLE
RFC for Identity insertion noise scaling

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#335]
Insert n identity gates in a circuit which scales certain errors by elapsing time. Suggested in recent discussions by alpha users.

**Comment by andreamari** [comment]
+1 
Sounds like a very reasonable scaling method and I think we should provide it. 
Possible problem: identity gates may be considered as virtual gates by some backends and in this case the method won't work.

**Comment by willzeng** [comment]
I'm interested in this method. Do we have a use case yet for where it would be better than unitary folding?

In my head unitary folding's advantage is that it duplicates exactly the gates that you were running and so if the noise is not uniform across gates than the unitary folding will still scale things appropriately.

**Comment by andreamari** [comment]
Adding identities could help to effectively simulate a slow execution of a circuit but I agree that, differently from unitary folding, this  would be insensitive to the noise model of specific gates. Taking into considering this fact, maybe it makes more sense to insert entire layers (moments) of identities, instead of appending identities to gates. An identity layer would corresponds to a physical time pause which could effectively scale the effective decoherence time of the qubits (not the gate noise).

**Comment by purva-thakre** [comment]
@rmlarose @willzeng  @andreamari  

How do you want the identity gates to be inserted ? If I use the method used for unitary folding i.e. U(U^* U)^n then 2 identities could form 1 moment i.e. n such moments are inserted into the circuit U(I I)^n. 

If I instead use U(I)^n then the formula for scale factor changes i.e. [this formula](https://github.com/unitaryfund/mitiq/blob/08edc5ec7dccf224c44e2afc3804dc140bbcb8af/mitiq/zne/scaling/folding.py#L288) calculating needed number of gates will change to `(ngates * (scale_factor - 1.0))`.

**Comment by andreamari** [comment]
@purva-thakre  I think your second proposal is better and the formula that you suggested should be correct.
However, the best way to confirm that everything works as expected is to add many tests :-)

**Comment by purva-thakre** [comment]
Working on this. Should be able to mark above linked PR as ready for review in the next 2 weeks.

**Comment by purva-thakre** [comment]
Reopening this because previous PR was incomplete and needed a better design. See @andreamari comment (from Discord)

> my suggestion is that since folding and id_insertions are actually quite different, it is probably easier to code id_insertions from scratch without necessarily following the existing code of unitary folding

![image](https://user-images.githubusercontent.com/66048318/147039164-18977f14-dcc4-4f5b-aca9-86d7b06aea24.png)

**Comment by purva-thakre** [comment]
no, don't close

**Comment by purva-thakre** [comment]
Link to the RFC : https://docs.google.com/document/d/1hbd9frjYiSy0WujA0iCccc-oMO4Q-kZc2G4b3lkJHdk/edit?usp=sharing

**Comment by andreamari** [comment]
Thanks @purva-thakre, the RFC looks very good!

**Comment by andreamari** [comment]
Closing this since the RFC has been accepted

**Comment by nathanshammah** [comment]
@purva-thakre we can move onto opening a list of detailed issued to implement the RFC.

**Comment by purva-thakre** [comment]
@nathanshammah The RFC does have issues at the end. I am close to finishing off the tests for the scaling function. Do you want me to make 1 issue for the documentation changes ?

**Comment by nathanshammah** [comment]
Yes, what about opening single issues on github?
What about adding one for the documentation like this one https://github.com/unitaryfund/mitiq/issues/1448 (it has sub issues that will be easier to assign and to avoid getting stuck). Btw I think the RFC is quite beautifully explaining the concept and we should try to port as much information as possible (and your diagrams) into the actual docs.
