### ISSUE TITLE
Simplify and partly automate the release process

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#341]
Issue Description
-----------------
- [x] First, let's check that the instructions in the docs are correct and consequential to the detail, cc double check with @karalekas (#388)
- [ ] Second, some parts of the process of making a new release could be simplified. Also with some automation. 

Proposed Solution
-----------------
- [x] With regards to copying the pdf file, #340 has simplified the task, also thanks now to the RTD versions and pdfs downloadable there. Another option could be to remove the folder `docs/pdf` with the `mitiq.pdf` file that needs to be copied there from `docs/buld/latex/`, and instead tweak the `.gitignore` so that it ignores all the `build/` folder but for the `build/latex/mitiq.pdf` file. This seems doable with the pattern + `!` [as prefix](https://stackoverflow.com/questions/2415873/exceptions-in-gitignore), i.e.  `!build/latex/mitiq.pdf`
- [ ] We could add a shortcut to the makefile with instructions to build the pdf, just like `make docs` from root is equivalent to `cd docs/ && make html && doctest`. 

Superseded by other issues
----------------------------
- @karalekas has mentioned automatic releases on testpypi for every commit merged to master. I would propose something midways, with a command to be triggered only when really requested by a mantainer, e.g., with a special label such as ``release`` added to a PR that triggers the action when merged (?). Maybe we can see if this is easy with Github Actions. 
- It would be nice if Github Actions or some other CI could be triggered by a new TestPyPI release, and install it on several environments.

**Comment by nathanshammah** [comment]
As first point, just checking with @karalekas that the instructions were correct and precise, as you made the release. In case they are, the first item in the issue is ticked.

**Comment by karalekas** [comment]
The instructions LGTM!

**Comment by karalekas** [comment]
Checking over the instructions, they need a bit of updating. I've opened a separate issue to track that work.

**Comment by karalekas** [comment]
With the two new issues that I just opened (#388, #391), this issue can be downscoped to just focus on automating the generation of PDF documentation.

**Comment by karalekas** [comment]
I think we can close this now

**Comment by karalekas** [comment]
This is the goal of this issue (@nathanshammah will complete for this sprint):
> We could add a shortcut to the makefile with instructions to build the pdf, just like make docs from root is equivalent to cd docs/ && make html && doctest.
