### ISSUE TITLE
Add the schedule of talks and event related to mitiq in the Wiki

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#346]
We are giving some talks about Mitiq as well as participating to workshop and conferences. It would be nice to add this information to the Wiki, just as it has been done for the Mitiq pre-alpha workshop. In addition to keeping track of things for the future, this could be useful for prospective attendees.

**Comment by zlatko-minev** [comment]
That would be helpful, can't find right now

**Comment by nathanshammah** [comment]
https://github.com/unitaryfund/mitiq/wiki/Mitiq-Talks-and-Events.

**Comment by zlatko-minev** [comment]
Nice, thanks
