### ISSUE TITLE
Qiskit conversions can change the number of classical registers

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#355]
This is, at the least, quite confusing, and it can lead to problems with Qiskit executors since the `counts` of a job result are formatted differently depending on how many classical registers are in the circuit. 

The screenshot below shows calling the executor on a circuit with one classical register. The output counts dict has no spaces in the bitstring keys. When execute with zne is called, conversions introduce two classical registers so the output counts dict has spaces in the bitstring keys.

![image](https://user-images.githubusercontent.com/32416820/92850362-58f2df80-f3ba-11ea-9a2c-87209879c46d.png)

**Comment by willzeng** [comment]
Am labeling this as a bug since it violates expected behavior that internal conversions wouldn't change the circuit

**Comment by pchung39** [comment]
Hey @rmlarose! I did a bit of investigation on this issue and I believe I identified the function `from_qasm()` from file "/mitiq_qiskit/conversions.py` was introducing this issue when it converts the qasm string to cirq.

For example, right before the qasm string is converted to a cirq circuit, it looks like this:
```
QASM:  OPENQASM 2.0;
include "qelib1.inc";
qreg q0[2];
creg c0[2];
h q0[0];
h q0[1];
measure q0[0] -> c0[0];
measure q0[1] -> c0[1];
```

and then right after the conversion to cirq  (using `circuit_from_qasm()`), we see that the classical registers is now doubled:
```
qreg q[2];
**creg m_c0_1[1];
creg m_c0_0[1];**


h q[0];
h q[1];
measure q[1] -> m_c0_1[0];
measure q[0] -> m_c0_0[0];
```

It looks like the conversion to cirq is splitting the classical circuit into unit registers. For example, if there were 3 classical registers, the conversion would break it up into 3 individual registers. The example above shows the split for 2 classical registers.

I looked into the cirq documentation for the conversion function here: [https://cirq.readthedocs.io/en/latest/docs/interop.html#Importing-cirq.Circuit-from-QASM-format] and found that they have a small note regarding this behavior

```
**Mapping classical registers to measurement keys**
For a classical register creg cbar[n]; the QASM importer will create measurement keys named cbar_0..cbar_<n-1>.
``
I wasn't able to find anything in the documentation to suggest that this behavior can be over-ridden natively. 
I'm currently mulling through alternative solutions. I'll reach out again once I have a viable solution!

Thanks Ryan

**Comment by rmlarose** [comment]
Thanks @pchung39 for the update and nice find about measurement keys. I indeed think relating classical registers in Qasm to measurement keys in Cirq is a viable path, though I haven't thought much about alternatives.

For instance, in your example circuit

```
QASM:  OPENQASM 2.0;
include "qelib1.inc";
qreg q0[2];
creg c0[2];
h q0[0];
h q0[1];
measure q0[0] -> c0[0];
measure q0[1] -> c0[1];
```

the Cirq circuit could be created like

```python
qubits = some qubits in Cirq, e.g. NamedQubits

cirq.Circuit(
  cirq.H.on_each(qubits),
  cirq.measure(qubits, key="c0")
)
```

Then in the conversion back to Qasm, the parser would recognized the two measurements as having identical keys "c0" and put them in the same classical register. Generally, name of classical register in Qiskit <-> name of measurement key in Cirq.

I also don't think this can be handled with a simple option and the parser/conversion code would have to be modified.

**Comment by willzeng** [comment]
Awesome! Great to see this close @rmlarose. Critical details like this help a lot with usability.
