### ISSUE TITLE
Consider adding an additional conversation channel

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#358]
Creating a channel beyond github for quick response on questions, troubleshooting and community building in general could be helpful. Possible options that come to mind:
- Slack 
  - Pros: widely used. Most people have slack already installed anyway.
  - Cons: not open-source, heavy.
- [Keybase](https://keybase.io/) 
  - Pros: Open-source.
  - Cons: not very stable?
- [Gitter](https://gitter.im/).
  - Pros: Integrated with github. 
  - Cons:
- Discord. 
  - Pros: 
  - Cons: 
- [Discourse](https://discourse.jupyter.org/). 
  - Note: Used by PennyLane (https://discuss.pennylane.ai/)
  - Pros: Being a forum and not a chat could avoid answering more times to similar questions.
  - Cons:
Pros: proved scalable as used by large projects, as Jupyter. Cons: may duplicate issues discussion?

Feel free to edit the list directly with items and pros and cons, just add EDIT By: here.

**Comment by rmlarose** [comment]
And the winner is... Discord!
