### ISSUE TITLE
Reproduce a result from the literature with Mitiq

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#365]
It would be nice to have an example taking Mitiq and applying it to a result in the research literature where zero-noise extrapolation, ZNE, is applied. It could also highlight differences between the unitary folding approach and what is there in the literature.  

This could be an example for the documentation, or a notebook (how to integrate notebooks in the repository  is something being discussed).

The [Kandala *et al.*](https://arxiv.org/abs/1805.04492) paper, with a simulation or real hardware, could be an idea.

**Comment by nathanshammah** [comment]
I think it is more feasible to bump this to the next milestone, as I am pretty full next week and haven't started yet.

**Comment by rmlarose** [comment]
Just added notebook to [mitiq-internal](https://github.com/unitaryfund/mitiq-internal/tree/master/lit/kandala) which reproduces Fig. 2(a) of the Kandala paper. As such I will close this issue.

 The real issue now should be to decide on / create an infrastructure for hosting such examples, as mitiq-internal is UF exclusive. I think notebooks are by far the preferred format, especially for community contributions, so we should think of how to do best do this.

**Comment by rmlarose** [comment]
Closed via https://github.com/unitaryfund/mitiq-internal/pull/15.

**Comment by nathanshammah** [comment]
Just wanted to mention that @elmandouh volunteered to look into this. Maybe he could add some features, such as running the experiment multiple times to obtain error bars?

**Comment by rmlarose** [comment]
I think that's a great idea @nathanshammah.

We'll have to figure out something for access. cf. #450.

**Comment by elmandouh** [comment]
I took a stab at reproducing fig 2(a) [here](https://github.com/elmandouh/error-mitigation-tutorial/blob/main/zne.ipynb). Next I will try to implement @nathanshammah's suggestion.
