### ISSUE TITLE
Make information on development install in readme and documentation more visible

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#367]
Currently the readme just mentions the PyPI installation.  Adding information on the development version installation may be helpful. Since the "installation" part of the documentation is just the one imported from the readme, this would be reflected also in the documentation. We could simply add a link to https://mitiq.readthedocs.io/en/stable/contributing.html#development-install.

**Comment by rmlarose** [comment]
Closing this as [Developer information](https://github.com/unitaryfund/mitiq#developer-information) links to [CONTRIBUTING.md](https://github.com/unitaryfund/mitiq/blob/master/CONTRIBUTING.md) which includes development installation instructions. 

@nathanshammah reopen if you think we should do more.
