### ISSUE TITLE
Update software version to current version; possibly track last commit in dev versions

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#368]
Currently, the VERSION.txt file has 0.1.0 as version. But this has been released, and we are now in the development version of the next one. (I think something happened in the history of how the release PRs [were committed](https://github.com/unitaryfund/mitiq/commits/master/VERSION.txt), maybe in the wrong order).

The first part of the issue is easy. The second part, is that, as a refinement, it may be nice to be able to discern between specific development version commits. For this we could use the hash of the latest merged commit.

**Comment by rmlarose** [comment]
I believe this is outdated as VERSION.txt is no longer 0.1.0.
