### ISSUE TITLE
Use cirq as internal representation

### ISSUE THREAD

**Issue by willzeng** [unitaryfund/mitiq#37]
In #31 and #32 Ryan suggests that for the alpha release we just use the cirq internal representation. I agree with this. Cirq already has built in import and export to QASM which means it is especially easy to support qiskit and cirq together. Cirq also has some open issues about export to Quil. 

To me this is enough of a case that cirq is (for the time being at least) preferred as an internal representation over pyquil. Thus I propose that we remove the pyquil internal representations and just use cirq. This reduces the maintenance burden on our code and will help us clean up the dependencies and structure. 

Do you agree @rmlarose @andreamari @nathanshammah ?

**Comment by andreamari** [comment]
Cirq seems to have more options for circuit manipulation. So I agree to use Cirq within Mitiq. 
If we do this, we can remove the PyQuil folding functions and their tests.

**Comment by rmlarose** [comment]
Agree.

**Comment by willzeng** [comment]
Got it. As we're agreed I'll take this issue and open up a PR to remove the pyquil stuff.
