### ISSUE TITLE
Manually solve for QPR decomposition given noisy gateset

### ISSUE THREAD

**Issue by karalekas** [unitaryfund/mitiq#374]
Following the trend of #370, we would like to be able to compute the quasi-probability distribution (QPR) of an "ideal gate" in a more general fashion, without assuming there exists some well-behaved/simple noise model to describe our QPU. In this case, we might be given some description of a "noisy implementable gateset" (e.g. as superoperators or process matrices). Using this description, we can solve the linear problem described in [Temme2017](https://arxiv.org/abs/1612.02058) to find the decomposition with minimum overhead (defined as 1-norm of the QPR coefficients).

**Comment by karalekas** [comment]
Punting on this for now, as it is not blocking for an initial end-to-end demonstration of PEC.

**Comment by nathanshammah** [comment]
I'm happy to look into this. I am coordinating with @andreamari.
