### ISSUE TITLE
Replace Qiskit utils with Qiskit executors from docs

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#379]
The code in [qiskit_utils.py](https://github.com/unitaryfund/mitiq/blob/master/mitiq/mitiq_qiskit/qiskit_utils.py) is stale, not used for anything but testing, and not general enough to be useful as a utility. In my opinion, the [Qiskit executors](https://github.com/unitaryfund/mitiq/blob/master/docs/source/guide/guide-executors.rst#qiskit-executors) in the docs would be much better to include as a utility.

**Comment by pchung39** [comment]
Hey @rmlarose , I can take a shot at this issue :)

**Comment by rmlarose** [comment]
Awesome thanks @pchung39!
