### ISSUE TITLE
PDF generation for docs is a bit janky

### ISSUE THREAD

**Issue by karalekas** [unitaryfund/mitiq#386]
Requires that the user skip errors with "s" and run twice to make sure the ToC is built correctly. Would be great to fix those two issues if possible.

**Comment by crazy4pi314** [comment]
I was just revisiting this, and I can't get the PDF docs to build at all in a clean ubuntu container. Will look into this and try to make it more robust.

**Comment by crazy4pi314** [comment]
I want to maybe leave this one for future events and focus more on CI related issues for 0.6. Bumping.
