### ISSUE TITLE
Add a PEC section to the documentation

### ISSUE THREAD

**Issue by karalekas** [unitaryfund/mitiq#393]
Depends on the PEC-related issues (#369, #370, #372, #374). Once those are done, we should add a new section to the docs describing the new module, as well as a demonstration of the new feature.

**Comment by karalekas** [comment]
Pushing this to next release

**Comment by crazy4pi314** [comment]
@rmlarose do you want to connect on this one to see how I can help?

**Comment by rmlarose** [comment]
Thanks @crazy4pi314, sounds good. My only hesitation is the PEC API is not likely to be stable for a bit, so I worry about constantly re-writing docs. Let's discuss at the Mitiq meeting tomorrow.

**Comment by nathanshammah** [comment]
@rmlarose: @andreamari and I agree on avoiding to add too many details that will change in the near future. @andreamari will add a very short example in the Getting Started section that will be helpful to understand Mitiq is not only ZNE. We can then add a more in-depth example based on @andreamari notebook in the examples section using the new features of the infrastructure made by @crazy4pi314.
