### ISSUE TITLE
Decide and implement a logo for Mitiq

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#394]
Issue Description
-----------------
Mitiq doesn't have a logo.

Proposed Solution:
-----------------

- [ ] Propose some alternative logos
- [ ] Get feedback and maybe get votes from other developers 
- [ ] Implement the logo in the Readme.md and in the docs.

**Comment by rmlarose** [comment]
I think @nathanshammah created some logo options a while ago.

**Comment by nathanshammah** [comment]
## Idea for a logo:
- Two probability curves of a displaced error mitigated value could somehow resemble an "m" for "mitiq", as calculated through zero-noise extrapolation (or probabilistic error cancellation). Some sketches / idea board are attached, as well as a . 

## Context
QuTiP's logo is a Schrödinger cat Wigner function, plotted with matplotlib. Qiskit is inspired by the Bloch sphere. Similarly, an idea could be to have a logo that is algorithmically designed. There could be a short `logo.py` file with a simple script that generates it from the error mitigation of a circuit, which would make it nerdier.
The inspiration is from ZNE plots with error bars / distributions
![error_mitigation](https://user-images.githubusercontent.com/14573436/97882789-4b0b6c00-1d24-11eb-8051-01265566f836.jpeg)
and this are some free-hand attempts, 
![Ideas-logo](https://user-images.githubusercontent.com/14573436/97882745-3e871380-1d24-11eb-98c8-ce3180f34ce7.jpg)
while here is an example with xkcd's matplotlib plugin, 
<img width="398" alt="Screen Shot 2020-11-02 at 16 02 47" src="https://user-images.githubusercontent.com/14573436/97883336-046a4180-1d25-11eb-93ef-b0f13cc7f85a.png">
made with [this notebook](https://gist.github.com/nathanshammah/78e3afd28ead563db6d293c9a6d6a00f).
The algorithm could be related to #401 and #403.

**Comment by nathanshammah** [comment]
Another simple idea (temporary, eventually): use UF's font and style. 
<img width="656" alt="Screen Shot 2020-11-03 at 9 23 32" src="https://user-images.githubusercontent.com/14573436/97962949-7b034f80-1db6-11eb-9242-27f72356a88f.png">

**Comment by andreamari** [comment]
I like both ideas.
Between the two, I am a bit more in favor of the second (Mitiq word) because of its simplicity.
If we decide to use the first (M symbol), I would completely remove the axis from the plot to make as simpler as possible.

**Comment by elmandouh** [comment]
Here are some suggestions based on the idea of noise.
<img width="765" alt="mitiq_noisy_logos" src="https://user-images.githubusercontent.com/73552047/99115636-bd9c0780-25c0-11eb-967c-cc59d9b33186.png">

**Comment by francespoblete** [comment]
![mitiq](https://user-images.githubusercontent.com/65167390/112882886-d61f4100-90cd-11eb-803a-d20b64ff8062.png)

Based on the color of the Unitary Fund's current logo and the idea that Mitiq works with noise mitigation, these are logo proposals I made for Mitiq. If you have any comments, suggestions, or any concept you'd like for the logo, feel free to write it out here, or pm me.

![mitiqborder](https://user-images.githubusercontent.com/65167390/112882889-d6b7d780-90cd-11eb-9b95-256f124bb821.png)

**Comment by nathanshammah** [comment]
Thanks @francespoblete. I personally Like the idea but think that the current proposals are a bit too hard to read.

**Comment by francespoblete** [comment]
@nathanshammah Thanks for the comment! I could revise it to make it more readable and submit the revision afterwards. :)

**Comment by francespoblete** [comment]
Hey, sorry it's been a while. I understand that the noise was too much so I minimised it. Please see below revisions.

![revision 1](https://user-images.githubusercontent.com/65167390/113344579-8a6cd180-9331-11eb-95a4-fa7002faca8c.png)

![revison 2](https://user-images.githubusercontent.com/65167390/113344582-8b056800-9331-11eb-8b6c-ad2428b89ee4.png)

Aside from that, I also have new logo proposals. I am aware that in Physics, a cat is super famous. So I tried to integrate it in the design. And here's what I came up with.

![revision 3](https://user-images.githubusercontent.com/65167390/113344706-ba1bd980-9331-11eb-98d6-63f074d50091.png)

![revision 4](https://user-images.githubusercontent.com/65167390/113344708-bab47000-9331-11eb-8401-a479df1cfe02.png)

Hope to hear from you guys soon! Keep safe! Cheers!

**Comment by Aaron-Robertson** [comment]
@francespoblete That schrodinger's cat is amazing 😻 !

**Comment by crazy4pi314** [comment]
This is something the above inspired for me: 
![MOSHED-2021-4-7-9-0-44](https://user-images.githubusercontent.com/6486256/114210636-c21ce000-9914-11eb-8046-764ee95780fe.gif)

**Comment by grmlarose** [comment]
Decided at Mitiq meeting to add some noise to the Schrodinger cat logo and follow up. Thanks for the multiple designs!! 

Perhaps a poll to decide the final logo? (on discord.unitary.fund)

**Comment by francespoblete** [comment]
Hi all! As per the discussion during the meeting, I have revised the Schrodinger's cat logo to have some noise. I made emphasis to the noise by adding shadows to it, which also resulted to emphasis to the regular ones ("noise reduced concept").

![revision 5](https://user-images.githubusercontent.com/65167390/114231609-f1fece80-997a-11eb-8dc7-59ec9c49099a.png)

![revision 6](https://user-images.githubusercontent.com/65167390/114231612-f32ffb80-997a-11eb-9f43-fcd0dc2f0354.png)

![revision 7](https://user-images.githubusercontent.com/65167390/114231613-f3c89200-997a-11eb-9d72-89ea8d2372f5.png)

**Comment by elmandouh** [comment]
Seems like there is interest in this again. I am personally a big fan of consistent style/branding. So following up on my earlier suggestions, my final design is a box logo with the same font as UF's with a different coloured background (I include a few colours) and noise. There are 2 versions of the noise. First, is where noise decreases from left to right and the second where noise is "constant" throughout. I also added two version, one with uppercase and one lowercase with lowercase m.

![Mitiq new versions](https://user-images.githubusercontent.com/73552047/114243399-7a20ac00-995a-11eb-8019-c6b2c09881b4.png)
![second mitiq version](https://user-images.githubusercontent.com/73552047/114243387-75f48e80-995a-11eb-95f5-1e8815cbf557.png)

**Comment by willzeng** [comment]
Thanks everyone! These are great!

I'm partial to the consistent branding of our font. The second proposal in the above stands out to me (with the black text and white background)

![image](https://user-images.githubusercontent.com/5214594/114449818-3a003a00-9ba3-11eb-9bf9-31b0095a802e.png)

**Comment by francespoblete** [comment]
Hey all,

Based on your preference I made a new proposal following the design made above. I understand that you guys would like to integrate the unitary fund logo into the mitiq logo fully so I decided to create one that is almost exactly unitary fund. ☺️ Would love to hear from your comments and suggestions.

![revision8](https://user-images.githubusercontent.com/65167390/115779582-75c3ac80-a3b8-11eb-8e24-9aa1c23cd13e.png)

**Comment by crazy4pi314** [comment]
OMG I love it <3<3

**Comment by willzeng** [comment]
+1

**Comment by crazy4pi314** [comment]
@francespoblete I'll send you a ping on discord and let's chat about getting this in use! <3

**Comment by nathanshammah** [comment]
@francespoblete, thanks, this has been accepted as the new logo! 🎉

One question: would it be possible to just do one last test on the q, to replace completely the back font with the blue and red 3D effect? That's because the contours of the q may be hard to reproduce when the logo is small, or printed small.

**Comment by nathanshammah** [comment]
Another request is: highlighting the text in yellow instead of the full background, a bit like UF logo.

**Comment by francespoblete** [comment]
Hi Nathan,

Sure thing. I'll work on it and post it here.  Would you also need a
favicon?

**Comment by crazy4pi314** [comment]
I think a favicon would be great, thanks!

**Comment by francespoblete** [comment]
Hey all,
I'm not really sure what you meant by the first question but this is how I interpreted it. If this is different from what you were saying @nathanshammah, I still could change it. 😊

![g1022](https://user-images.githubusercontent.com/65167390/116050206-82295d00-a677-11eb-8561-46a047b9883e.png)

The yellow background like in the UF logo is implemented below.

![g1089](https://user-images.githubusercontent.com/65167390/116050211-82c1f380-a677-11eb-90a1-a26fc6e37308.png)

And here are a few favicon options. 

![g1232](https://user-images.githubusercontent.com/65167390/116050358-a9802a00-a677-11eb-8685-75bdebaef20d.png)

![g1264](https://user-images.githubusercontent.com/65167390/116051627-15af5d80-a679-11eb-8715-9baebe77844e.png)

**Comment by crazy4pi314** [comment]
This is done! Thanks so much again to @francespoblete for some amazing work 💖🎉

**Comment by willzeng** [comment]
Thanks @francespoblete! These came out wonderfully!
