### ISSUE TITLE
Depend only on the Qiskit packages we really need

### ISSUE THREAD

**Issue by karalekas** [unitaryfund/mitiq#396]
Issue Description
-----------------

Right now, we have `qiskit` in the `requirements.txt` file, as it is an optional third-party integration. This is a "meta" package that just installs other Qiskit libraries. For example, this is what is installed when you do `pip install qiskit` as of today:

```
qiskit                        0.16.2
qiskit-aer                    0.4.1
qiskit-aqua                   0.6.5
qiskit-ibmq-provider          0.5.0
qiskit-ignis                  0.2.0
qiskit-terra                  0.12.0
```

This is likely more than we need to run Mitiq, and additionally makes `import mitiq` quite slow. The goal of this issue is to only install the Qiskit packages we really need in `requirements.txt`.

**Comment by purva-thakre** [comment]
@karalekas If I want to work on this issue, how would I go about finding all the packages needed ? From `qiskit_utils.py` I see qiskit-aer is imported. Sorry if this is a really basic question. I am new to quantum open source contributions !

**Comment by karalekas** [comment]
@purva-thakre Welcome! Thanks for the interest :) in the `mitiq` source there are various imports from Qiskit libraries, as you noticed. In addition to Aer, the imports that seem to come from just `qiskit` (e.g. `QuantumCircuit`) are most likely from `qiskit-terra` (see https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/circuit/quantumcircuit.py for example). Thus, my hunch is that `qiskit-aer` and `qiskit-terra` are the only two that we depend on directly. You could test this by installing just those two libraries and verifying that the test suite still runs without error. Let me know if that makes sense!

**Comment by purva-thakre** [comment]
Ok. thanks !

**Comment by karalekas** [comment]
@purva-thakre Welcome to the `v0.4.0` milestone! :)

**Comment by purva-thakre** [comment]
In addition to `qiskit-aer` and `qiskit-terra`, `qiskit-ibmq-provider` is also needed. I'll check for more.

**Comment by rmlarose** [comment]
I imagine these are the only ones. If we rely on aqua something's gone terribly wrong :sweat_smile:

**Comment by purva-thakre** [comment]
Is it ok to make a pull request if I get errors due to issues already known when I run `make test-all` ? I think I am getting errors related to [this pull request](https://github.com/unitaryfund/mitiq/pull/463) even before making any changes.  

I have edited `requirements.txt` and `_about.py` with details of `qiskit-aer`, `qiskit-terra` and `qiskit-ibmq-provider`. In a new virtual environment, I get the previously mentioned errors after a new installation of `mitiq`. 

`make test-qiskit' does not have any issues.

**Comment by purva-thakre** [comment]
Putting this on old until a better version of pip's dependency resolver is released. Currently pip backtracks over all older versions of a package. See https://github.com/unitaryfund/mitiq/pull/485#discussion_r551542320

**Comment by purva-thakre** [comment]
@rmlarose I think you could re-open this issue. There's no checks being run for Python 3.6 in Github workflows. So, maybe the pip dependency resolver will not get stuck.

**Comment by rmlarose** [comment]
Great, thanks @purva-thakre! Setting up requirements takes about 2 minutes in CI now, so if we save time on this that would be great.
