### ISSUE TITLE
Link to *.md files in the docs are broken

### ISSUE THREAD

**Issue by crazy4pi314** [unitaryfund/mitiq#397]
Pre-Report Checklist
--------------------

- [x] I am running the latest version of mitiq
- [x] I checked to make sure that this bug has not already been reported

Issue Description
-----------------
On both of latest and stable releases of the docs page, the links to the [code of conduct](https://github.com/unitaryfund/mitiq/blob/master/CODE_OF_CONDUCT.md) and the links in contributing to docs section here are broken: https://mitiq.readthedocs.io/en/stable/contributing.html#updating-the-documentation.
Likely a regression of https://github.com/unitaryfund/mitiq/issues/211 

How to Reproduce
----------------

Visit https://mitiq.readthedocs.io/en/stable/contributing.html and try clicking on the code of conduct link at the bottom of the page.

**Comment by erkska** [comment]
I'm going to fix it.
