### ISSUE TITLE
Test validity of PEC decompositions using numerical representation

### ISSUE THREAD

**Issue by karalekas** [unitaryfund/mitiq#415]
As @andreamari comments [here](https://github.com/unitaryfund/mitiq/pull/371#pullrequestreview-518844279) we could make our PEC decomposition test suite even more robust by actually verifying that the decomposition is equal to the original operation, using for example `mitiq.pec.utils._operation_to_choi`.

**Comment by willzeng** [comment]
@andreamari @karalekas How critical is this for PEC? Should this be in the 0.5.0 milestone?

**Comment by andreamari** [comment]
This is not critical in the sense that it is not blocking any other issues.

However I think it is quite important since it allows to distinguish between probabilistic failures of PEC (bad results due to random fluctuations) with respect to intrinsic problems of representation dictionary.
