### ISSUE TITLE
List of papers citing/using Mitiq

### ISSUE THREAD

**Issue by crazy4pi314** [unitaryfund/mitiq#424]
Pre-Request Checklist
---------------------

- [x] I am running the latest version of mitiq
- [x] I checked to make sure that this feature has not already been requested

Issue Description
-----------------

It would be nice to be able to show off the groups/projects/papers using Mitiq and provide links to the projects.

Proposed Solution
-----------------

I think a section in the readme would be just fine.

**Comment by crazy4pi314** [comment]
Collecting some here: 
- https://arxiv.org/pdf/2009.08513.pdf

**Comment by nathanshammah** [comment]
Great idea. A section in the Readme could link to a section in the documentation. We could add a subsection in this page in the documentation, https://mitiq.readthedocs.io/en/stable/citing.html. From experience with QuTiP (http://qutip.org/users.html), it is possible that the list becomes out of sync with latest papers if one does not actively manages this. So, together with the list of papers, I'd add a link to some automated bibliography metrics tracker, such as on google scholar, e.g., https://scholar.google.com/scholar?cluster=12810395086731011605&hl=it&as_sdt=0,5 or "cited by" once that item is picked up by scholar.
