### ISSUE TITLE
Integrate with OpenQasm v.3.0

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#427]
A major version of [OpenQasm](https://github.com/Qiskit/openqasm) has been released, v. 3.0. Mitiq has been tested with OpenQasm v. 2.0. 

- It would be nice to test that all current features are compatible with v. 3.0 (likely so). 

- It would be nice to see if there are specific features that could be employed, such as w.r.t. timing (moments issues with qiskit-cirq conversions) or pulse-level control (e.g. stretching for analog ZNE), see https://qiskit.github.io/openqasm/.

**Comment by rmlarose** [comment]
It looks like there is a lot more interface between classical and quantum instructions. This will require updating `from_qasm` to handle these new features (custom defined gates, gate modifiers, classical instructions, etc.). This portion is best handled by updating Cirq conversions in my opinion.

The [lengthened instructions](https://qiskit.github.io/openqasm/#delays-and-other-lengthed-instructions) seem to be exactly pulse stretching.

**Comment by rmlarose** [comment]
Pinging this and requesting clarification. 

- Is OpenQasm 3.0 not backwards compatible? Do we **need** to make any changes to support this?
- Do we want to use new features present in OpenQasm 3.0 in Mitiq? Probably for pulse-stretching in zero-noise extrapolation?
- Other?
