### ISSUE TITLE
Make a new ZNE Factory based on the S-Runge interpolation algorithm.

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#442]
Issue Description
-----------------
Richardson extrapolation is equivalent to:
- Getting the polynomial which perfectly interpolates the measured points
- Evaluate the polynomial at the the origin.

This method is well known to be unstable when the number of measured points is large. This problem
can be related to the so-called Runge's phenomenon (https://en.wikipedia.org/wiki/Runge%27s_phenomenon)

Proposed Solution
-----------------

There are two ways of avoiding the Runge's phenomenon:

1. The first way is to choose a particular set of x values (the noise scale factors) known as [Chebyshev nodes](https://en.wikipedia.org/wiki/Chebyshev_nodes).

2. Alternatively, there exists an algorithm to interpolate a polynomial using _fake nodes_ which seems interesting [1]. This method has also a Python implementation https://github.com/pog87/FakeNodes. 

In Mitiq this could be achieved by adding a new Factory class (e.g. `RungeFactory`), which would be almost equal to `RichardsonFactory`, but where one of the two mentioned procedures is used to evaluate the zero-noise limit.

Additional References
---------------------
[1] S. De Marchi, F. Marchetti, E. Perracchione, D. Poggiali, Polynomial interpolation via mapped bases without resampling, Journal of Computational and Applied Mathematics, 364, 2020.

**Comment by elmandouh** [comment]
Hey @andreamari can I take this?

**Comment by andreamari** [comment]
Thanks @elmandouh for the quick contribution!
