### ISSUE TITLE
Raise a warning if number of samples in PEC is too large.

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#454]
Issue Description
-----------------
If the `precision` option is too small or if the one-norm of the circuit quasi-distribution is too large, the number of samples in `execute_with_pec` can become huge.

Proposed Solution
-----------------
Two options:

- Raise a warning if `num_samples` is beyond a certain threshold in such a way that the user is aware that the computation may be very long.

- Automatically cut `num_samples` to some default `max_samples` and raise a warning about this truncation.

**Comment by sid1993** [comment]
@andreamari 
Hello!!
Siddhartha here.
- `execute_with_pec` uses either user provided samples or generates them. In both the cases, computation may take very long.

- Exploring the first option, I performed tests for sample sizes 10^3, 10^4, 10^5, and 10^6 and found out that a warning for any sample size greater than 10^5 would be a good threshold.
![large_samples](https://user-images.githubusercontent.com/4842078/100553330-82cdeb00-32b3-11eb-8d20-5ef792c8dde6.png)

- I suggest to issue an UserWarning for sample sizes greater than 10^5 

- Truncating num_samples to max_samples needs various changes in test script functions like `test_execute_with_pec_with_different_samples` `test_precision_option_in_execute_with_pec`  and pec.py itself.
![error](https://user-images.githubusercontent.com/4842078/100553738-91b59d00-32b5-11eb-8d34-1b52b8e567e5.png)

- First option is a quick fix. In a later fix, we can add user preference on what actions (continue/truncate to max_samples) to take when sample size is very large.

Please let me know if I should proceed with this approach. Do assign me this issue if agreed.

**Comment by andreamari** [comment]
Thanks @sid1993  for the nice test for checking what is a reasonable threshold for the number of samples. 
Since current tests involve very small circuits, in the future we may decide to reduce that threshold. But for the moment I think `10 ** 5` is a reasonable value.

Your proposal (that you have already drafted in #459) LGTM.
