### ISSUE TITLE
Add continuous integration for notebooks

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#466]
Pull request #461 is introducing notebooks in the documentation using `nbsphinx`. 

- [`nbclean`](https://github.com/choldgraf/nbclean) and other tools could be used for enabling version control and continuous integration. 
- [ReviewNB](https://www.reviewnb.com/) can also be considered for review. 
- Some guidelines for notebook style are present in `examples/CONTRIBUTING.MD`, more could be added with regard to CI.

**Comment by crazy4pi314** [comment]
This should be resolved with #509 as you can use all of the regular Sphinx `doctest` plugin with notebooks either in `*.ipynb` or markdown format, and all notebooks specified are run from scratch to make sure that works. I will close this for now, please re-open if anyone feels this is not addressed.
