### ISSUE TITLE
Show notebooks in documentation from table of content and gallery

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#467]
From #461, notebooks are included in the documentation using simple hyperlinks from the `examples.ipynb` notebook and show as html pages. However, `nbsphinx` allows to use both [table of contents](https://nbsphinx.readthedocs.io/en/0.8.0/subdir/toctree.html), RST-like links and the use of thumbnail [galleries](https://nbsphinx.readthedocs.io/en/0.8.0/subdir/gallery.html) similarly to sphinx-gallery. Implementing both would be great. The catch with respect to TOC links, is that they should be linkable also if someone is opening the `examples.ipynb` notebook, and not only looking at `examples.html` from the documentation (on Read The Docs or built locally). Probably keeping both the hyperlinks and rst-like links could work fine.

**Comment by crazy4pi314** [comment]
My plan for this is to start using [JupyterBook](https://github.com/numpy/numpy/blob/1245f9da021d65789a3332f0e046ca30d518e9c8/doc/neps/nep-0000.rst#id2) as the front end for the docs build, which is basically just adding some more custom options to Sphinx. I started on the `crazy4pi314/jupyterbook` branch but will need more time to make sure there are no bugs.

**Comment by andreamari** [comment]
@nathanshammah, is this up-to-date?  (We now have sphinx gallery)

**Comment by crazy4pi314** [comment]
Ah sorry, I'll close again. Idk why I thought there was still things we wanted from this... New achievement though, forgetting this even though I actually implemented 😓
