### ISSUE TITLE
Highlight inserted part of circuit in noise scaling

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#473]
In noise scaling for zero noise extrapolation, it could be interesting to provide a method to visually highlight the part of circuit that is being inserted, for example showing the folded gates in a different color. @rmlarose mentioned that Cirq's testing has a feature that could be used for this (maybe it's [`highlight_text_differences`](https://quantumai.google/reference/python/cirq/testing/highlight_text_differences)).

**Comment by purva-thakre** [comment]
@nathanshammah To be clear, you are talking about this highlight showing up in output of `print(folded_circuit)` ?

**Comment by rmlarose** [comment]
Requesting clarification: Do you want a function which inputs the folded + original circuit and highlights gates?

```python
def highlight_diff(folded: QPROGRAM, original: QPROGRAM) -> None:
```

The Cirq function you linked shows █ where the diffs are, which probably wouldn't be helpful. To actually show highlights would require something else I think.
