### ISSUE TITLE
Add type check to CI

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#489]
We had a PR (#326) to add mypy to CI, but while this PR fixed mypy errors it never actually added a job to CI. Do we want to add this?

**Comment by rmlarose** [comment]
Agreed to add type check @ mitiq meeting.

**Comment by crazy4pi314** [comment]
Mitiq meeting notes: The scope here would be adding the CI check and then squashing any resulting issues one master.

**Comment by crazy4pi314** [comment]
So there are 466 errors to fix on master, this is gonna take a while...

**Comment by nathanshammah** [comment]
Just clarifying that a solution to this issue for UnitaryHACK may build upon #556 by @crazy4pi314.

**Comment by TripleR47** [comment]
Hi @crazy4pi314 @rmlarose @nathanshammah, I would like to work on this issue. Just for clarification, following the checklist in PR #556 should be enough or do I have to work on anything specific? Thanks!

**Comment by rmlarose** [comment]
That checklist for generic PRs. The steps to fix this issue are:

1. Run [`make check-types`](https://github.com/unitaryfund/mitiq/blob/master/Makefile#L18-L20) and fix all mypy errors.
2. [Uncomment the type check in CI](https://github.com/unitaryfund/mitiq/blob/master/.github/workflows/test.yml#L26-L28) to make sure we're tracking it in CI.

**Comment by TripleR47** [comment]
Okay, and does all the code need to be annotated? I went through the discussion in the PR there it was being discussed on ignoring type checking on test files (hence no annotation required for the test files).

**Comment by TripleR47** [comment]
> Okay, and does all the code need to be annotated? I went through the discussion in the PR there it was being discussed on ignoring type checking on test files (hence no annotation required for the test files).

@crazy4pi314 @rmlarose @nathanshammah

**Comment by crazy4pi314** [comment]
I think it all should be annotated, but I am not sure what the rest of the team thinks. Also gonna ping @andreamari

**Comment by rmlarose** [comment]
No need to annotate tests.

**Comment by andreamari** [comment]
I also think that excluding tests is fine. In this case, it may be necessary to find some trick for telling `mypy` to exclude tests unless this is automatic.

**Comment by TripleR47** [comment]
Okay, thanks for clearing the doubts.

**Comment by TripleR47** [comment]
I have updated some files with type annotations and updated the CI for type checking the non-test files. Should I create a PR or PR them all together after updating the rest of the files?

**Comment by rmlarose** [comment]
Thanks @TripleR47! It's fine to do separate PRs as you describe (would be good if you're running mypy on the files you added annotations for).

**Comment by TripleR47** [comment]
Yes, I'm running the mypy on the annotated files.

**Comment by TripleR47** [comment]
Yes, I'm running the mypy on the annotated files. And will it be okay if I push the future changes in the same PR? Thanks!

**Comment by TripleR47** [comment]
Hey @rmlarose, I created a PR, but it failed the validate and the unit test. I went through the error messages and the source code. But the source code looks fine. Any suggestions on how to work on it? Thanks!

**Comment by rmlarose** [comment]
Yep! I think just adding mypy to dev_requirements.txt will solve all (most) of the failures. [`make check-types` failed](https://github.com/unitaryfund/mitiq/pull/695/checks?check_run_id=2678781472) because mypy wasn't installed, and [some tests failed](https://github.com/unitaryfund/mitiq/pull/695/checks?check_run_id=2678781551) I think because of type checking also.

**Comment by TripleR47** [comment]
Okay, updating the dev_requirements.txt file.
