### ISSUE TITLE
Sort out how branches and tags are used for version releases and development

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#493]
Currently we are just storing tags for version releases. Another option is to have the corresponding branch.

**Comment by crazy4pi314** [comment]
We have discussed/debriefed on the issues in the patch release calls and I will try and summarize here:

**Current git flow/process:**
- Development work is done is various user branches and forks
- PRs for milestones are made to `master` 
- Releases get tagged on `master`
- CI is run on PRs and pushes to `master`

**Issues with this flow for patch release:**
We needed to take some commits already merged to master and separate them out for a patch release, but they were mixed in with a number of other unrelated commits past the last release tag. The main issue is that we on the same branch mix milestone development and release history tracking are functionally mixed here making it hard to have clean branches or states to make patch PRs to.

**Possible solutions:**
- Make a separate `releases` or `stable` branch that we make PRs from master or hotfix branches to that only contains complete releases.
- Make a new `development` branch and only do in-between milestone approvals to this branch and treat `master` as a stable or release branch. 

---
Other comments:
- We need to make more of this process automatic, no local building should be done for releases for reproducibility. I can take an  issue to spec it out later.

**Comment by willzeng** [comment]
I've used the separate dev branch with merge to master for releases before
and liked it a lot. I agree that mitiq is ready for that. Thanks for
raising Sarah!

**Comment by nathanshammah** [comment]
As discussed in the recent community call meeting, I'm in favor of working on the master, as it simplifies requirements for external contributions (no need to fork remote branches), and use something like a `releases` branch, with commits marking released versions to keep things separate.

**Comment by crazy4pi314** [comment]
I think then the actions I should take here are (likely for the next release cycle)
- [ ] Create new release branch and cherry pick all previous release to it
- [ ] Figure out how (if at all) to update/move tags and GH releases tied to them.
- [ ] Create new CI actions for merges from master to the new release branch that will auto build and push pypi and docs
- [ ] Rename master -> main
