### ISSUE TITLE
Questions about our requirements

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#508]
I have 3 questions related to our requirements:

1. Shall we remove `numpy` and `scipy`  given they are already required by `cirq` ?
2. Shall we remove `matplotlib`  from our dev. requirements for the same reason?
3. All dev. requirements are pinned. Is this a good thing? For example, shouldn't we test that Mitiq works properly with the last stable version of `qiskit` and `pyquil`?

**Comment by nathanshammah** [comment]
Hi Andrea, regarding 3., I think it is recommended to have the versions pinned, for reproducibility, and upgrade them when needed. We could use a tool like Dependabot to upgrade them, https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/.

Regading 1 and 2 I have no clear answer, but I guess that maybe keeping them is fine as we'd like to point out that we are explicitly calling out those packages for some features (scipy for fitting and matplotlib will be called by #464). It

**Comment by crazy4pi314** [comment]
I took a stab at adding a simple dependabot action that each day checks if there are updates from pip available for any of the requirements.

**Comment by andreamari** [comment]
Thanks everyone for your answers! Now all is clear to me.

**Comment by crazy4pi314** [comment]
I think we can close this now, feel free to re-open if there is something else to discuss!
