### ISSUE TITLE
Allow rb circuit function to be seeded

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#512]
It's useful to be able to reproduce the same circuit from [`rb_circuits`](https://github.com/unitaryfund/mitiq/blob/master/mitiq/benchmarks/randomized_benchmarking.py#L36).

**Comment by andreamari** [comment]
Our [`rb_circuits`](https://github.com/unitaryfund/mitiq/blob/master/mitiq/benchmarks/randomized_benchmarking.py#L36) function is based on Cirq functions which don't have a seed option.
This means that we should:
1. Manually rewrite all the Cirq functions which need to be seeded.
2. Upstream this request to Cirq.

**Comment by rmlarose** [comment]
Ah, thanks @andreamari, I thought these Cirq functions already had a seed argument and we just weren't using it. Still looks like an easy change (starting [here](https://github.com/quantumlib/Cirq/blob/master/cirq/experiments/qubit_characterizations.py#L592) and [here](https://github.com/quantumlib/Cirq/blob/master/cirq/experiments/qubit_characterizations.py#L604)) but is in the Cirq domain, so I will close this for now.
