### ISSUE TITLE
Allow setting qiskit.QuantumRegister when converting to Qiskit

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#516]
Issue Description
-----------------
In PEC we need to convert operations defined in Qiskit or PyQuil to Cirq and viceversa. 
However this can create ambiguities: for example operations acting on different Cirq qubits can be mapped to
the operations acting on the same qiskit qubit (and probably viceversa).

How to Reproduce
----------------

```python
qreg = cirq.LineQubit.range(2)
x_on_qubit_zero = cirq.Circuit(cirq.X(qreg[0]))
print("x_on_qubit_zero:")
print(x_on_qubit_zero)
qiskit_operation = mitiq.conversions.convert_from_mitiq(x_on_qubit_zero, "qiskit")
print("x_on_qubit_zero converted to qiskit:")
print(qiskit_operation)

x_on_qubit_one = cirq.Circuit(cirq.X(qreg[1]))
print("x_on_qubit_one\n", x_on_qubit_one)
qiskit_operation_one = mitiq.conversions.convert_from_mitiq(x_on_qubit_one, "qiskit")
print("x_on_qubit_one converted to qiskit:")
print(qiskit_operation)
```

OUTPUT:
```
x_on_qubit_zero:
0: ───X───
x_on_qubit_zero converted to qiskit:
        ┌───┐
q_0: |0>┤ X ├
        └───┘
x_on_qubit_one
 1: ───X───
x_on_qubit_one converted to qiskit:
        ┌───┐
q_0: |0>┤ X ├
        └───┘

```

In the example above two Cirq operations acting on different qubits are mapped to the same qiskit object.

How to Solve
----------------
I see two possible options but I am not sure:

1. Try to convert in some way qubit names or numbers directly in conversion functions. 
2. Keep conversion function unchanged but do some qubit re-mapping after converting operations in PEC.

**Comment by rmlarose** [comment]
This is good to note (see also [here](https://github.com/unitaryfund/mitiq/blob/master/mitiq/pec/sampling.py#L114-L116)) but I'm not convinced this is a bug or is blocking. The intended workflow is

1. Define circuit in Qiskit.
2. Represent all operations in Qiskit circuit.
3. Use PEC with circuit + representations.

Here you have a conversion between steps 1 and 2. (Why is this?) I don't imagine a user ever doing this.

I would replace this with

```
for op in qiskit_circuit:
  rep = pec.OperationRepresentation(qiskit circuit of op, basis expansion)
```

then use the `rep`s. Or am I missing the point?

**Comment by rmlarose** [comment]
If we wanted to modify conversions at all, I guess the easiest thing is add an optional argument to [`conversions.to_qiskit`](https://github.com/unitaryfund/mitiq/blob/master/mitiq/mitiq_qiskit/conversions.py#L58) which specifies the `qiskit.QuantumRegister` of the returned circuit. I think `qiskit.QuantumRegister`s are uniquely specified by their "name" attribute, so we would do something like

```python
def to_qiskit(circuit: cirq.Circuit, register_name: Optional[str] = None) -> QuantumCircuit:
    """Returns a Qiskit circuit equivalent to the input Mitiq circuit.

    Args:
        circuit: Mitiq circuit to convert to a Qiskit circuit.
        register_name: Name of the QuantumRegister in the circuit.

    Returns:
        Qiskit.QuantumCircuit object equivalent to the input Mitiq circuit.
    """
    circuit = QuantumCircuit.from_qasm_str(to_qasm(circuit))

    if register_name is not None:
        circuit.qregs[0].name = register_name

    return circuit
```

Then with your example: 

```python
qreg = cirq.LineQubit.range(2)
x_on_qubit_zero = cirq.Circuit(cirq.X(qreg[0]))

print(to_qiskit(x_on_qubit_zero))
#         ┌───┐
# q_0: |0>┤ X ├
#         └───┘

print(to_qiskit(x_on_qubit_zero, register_name="new_name"))
#                ┌───┐
# new_name_0: |0>┤ X ├
#                └───┘

**Comment by crazy4pi314** [comment]
Discussed in Community Call: Upstream this issue to Circ and Qiskit

**Comment by rmlarose** [comment]
> Discussed in Community Call: Upstream this issue to Circ and Qiskit

(Conversions are in Cirq, not Qiskit.) I think its best if we handle it here, then optionally open a PR to Cirq if its useful beyond this context.
