### ISSUE TITLE
Support raw executors which return raw counts instead of expectation values

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#517]
Issue Description
-----------------

This issue is motivated by problems emerged in #471 (Bayesian ZNE), #477 (Clifford-data regression). 
It seems that for many applications it would be nice if, instead of using executors which returns expectation values,
one could use executors which return raw counts (all the results of the measurement shots).

Proposed Solution
-----------------
I think the motivations are quite strong but this requires a strong change of the current architecture so, if we want to implement this, we need to do a careful plan.

Probably the first important decision to take is:

- Do we want to support two types of executors: both the usual executor and the new _raw executor_ ? 
- Do we want the _raw executor_ to become the new standard that will replace the existing type of executor?

Summarizing the ideas emerged so far, this is a list of possible solutions:

1. Let the usual `executor` optionally return, in addition to the expectation value (`float`),  the full dictionary of raw counts (measurement results in the Z basis for all qubits). Note that in this case Mitiq doesn't know how the expectation value can be computed from the counts but still could use the raw counts for other stuff (e.g. training a clifford-regression model etc.).

2. Let the usual `executor` return, in addition or instead of an expectation value (`float`), the single shot estimators of the expectation value (e.g. if we want to measure 0.6234234 * Z_1 * Z_2  we return the single-shot estimator of this observable for each measurement). This allows Mitiq to compute the expectation value from the single-shot results by just averaging them and allows Mitiq to easily estimate the variance, etc.. The downside is that we don't get the raw, nice and well-behaving integer counts. So we are loosing some information compared to point 1. 

3. Split the executor in two functions, `circuit_to_counts`  and `count_to_unbiased_estimator`. In this way we have **2 black boxes** which allow to get both kinds of raw data mentioned in 1. and 2.

4. I am sure there exist other solutions...  please add :-)

**Comment by rmlarose** [comment]
> This issue is motivated by problems emerged in #471 (Bayesian ZNE), #484 (Batched PEC), #477 (Clifford-data regression).

Can we clearly describe, here or elsewhere, why these issues need raw measurement results and how they use them? 

I still don't understand this (i) in general and (ii) in particular for #484 - here you don't need raw measurement results, you just need an executor with a `shots` argument so that we can increase the number of shots if needed.

**Comment by andreamari** [comment]
You are right, for #484 we don't need raw results I was confused. So I remove the reference.

**Comment by crazy4pi314** [comment]
We are working on a design doc for this feature [here](https://docs.google.com/document/d/1MENciPA3Gri__ZDCkA3PwdtfYV8BMk8pCXTLwnHX9qw/edit?usp=sharing)

**Comment by rmlarose** [comment]
Superseded by #623.
