### ISSUE TITLE
Readthedocs fails to build the docs

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#542]
Issue Description
-----------------

Readthedocs cannot build the docs (fails the build) after we merged this [commit](https://github.com/unitaryfund/mitiq/commit/49986668a2a9d4736d1ef066931b24fce479d644
) in which we have split the requirements into two files (`requirements.txt` and `dev_requirements.txt`).

Since readthedocs only looks inside a single file (`requirements.txt`), the build fails.

How to fix
-----------------
I am not sure what is the optimal solution. Two ideas:

- Add Cirq to `dev_requirements.txt` too. And set `dev_requirements.txt` in the readthedocs administration settings instead of `requirements.txt`. I tried this, but since Cirq is missing in `dev_requirements.txt` the API is not rendered (even if the build correctly passes). 
- Add a new readthedocs [configuration file](https://docs.readthedocs.io/en/stable/config-file/v2.html).

**Comment by nathanshammah** [comment]
Thanks @andreamari for finding it out and for the proposed solutions. Actually also @crazy4pi314 and I last week noticed that the RTD badge was failing, but did not understand why.

I vote for adding the new RTD configuration file and see if this fixes all. Even if it adds some redundancy. I can then open an issue about requirements, as currently the situation is pretty scattered, among:
- requirements
- dev_requirements
- docs/requirements
and I would find it useful as a dev to at least have a single installation command to do all, such as 
pip install [all].

**Comment by nathanshammah** [comment]
We can add the RTD config to a remote branch and tag the label at https://readthedocs.org/projects/mitiq/versions/.

**Comment by nathanshammah** [comment]
Thanks for adding the config file. The build now fails on RTD as it does not find the index.rst file. It is index.myst. My understanding is that RTD is not using the MyST parser and we should force it to, I am not sure how.
These threads seem relevant: 
- https://github.com/executablebooks/MyST-Parser/issues/139
- https://github.com/berkeley-dsep-infra/datahub/pull/1562 (which seems to just add myst_parser[sphinx] to the (dev_)requirements.txt)


Or we could rename just index to .rst, maybe.

**Comment by andreamari** [comment]
This is now working by adding the readthedocs config file, as proposed in this PR #543.
The problem was the default link to `docs/conf.py` which needed to be changed to `docs/source/conf.py`.

**Comment by crazy4pi314** [comment]
I am glad @andreamari and @nathanshammah got this figured out! I just wanted to add that I agree, having multiple `requrirements.txt` files is really not great, and in terms of python best practice is being phased out for a `pyproject.toml` as outlined in [PEP518](https://www.python.org/dev/peps/pep-0518/). This is a [great blog post](https://snarky.ca/what-the-heck-is-pyproject-toml/) on what/why the standards are changing, and there is a [great awesome list](https://github.com/carlosperate/awesome-pyproject) for tools that we can use with the new `pyproject` files. This will likely be one of the improvements slated for this next release :)
