### ISSUE TITLE
Pin to specific Qiskit, pyQuil, and Cirq versions in requirements

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#55]
Just ran into an issue where Qiskit circuit data is stored differently between v0.0.15 and v0.0.16, causing local tests to pass but the build to fail.

To avoid similar issues in the future, we should pin to specific versions now. @willzeng thoughts on what the versions should be? Latest?

Note that PR #42 pins Cirq to version 0.0.7.

**Comment by willzeng** [comment]
Agreed. Let's pin to the current latest, which may require some changes to get to v0.0.16 on qiskit as you point out.
