### ISSUE TITLE
Add gate set tomography for PEC

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#550]
PEC assumes knowledge of the noisy operations which a given computer can implement. This noisy basis is used to form representations of desired operations to implement.

Currently, we can form representations assuming a noise model (depolarizing noise). This issue is to add PEC so the assumption on a particular noise model isn't mandatory.

**Comment by willzeng** [comment]
@andreamari Perhaps we could close this by integrating with or just having a tutorial on the pygsti library that already has gate set tomography features?

Maybe the first MVP is to show how to use pygsti to get gate set tomography data and then how to import that into mitiq for PEC?

**Comment by willzeng** [comment]
@rmlarose am unassigning you as I think this is not being actively worked on? Correct me if so.

**Comment by rmlarose** [comment]
SGTM. Last I remember is waiting to get pygsti tutorials from their quantum software talk and turning those into an example for the docs.

**Comment by andreamari** [comment]
Superseded by #1273.
