### ISSUE TITLE
Revamp executor docs

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#552]
* Add executor examples to the library instead of the docs.
    - This is done for `mitiq_qiskit` in #463.
* Use these docs to instead describe different executor types: single/serial, batched, and raw.

**Comment by rmlarose** [comment]
It seems like a good idea to me because (i) these docs will soon be for explaining serial/batched & raw/not raw executors and (ii) it's more useful to people to have them in the codebase so they can be used, rather than copying and pasting from the docs.

I would propose they go into a new `mitiq_cirq.utils` instead of `utils.py` so that (i) there is parallelism between `mitiq_qiskit.utils` and `mitiq_pyquil.utils` and (ii) so that we don't further clutter `utils.py`. Thoughts on this point @andreamari @willzeng?

**Comment by andreamari** [comment]
I think having a `mitiq_cirq` folder similar to  `mitiq_qiskit` and `mitiq_pyquil` is a good idea. 
We could put there some Cirq executors but also any other functions which are supposed to be used only by Cirq users.

**Comment by willzeng** [comment]
Agreed!

**Comment by Aaron-Robertson** [comment]
@rmlarose I created #591 for the `mitiq_cirq/` changes so this issue can stay focused on updating docs for different executor types.

And @purva-thakre is that something you wanted to pick up? Otherwise I'm happy to take it on.

**Comment by purva-thakre** [comment]
@Aaron-Robertson I started to work on it....
