### ISSUE TITLE
Only need to transform qubit registers in Qiskit conversions, not classical registers

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#561]
Originally classical registers were transformed, but this didn't preserve the order of measurements (#551). The measurement order was fixed in #557 by removing all measurements then adding them back in the original order. It is therefore no longer needed to transform the classical registers (but this is still done). Rather, one can:

* Remove all measurements and classical registers, storing the classical registers.
* Do any operations on the Qiskit circuit, e.g. fold it.
* Add the classical registers back to the modified circuit, then add measurements in the correct order.

This simplifies the `_transform_registers` function in `mitiq_qiskit.conversions`.

**Comment by Aaron-Robertson** [comment]
@rmlarose I can take on this one next!
