### ISSUE TITLE
Create getting started and installation

### ISSUE THREAD

**Issue by willzeng** [unitaryfund/mitiq#57]
For the beta release we'll need a getting started that shows how to install the library and shows examples of how to use the library.

I propose that the examples show one how to:
- Mitigate a simple `cirq` quantum program on a `cirq` backend.
- Mitigate a simple `qiskit` quantum program on a `qiskit` backend.
- Mitigate a simple `cirq` quantum program on a `qiskit` backend.

Other suggestions for the getting started?

**Comment by willzeng** [comment]
@nathanshammah Since you are already doing #34 this is a sub-issue of that. Can you assign this to yourself as well?

**Comment by nathanshammah** [comment]
Sure. I am actually tinkering with jupyter notebooks that would do that. Nothing working smooth yet but it is helping with some ideas and questions I have. 

I also think that it is nice to add two or three other simple examples :
- Factories in mitiq
- A minimal zero-noise extrapolation (ZNE) example (with one given framework)
- One on the concept of folding

They have an overlap with the examples on the backends, but they may target a different need.

### Factories
From my limited understanding and my guess, it could be that "Factories" would be more general than for ZNE. Maybe I am wrong, or it was not settled, but `Factory` could be a staple that interfaces also with other techniques such as quasiprobability, etc. In any case at this point they look to me like QuTiP's `Qobj` and Pennylane's `QNode`. They are a quite flexible class whose objects are used to do things in `mitiq`. Having something about them is helpful. 

### ZNE and Folding
Some researchers may get to know `mitiq` even without a proper knowledge of the quantum circuit stacks, but really as a curiosity into QEM. These two examples would tackle the most widely known approach and an innovation.

**Comment by willzeng** [comment]
Good points. 

- The folding example could show how one can make their own modular function for scaling noise and then use it.
- The factory example could show how to make a custom factory and then use it.
