### ISSUE TITLE
Have Repo Tweet about releases and community contributions

### ISSUE THREAD

**Issue by crazy4pi314** [unitaryfund/mitiq#570]
It would be super cool to have an action like https://github.com/marketplace/actions/twitter-together hooked up to tweet when we publish releases as well as merge PRs into master for stuff :)

**Comment by StreakSharn** [comment]
I'd love to try this as a first issue! Could I take it?

**Comment by crazy4pi314** [comment]
Yeah! That would be great @StreakSharn 💖 We can talk about this if you want tomorrow at the Mitiq community call on [our discord](https://discord.unitary.fund) :)

**Comment by StreakSharn** [comment]
Sure! I don't have a working mic, sadly, but I'll make sure to be there. What time will it be?

**Comment by crazy4pi314** [comment]
Its 9am PST on #community-call voice channel 👍

**Comment by StreakSharn** [comment]
Does Mitiq have a twitter account?

**Comment by crazy4pi314** [comment]
Not separate from the Unitary Fund's acct. (@unitaryfund).
