### ISSUE TITLE
Suppress TestPyPI action from forks

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#581]
Pre-Report Checklist
--------------------

- [x] I am running the latest version of mitiq
- [x] I checked to make sure that this bug has not already been reported

Issue Description
-----------------

The TestPyPI-nightly action tries to update Mitiq also from forks, such as mine, `nathanshammah/mitiq`.  

How to Reproduce
----------------

See https://github.com/nathanshammah/mitiq/actions

Proposed solution
------------------

I see two possible options:
- Add these release actions to the gitignore, if possible for actions. 
- Insert a condition for the triggering event (runs "on") in the `.yml` files related to release actions (gh-release.yml, greeting.yml, pre-release.yml, publish-pypi.yml, publish-testpypi.yml), to run only from specific branches (unitaryfund/*).

**Comment by purva-thakre** [comment]
I don't know if this will help or not but it is possible to disable this workflow manually in your fork. If you go to Actions and then click on a specific workflow, on top right there's an option to `Disable the workflow`.
