### ISSUE TITLE
Add link to github from RTD

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#588]
It could be nice if from https://mitiq.readthedocs.io/ there was a more apparent link to the github repository. Currently one can reach it only from the readme page, by clicking on one of the badges at https://mitiq.readthedocs.io/en/stable/readme.html. 
I don't know if it is easy in this sphinx format, but something like "Fork us on Github" on the top right.

**Comment by purva-thakre** [comment]
@nathanshammah There are two possible different styles for this - [1](https://github.blog/2008-12-19-github-ribbons/), [2](https://tholman.com/github-corners/). Should I just pick one ?

**Comment by andre-a-alves** [comment]
What about just adding a link to the GitHub repo in the header links, as depicted below? 

![mitiq_rtd_github_link](https://user-images.githubusercontent.com/20098360/113398498-fe918e80-939e-11eb-877f-4dba6274b5f0.png)

It keeps the link obvious but subtle at the same time, and it's super easy to do. If you're happy with that solution, I can create a pull request.

**Comment by nathanshammah** [comment]
Thank you both, @purva-thakre and @andre-a-alves, and sorry for the slow reply, @purva-thakre. Personally I like option 2 by Purva, or Andre's proposal, and then a bit less option 1. Otherwise, one could just add a github logo or the word "Github" in the footer at the bottom of the page. Maybe this is something we could discuss at the Mitiq meeting (6pm CET, Fridays), if you can join, to get other folks input.

**Comment by purva-thakre** [comment]
Sorry, I joined the meeting very late. I have added this to next meeting's agenda and we could discuss this then.

**Comment by grmlarose** [comment]
Decided at Mitiq meeting to do badge on README and do this: https://tholman.com/github-corners/

**Comment by crazy4pi314** [comment]
As a future enhancement, you can check out the way JupyterBook does it here: https://jupyterbook.org/interactive/launchbuttons.html?highlight=github
![image](https://user-images.githubusercontent.com/6486256/114210426-a0bbf400-9914-11eb-80df-53deafcb0b7a.png)

**Comment by purva-thakre** [comment]
@andre-a-alves If you would like to work on both (README + ribbon), I am fine with it since I have enough issues to work on.

**Comment by andre-a-alves** [comment]
@purva-thakre Sounds good. Thank you. I'll get to it this week :-)
