### ISSUE TITLE
Move all benchmark circuits to mitiq.benchmarks

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#589]
Discussed at Mitiq meeting. All benchmark circuits should be defined in `mitiq.benchmarks` and have the option to output as a specific supported type (i.e., `QPROGRAM`). This is preferable to (re)defining them in `mitiq_qiskit`, `mitiq_pyquil`, etc.

**Comment by Aaron-Robertson** [comment]
@rmlarose Is this issue a clarification of #320? I think so, and either way I'm happy to take it on next unless you started on it.

**Comment by rmlarose** [comment]
> @rmlarose Is this issue a clarification of #320? I think so, but either way I'm happy to take it on next unless you started on it.

Yeah I closed that in favor of this one. I haven't started so feel free! Thanks!
