### ISSUE TITLE
Create Cirq specific folder and utils

### ISSUE THREAD

**Issue by Aaron-Robertson** [unitaryfund/mitiq#591]
Pre-Request Checklist
---------------------

- [x] I am running the latest version of mitiq
- [x] I checked to make sure that this feature has not already been requested

Issue Description
-----------------

There are Qiskit and Pyquil folders for platform specific functions and executors, but no folder for Cirq.

Proposed Solution
-----------------

Create `mitiq_cirq/` folder similar to `mitiq_qiskit/` and `mitiq_pyquil/` with `mitiq_cirq/cirq_utils.py` that includes the Cirq executors from the docs.

Additional References
---------------------

Based on the conversation from #552.

**Comment by ckissane** [comment]
That seems to be a good thing to do to make things less confusing!

**Comment by rmlarose** [comment]
This was closed by #603.
