### ISSUE TITLE
Emphasize instructions on black formatting

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#593]
Could emphasize the instructions on code formatting with `black` in the documentation:
- put code in a code block
- subsection making the existing text more evident
- include a link in PR template not just to Black RTD docs, but to MItiq's docs, to show the way black is configured in the makefile

**Comment by purva-thakre** [comment]
@nathanshammah Is [this](https://github.com/unitaryfund/mitiq/blob/master/CONTRIBUTING.md#style-guidelines) the section that needs to be updated in docs ?
