### ISSUE TITLE
Mitiq about() shows the version for qiskit-terra instead of qiskit

### ISSUE THREAD

**Issue by Aaron-Robertson** [unitaryfund/mitiq#595]
Pre-Report Checklist
--------------------

- [x] I am running the latest version of mitiq
- [x] I checked to make sure that this bug has not already been reported

Issue Description
-----------------

Mitiq's `about()` function yields the incorrect version of Qiskit.

How to Reproduce
----------------

Using `from mitiq import about` and `about()` the listed Qiskit version is incorrect.

Recommend using `qiskit.__qiskit_version__` and getting `qiskit`.

`qiskit.__qiskit_version__`:
`{'qiskit-terra': '0.16.4', 'qiskit-aer': '0.7.5', 'qiskit-ignis': '0.5.2', 'qiskit-ibmq-provider': '0.11.1', 'qiskit-aqua': '0.8.2', 'qiskit': '0.23.6'}`

Environment Context
-------------------

```
print(qiskit.__qiskit_version__)
{'qiskit-terra': '0.16.4', 'qiskit-aer': '0.7.5', 'qiskit-ignis': '0.5.2', 'qiskit-ibmq-provider': '0.11.1', 'qiskit-aqua': '0.8.2', 'qiskit': '0.23.6'}
```

VS

```
print(about())

Mitiq: A Python toolkit for implementing error mitigation on quantum computers
==============================================================================
Authored by: Mitiq team, 2020 & later (https://github.com/unitaryfund/mitiq)

Mitiq Version:	0.7.0dev

Core Dependencies
-----------------
Cirq Version:	0.10.0.dev
NumPy Version:	1.20.1
SciPy Version:	1.6.1

Optional Dependencies
---------------------
PyQuil Version:	2.18.0
Qiskit Version:	0.16.4

Python Version:	3.8.5
Platform Info:	Darwin (x86_64)
```

**Comment by purva-thakre** [comment]
This seems to be an issue with how Qiskit checks for versions. For more, see [here](https://qiskit.org/documentation/install.html#checking-which-version-is-installed).

**Comment by rmlarose** [comment]
I agree it would be good to display `qiskit.__qiskit_version__["qiskit"]` instead of the current https://github.com/unitaryfund/mitiq/blob/master/mitiq/_about.py#L44.

**Comment by Aaron-Robertson** [comment]
I thought it would make a good first issue, but probably too confusing if it stays open for much time?
