### ISSUE TITLE
Replace the custom depolarizing channel in tests with the cirq.DepolarizingChannel

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#607]
In some PEC tests we had to define a custom depolarizing channel:

https://github.com/unitaryfund/mitiq/blob/69c588b084d09fd9f2696dc86c64da6b96ef5d8b/mitiq/pec/representations/tests/test_depolarizing.py#L44

since at that time `cirq.DepolarizingChannel` was not compatible with 2-qubit gates.

The Cirq issue has been fixed and so we could replace the custom channel with `cirq.DepolarizingChannel`.

**Comment by purva-thakre** [comment]
@andreamari This seemed like a very quick fix - replace the channel and make sure pytest runs `test_local_depolarizing_representation_with_choi` successfully. Let me know if I forgot to change something else because I found only 1 test using this custom channel.
