### ISSUE TITLE
No link for MEPs in documentation

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#608]
There is no link / broken link to the MEP template at 
https://mitiq.readthedocs.io/en/latest/contributing.html#proposing-a-new-feature-to-mitiq

**Comment by itsabhianant** [comment]
Hi,
By the broken link are you referring to the discord link?

**Comment by nathanshammah** [comment]
No, it refers to the fact that `docs/mep/0000-feature-proposal-TEMPLATE.md.` in the page of the link above does not take one to the linked file.
