### ISSUE TITLE
Make it so `fold_left` and `fold_right` match on odd scale factors

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#624]
We want to change `fold_gates_from_left` and `fold_gates_from_right` so that they match on odd scale factors. Namely, we want it so that

```python
fold_gates_from_left(circuit, 2k + 1) == fold_gates_from_right(circuit, 2k + 1)
```

for all integers `k`. This is to match how they are defined in https://arxiv.org/abs/2005.10921.

## Current behavior

Currently the circuit is folded up to a scale factor of 3, then this circuit is folded again treating all gates as though they were in the original circuit for scale factors beyond 3.

```python
import cirq
from mitiq.zne import scaling

circuit = cirq.Circuit(cirq.H(cirq.LineQubit(0)), cirq.CNOT(*cirq.LineQubit.range(2)))
# 0: ───H───@───
#           │
# 1: ───────X───

# They are the same for scale_factor = 3.
lscaled = scaling.fold_gates_from_left(circuit, 3)
rscaled = scaling.fold_gates_from_right(circuit, 3)
print(lscaled)
# 0: ───H───H───H───@───@───@───
#                   │   │   │
# 1: ───────────────X───X───X───

# They are different for scale_factor = 5, but we want them to be the same.
scaling.fold_gates_from_left(circuit, 5)
# 0: ───H───H───H───H───H───H───H───@───@───@───
#                                   │   │   │
# 1: ───────────────────────────────X───X───X───

scaling.fold_gates_from_right(circuit, 5)
# 0: ───H───H───H───@───@───@───@───@───@───@───
#                   │   │   │   │   │   │   │
# 1: ───────────────X───X───X───X───X───X───X───
```

For the last case (scale factor = 5), the returned circuit should be (for both left/right scaling)
```
0: ───H───H───H───H───H───@───@───@───@───@───
                          │   │   │   │   │
1: ───────────────────────X───X───X───X───X───
```

This would be a breaking change, so some scaling tests with scale factors > 3 may need to be modified.

**Comment by purva-thakre** [comment]
@rmlarose Why was this distinction made originally ? [In the code](https://github.com/unitaryfund/mitiq/blob/1467a8a4b2ad13605f61f56367b279608986e239/mitiq/zne/scaling/folding.py#L363) for `fold_gates_from_left`, a scale factor of greater than 3, calls a different function `fold_local`.

**Comment by andreamari** [comment]
@purva-thakre this is more or less how local folding functions are defined now in Mitiq (sketch):

```python
fold_gates_in_some_local_way(circuit, scale_factor):
  for gate in circuit:
      fold(gate) #modify circuit in place
      if  total number of gates is enough to match the scale_factor:
             return circuit
  # if the previous loop did not return (i.e. if scale_factor is > 3), repeat the loop again.
  for gate in circuit:
      fold(gate) #modify circuit in place
      if  total number of gates is enough to match the scale_factor:
             return circuit 
 # if the previous loop did not return (i.e. if scale_factor is > 5), repeat the loop again.
  for gate in circuit:
      fold(gate) #modify circuit in place
      if  total number of gates is enough to match the scale_factor:
             return circuit

  .... and so on.....
```

This recursive workflow has the advantage that one doesn't need to pre-compute in advance what gates needs to be folded. One simply starts folding the gates of the circuit until the stop condition is achieved. However this has some side-effects due to the recursive nature of the loops: in the second loop there is no distinctions between the original gates of the input circuit and the new gates which have been inserted in the first loop. This creates the non-uniform folding effects shown in the code example of this issue. 
For `scale_factor < 3`, only one loop is executed and so this problem does not emerge.

**Comment by andreamari** [comment]
I think also `fold_gates_at_random` should be fixed as well to match the theoretical definition in https://arxiv.org/abs/2005.10921.
I tested that for large odd scale_factors, sometimes the folding is non-uniform.

**Comment by rmlarose** [comment]
> I think also `fold_gates_at_random` should be fixed as well to match the theoretical definition in https://arxiv.org/abs/2005.10921.
> I tested that for large odd scale_factors, sometimes the folding is non-uniform.

I suggest opening a new issue for this.
