### ISSUE TITLE
Investigate why the release action did not trigger

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#631]
Issue Description
-----------------

Investigate why the release action did not trigger on the latest release, 0.7.0. 

Additional info
----------------

See  https://github.com/unitaryfund/mitiq/actions/workflows/publish-pypi.yml.

**Comment by crazy4pi314** [comment]
I can post mortem this:

Basically the syntax for the files as currently on master was invalid as you can see here: https://github.com/unitaryfund/mitiq/actions/runs/619303706/workflow#L11

Once we merge #597 I think this should be resolved, so I would move to close this once that is done. 👍
