### ISSUE TITLE
Make mitigate_executor and decorators more uniform between ZNE and PEC

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#638]
Issue Description
-----------------
For zero noise extrapolation there are 3 alternatives ways to use Mitiq: `execute_with_zne`, `mitigate_executor` and `zne_decorator`. 

For probabilistic error cancellation, we only have `execute_with_pec`.

It would be good to have a more uniform interface. This is also relevant for the arXiv resubmission.

Proposed Solution
-----------------
I would propose two options:

1. Add `mitigate_executor` and `pec_decorator` in `mitiq.pec`.
2. Remove the `zne_decorator` from `mitiq.zne` and only add `mitigate_executor` in `mitiq.pec`. The decorator is nice but in practice is not very useful. Indeed one typically wants to keep both the mitigated and the unmitigated executor in order to compare the results, but this is not possible with a decorator.

**Comment by rmlarose** [comment]
Discussed at Mitiq meeting. Decided to:

1. Define decorator and function for PEC and all other error mitigation techniques going forward.
2. Do `from mitiq import zne, pec, cdr, xyz` instead of importing the stuff in (1) at the top-level.

**Comment by andre-a-alves** [comment]
I think I've accomplished this, and I am writing the tests right now. Writing the tests raised a question, though:
While zne spreads its tests for cirq, qiskit, and pyquil across different files in different locations, all the pec tests are contained within a single file test_pec. Is there a plan to spread pec testing into multiple files as well? If so, should I put the executor and decorator tests in the current test_pec file, or should I go ahead and create individual test files for each of the frameworks and place the new tests there?

**Comment by andreamari** [comment]
@andre-a-alves good point! 
For the moment I would put them in `test_pec.py`, for consistency with other PEC tests. For the future we could discuss the alternative option.
Personally, I find more intuitive the current PEC approach where that tests related to functions in `pec.py` are in `test_pec.py` even if related to non-Cirq circuits. However, I recognize that this is different from the way in which we organized ZNE tests.
