### ISSUE TITLE
Improve fold global function

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#653]
The current `fold_global` function:

1. Has a `squash_moments` option but I guess that even if it is set to `False`, the folded blocks are always squashed anyway.
2. `fidelities` is not an option as in gate folding methods, but it could be.

Proposal for new changes:
1. Make use of a `fidelities` when applying fractional folding, in a similar way as it is now done for local folding methods.
2. Remove the `squash_moments` option and always try to **keep** the moment structure. The reason is that if one applies global folding there is not a strong motivation to squash. (we are not _inserting_ new gates in the middle of the input circuit we are just _appending_ circuits or sub_circuits circuits at the end of the input_cirucit).
3. Alternatively, keep the  `squash_moments` option but make sure that, if `squash_moments=False`, the moment structure is  preserved even for the appended circuits (virtual folded blocks). Maybe in this case  `squash_moments=False` should be default?

Between (2) and (3) I would prefer (2) for its conceptual simplicity, but (3) is fine.

**Comment by rmlarose** [comment]
Option (2) SGTM.

**Comment by andreamari** [comment]
I am reopening this since it is something worth doing, even if not urgent.

**Comment by purva-thakre** [comment]
Based on above discussion, I am going to work on option 2.

**Comment by purva-thakre** [comment]
> always try to keep the moment structure

@andreamari Do you mind clarifying this a bit more ? I am confused between the following : 

1. Each appended circuit is in 1 moment i.e. if the scale factor was 3, there are 3 moments etc. 
2. The number of moments in output circuit is increased by the scale factor and moments used to define the input circuit

**Comment by andreamari** [comment]
Hi @purva-thakre,
I think your second option is correct.
In the example that you linked the input circuit has 3 moments and the the expected results should have 9 moments as it indeed happens know.  However this example is too simple since there are no "holes" in the circuit.

Below I give an example which shows how the current fold global destroy the moment structure of the input circuit by squashing the gates. The idea of this issue is to avoid this effect. 

```
Input circuit:
0: ───H───────────────

1: ───────Z───────────

2: ───────────S───────

3: ───────────────T───


Example with scale_factor=3

Folded circuit with current fold_global function:
0: ───H───H──────H───

1: ───Z───Z──────Z───

2: ───S───S^-1───S───

3: ───T───T^-1───T───

Folded circuit desired result:
0: ───H─────────────────────────────────H───H───────────────

1: ───────Z─────────────────────────Z───────────Z───────────

2: ───────────S──────────────S^-1───────────────────S───────

3: ───────────────T───T^-1──────────────────────────────T───


Example with scale_factor=2

Folded circuit with current fold_global function:
0: ───H──────────────

1: ───Z──────────────

2: ───S───S^-1───S───

3: ───T───T^-1───T───

Folded circuit desired result:
0: ───H─────────────────────────────────────

1: ───────Z─────────────────────────────────

2: ───────────S──────────────S^-1───S───────

3: ───────────────T───T^-1──────────────T───
```

As you can see the "desired" results are equivalent to `fold_global` results but preserve the moment structure i.e. the "temporal shape" of the input circuit. 

I also attach the code that generated the circuits above (not sure if useful):
<details>
 <summary>Code to reproduce</summary>
from cirq import Circuit, LineQubit, S, H, T, CNOT, Z, inverse
from mitiq import zne


qreg = LineQubit.range(4)
circuit_H = Circuit(H(qreg[0]))
circuit_Z = Circuit(Z(qreg[1]))
circuit_S = Circuit(S(qreg[2]))
circuit_T = Circuit(T(qreg[3]))
circuit = circuit_H + circuit_Z + circuit_S + circuit_T
print("Input circuit:", circuit, sep="\n")


print("\n\nExample with scale_factor=3")
folded_current = zne.scaling.fold_global(circuit, 3)
print("\nFolded circuit with current fold_global function:", folded_current, sep="\n")
folded_expected =  circuit + inverse(circuit) + circuit
print("\nFolded circuit desired result:", folded_expected, sep="\n")
assert len(folded_expected) == 3 * len(circuit)
print("\n\nExample with scale_factor=2")
folded_current = zne.scaling.fold_global(circuit, 2)
print("\nFolded circuit with current fold_global function:", folded_current, sep="\n")
folded_expected =  circuit + inverse(circuit[2:]) + circuit[2:]
print("\nFolded circuit desired result:", folded_expected, sep="\n")
assert len(folded_expected) == 2 * len(circuit)
</details>
