### ISSUE TITLE
publish-pypi.yml doesn't publish to pypi

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#665]
For the latest GitHub release (0.8.0), the [publish-pypi.yml](https://github.com/unitaryfund/mitiq/blob/master/.github/workflows/publish-pypi.yml) action never triggered. The fix is probably some minor tweaking for when the action should take place.

**Comment by purva-thakre** [comment]
@rmlarose Do you mind testing the workflow with a [manual trigger](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch) without the create condition ? I don't think I will be able to test this in my fork without proper credentials and I just want to verify it does run on release branch. 

If it does, then I wonder if there's an issue with `[created]` vs [`create`](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#create).

**Comment by purva-thakre** [comment]
> Let me know if I misunderstood.

Not really. I was only throwing around some ideas since these files cannot be tested unless you run them on specific branches.

**Comment by nathanshammah** [comment]
I can help look into this, and into the test pypi trigger.
