### ISSUE TITLE
Move all ZNE unit tests to `mitiq.zne`

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#668]
There's some hanging around in `mitiq_qiskit` and `mitiq_pyquil`. We decided @ Mitiq meeting that it's better to put these in test files in `mitiq.zne`.

This also makes the testing structure more consistent between `mitiq.zne` and `mitiq.pec` (all PEC tests are in `mitiq.pec`).

**Comment by purva-thakre** [comment]
@rmlarose Is it preferred to add all of them in [test_ZNE](https://github.com/unitaryfund/mitiq/blob/master/mitiq/zne/tests/test_zne.py) ? 

Or add [test_ZNE_mitiq_pyquil](https://github.com/unitaryfund/mitiq/blob/master/mitiq/mitiq_pyquil/tests/test_zne_mitiq_pyquil.py) and [test_ZNE_mitiq_qiskit](https://github.com/unitaryfund/mitiq/blob/master/mitiq/mitiq_qiskit/tests/test_zne_mitiq_qiskit.py) to `ZNE/tests` folder ?

**Comment by rmlarose** [comment]
I would say to put the tests in those files into https://github.com/unitaryfund/mitiq/blob/master/mitiq/zne/tests/test_zne.py (and delete the old test files). One might be able to combine some tests (especially ones with different circuit interfaces but the same otherwise) with `pytest.mark.parameterize`.

**Comment by andre-a-alves** [comment]
During the meeting @crazy4pi314 had also mentioned the possibility of setting the testing up to take advantage of advanced PyTest features. I could look into those additional requirements and move all the tests around so their location is consistent (original intent), as close to their code as possible (goal from meeting), and compatible with those advanced features. It will take just a little bit longer to research what those requirements are, but if we want to implement the advanced features down the road, it's better to move things once than twice.
