### ISSUE TITLE
[Discussion] Allow exclusion of indices/moments in `check_foldable`

### ISSUE THREAD

**Issue by purva-thakre** [unitaryfund/mitiq#675]
In `folding.py`, [`check_foldable`](https://github.com/unitaryfund/mitiq/blob/2acb40d8c7970b43bed682137229ca073905cc4a/mitiq/zne/scaling/folding.py#L94) is used to verify if the input circuit contains non-unitary gates or non-terminal measurements.

Instead of failing to fold the entire circuit for above reason, an additional check could be done to see if the rest of the circuit could still be folded except for the index/moment with non-acceptable gates. If a user knows the positions of such gates then they should also be given the option to input an exclusion set i.e. fold rest of the circuit beyond the exclusion set. 

```python
def _check_foldable(circuit: Circuit, exclude: FrozenSet[Any] = frozenset(),) -> None:
```
If this is added then all other functions will need to take exclusion set as input as well to output a folded circuit (I think ?). If the exclusion set is not provided then `check_foldable` could create a set as needed.

**Comment by purva-thakre** [comment]
I do want to work on this soon after I have caught up with other things I am currently working on.

**Comment by purva-thakre** [comment]
no don't close

**Comment by purva-thakre** [comment]
@rmlarose @andreamari Does following seem like a good solution to this issue ? I am also available to discuss it on all weekdays except Tuesdays and Thursdays. 

I want to define a couple of functions for above case similar to how [`_pop_measurements`](https://github.com/unitaryfund/mitiq/blob/2acb40d8c7970b43bed682137229ca073905cc4a/mitiq/zne/scaling/folding.py#L64) is used but still a bit differently :

1. If `check_foldable` is about to raise an error, it can check if the circuit can be split into portions that are foldable and non-foldable gates are saved in a frozen set to be appended later.
2. A function will have to be defined to shift the moments of portions of foldable and non-foldable gates depending on if the first portion was foldable. 
3. Use currently available functions in Mitiq's folding module to fold the foldable portions with the new moments calculated in Step 2 - here a choice could be provided to either use same folding method on all portions or different method and/or scale factors (might leave the different scale factors design for later after functions discussed have been added). 
4. A function that will then finally append all of these different portions together to output a folded circuit

![image](https://user-images.githubusercontent.com/66048318/150273490-ad8cbb6b-5f34-4f13-98d4-e077691d1be4.png)

**Comment by andreamari** [comment]
Hi @purva-thakre, in principle something like this could work but I also see some critical aspects:

- The cut-and-paste trick is quite complicated and so subject to bugs and maintenance overhead.
- If there are many "red" gates there will be a large number of short blue slices that are difficult to scale for non-odd-integer scale factors. Maybe it could be better to apply local folding methods without removing the "red" gates but simply avoiding to fold them when we loop over the circuit operations. We do something similar for gates with fidelity 1 (zero weight).
- Note also that all folding functions are multi-frontend. So we would need a way to define the "excluded gates" in a multi-platform way (not just for Cirq circuits).

Given the previous points my main question, before we go into the details, is the following: 
- Is the motivation for heaving this feature strong enough to justify the introduction of the associated code complexity. What is an important use-case in which this feature is necessary?

Happy to discuss over Discord about this if you want.
