### ISSUE TITLE
Decide and document policy for optional packages

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#678]
There have been multiple cases of ambiguity when we want to integrate with packages, sometimes just for examples, sometimes for limited features in code, that we may not want to support as core/development/optional requirements for the Mitiq package, due to conflicts that may arise. 
Examples include:
- An idea for an XACC example #357, 
- The Windows CI issues arising due to `pymc3`, that would be used in the Bayes factory #646 part of ZNE
- Tensorflow, #417 which is called by Tensorflow Quantum example #559  

At the last Mitiq meeting we decided to include these optional packages but do not support them explicitly. This should be somehow refined and explained in the contributing guidelines in the documentation.

**Comment by rmlarose** [comment]
There's an important difference: XACC and TFQ would only be for the documentation and can go in dev_requirements. pymc3 would be for using Mitiq and would go in requirements.txt.

Generally I'm against adding a bunch of "executor examples" - if the documentation clearly defines executors, it should be obvious how to use whatever package you want to do this.

The pymc3 issue needs a final decision, but I thought we voted for (i) keep using pip, (ii) handle the pymc3 install in CI on windows as a special case, (iii) tell people if they want to use pymc3 on windows, they have to install whatever needs to be installed.
