### ISSUE TITLE
Installation from source

### ISSUE THREAD

**Issue by paniash** [unitaryfund/mitiq#680]
Pre-Request Checklist
---------------------

- [X] I am running the latest version of mitiq
- [X] I checked to make sure that this feature has not already been requested

Issue Description
-----------------

Currently the readme doesn't contain instructions on building mitiq from source. Is there a way to do it?

Proposed Solution
-----------------

A convenient way (especially for contributors) would be to enable installing from source using `pip install -e .` which would install `mitiq` as an editable file.

**Comment by andreamari** [comment]
Hi @paniash, for the moment this is written the docs https://mitiq.readthedocs.io/en/latest/contributing.html#development-install 
But we could consider putting this in the Readme too.

**Comment by andreamari** [comment]
It's fine for me. But I ask @crazy4pi314 for a second opinion.

**Comment by crazy4pi314** [comment]
I'm good with readme, but maybe both places (docs and readme?)

**Comment by paniash** [comment]
@crazy4pi314 I've made the PR for it (as per your suggestion). Could you review it and let me know? Another reviewer seems to have a different opinion on the PR.

**Comment by rmlarose** [comment]
We discussed this at our weekly meeting and decided to link to the docs instead of writing it out explicitly in the readme (i.e., to go with https://github.com/unitaryfund/mitiq/pull/682#discussion_r633722971).

**Comment by paniash** [comment]
Fixed in `[bac9a5a](bac9a5a07ccc20f1d90f7d273de57713640f9f04)`.
