### ISSUE TITLE
Fix reference numbering by citing the CDR paper

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#692]
Right now the CDR paper "Error mitigation with Clifford quantum-circuit data" is listed as the first reference in the Mitiq guide, even if it does not appear in the Users Guide. https://mitiq.readthedocs.io/en/stable/zz_bibliography.html

I think that this is due to the fact that it is cited in the codebase but not yet in the rest of the documentation rst files.  

Once we add the documentation, it should fix the correct list.

**Comment by rmlarose** [comment]
Is this fixed? I see it as the last entry in [the bib](https://mitiq.readthedocs.io/en/stable/zz_bibliography.html).

![image](https://user-images.githubusercontent.com/32416820/124198619-05639680-da9f-11eb-8f8c-ad4fc83e4c9f.png)

**Comment by nathanshammah** [comment]
Yes, thanks for noticing.
