### ISSUE TITLE
Make `cdr.execute_with_cdr` compatible with any `QPROGRAM`

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#710]
Right now you can only use a Cirq circuit in `execute_with_cdr` and related functions. All CDR functionality should be compatible with any `QPROGRAM`.

**Comment by andreamari** [comment]
@rmlarose A lazy idea: maybe for the release 0.9.0 it could be enough to support  `QPROGRAM`s in `execute_with_cdr` and push the generalization of all the other cdr functions to the next release.
