### ISSUE TITLE
Add a near-Clifford simulator for CDR

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#712]
The CDR method needs a near-Clifford simulator to be efficient at scale. Currently, this is sort-of placed on the user as an [argument to `execute_with_cdr`](https://github.com/unitaryfund/mitiq/blob/master/mitiq/cdr/cdr.py#L35). It would be good to have such a simulator available in Mitiq for this purpose.

## Description

The function should be able to efficiently simulate near-Clifford circuits, i.e., circuits where most operations are Clifford except for a small number (possible zero) of operations. Such near-Clifford circuits are generated by [`generate_training_circuits`](https://github.com/unitaryfund/mitiq/blob/cccbd4961c05cc65d0004c0c134073bce616c72a/mitiq/cdr/clifford_training_data.py#L31) in CDR. The simulator should input a near-Clifford circuit as a `QPROGRAM` with computational basis measurements and return measurement samples, for example as a dictionary `{bitstring_1: counts_1, ..., bitstring_n: counts_n}`. 

### Notes

- Several packages have implemented Clifford simulators, so one does not necessarily need to start from scratch on this.
- Any classical (noiseless) simulator works with CDR but is not necessarily efficient. For example, in tests we currently use a simple wavefunction simulator and sample from the resulting state.

**Comment by natestemen** [comment]
With https://github.com/unitaryfund/mitiq/issues/2241 open we will now close this in favor of adding some documentation.
