### ISSUE TITLE
Test Mitiq without 3rd party packages

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#740]
Issue Description
-----------------

Currently CI runs all tests in a development environment (where all 3rd party packages packages in `dev_requirements.txt` are installed).
It would be good to test some basic functionality of Mitiq without some/all 3rd party packages.

Proposed Solution
-----------------
Define a new command, `make test-basic`, which runs some basic tests that are supposed to work in a non-dev environment e.g.: 
- run some of the existing tests which only require Cirq circuits.
- maybe check that `mitiq.about()` print the expected output?

Once we have this command, we could run  `make test-basic` in our CI workflows before installing the dev requirements. After this, the existing workflows can follow as usual: dev requirements installation followed by `make test`  or `make test-all`.

**Comment by rmlarose** [comment]
Updated title / description to make this a little more precise. We still need dev requirements for testing, e.g., pytest, it's really about testing without Qiskit, pyQuil, etc.
