### ISSUE TITLE
Move example Jupyter notebook

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#777]
The example Jupyter notebook at https://mitiq.readthedocs.io/en/stable/examples/test.html is quite nice, but it's very strange to include this in the same spot as Mitiq examples - it's a note to contributors, not an example using Mitiq.

![image](https://user-images.githubusercontent.com/32416820/124055861-afd1b000-d9f2-11eb-946b-b84bf4c08a1a.png)

Can we move this to https://mitiq.readthedocs.io/en/stable/toc_contributing.html under "Contributing to the documentation"?

**Comment by nathanshammah** [comment]
Personally I don't dislike it too much where it is. One option could be to include it in the Contributing or Contributing to docs part.

**Comment by rmlarose** [comment]
Agreed to remove from TOC @ Mitiq meeting.
