### ISSUE TITLE
Folding in Cirq for multi-qubit circuits

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#8]
Folding a subset of gates [(fold_gates)](https://github.com/unitaryfund/mitiq/blob/master/mitiq/folding_cirq.py#L40) in Cirq iterates over moments instead of gates.

I propose we rename `fold_gates` to `fold_moments` and add another method `fold_gates` which correctly iterates over scheduled operations to fold a subset of gates. The latter is implemented in https://github.com/unitaryfund/mitiq/pull/7

**Comment by andreamari** [comment]
I agree!
