### ISSUE TITLE
Using qiskit QuantumCircuit with some unused registers 

### ISSUE THREAD

**Issue by Eyuel-E** [unitaryfund/mitiq#802]
Pre-Report Checklist
--------------------
 [ ✓ ] I am running the latest version of mitiq
 [ ✓ ] I checked to make sure that this bug has not already been reported

Issue Description
-----------------

I was using the execute_with_zne function with qiskit's circuit. However, the execute_with_zne() fails to execute when a QuantumCircuit with some unused registers is provided. The same problem arises for the same reason when I try to use it with a circuit transpiled for a certain backend. For example, the following code results in an Error. I guess, it is expecting a circuit where all the quantum registers are used.

### Code Snippe

```python
import qiskit
from qiskit import QuantumCircuit
from qiskit.test.mock import FakeAlmaden, FakeAthens,FakeSantiago
from mitiq.zne import execute_with_zne
from qiskit import IBMQ
#backend = FakeAthens()
#provider = IBMQ.load_account()
#backend = provider.get_backend('ibmq_santiago')
#backend = provider.get_backend("ibmq_qasm_simulator")

backend = FakeSantiago()

def qiskit_executor(circuit: qiskit.QuantumCircuit, shots: int = 4096) -> float: 
      
    job = qiskit.execute( circuit, backend, shots=shots )
    results = job.result()
    counts = results.get_counts()
    expval = counts['00'] / shots

    return expval

circ = QuantumCircuit(2, 2)
for _ in range(100):
     circ.x(0)
     circ.x(1)

circ.measure(0, 0)
circ.measure(1, 1)

circ = qiskit.transpile(circ,backend)
unmitigated = qiskit_executor(circ)
mitigated = execute_with_zne(circ, qiskit_executor)
```

### Error Output

 70 unmitigated = qiskit_executor(circ)
---> 71 mitigated = execute_with_zne(circ, qiskit_executor)
     72 
     73 print(mitigated)

~/anaconda3/lib/python3.8/site-packages/mitiq/zne/zne.py in execute_with_zne(qp, executor, factory, scale_noise, num_to_average)
     60         raise ValueError("Argument `num_to_average` must be a positive int.")
     61 
---> 62     return factory.run(qp, executor, scale_noise, int(num_to_average)).reduce()
     63 
     64 

~/anaconda3/lib/python3.8/site-packages/mitiq/zne/inference.py in run(self, qp, executor, scale_noise, num_to_average)
    520 
    521         # Get all noise-scaled circuits to run
--> 522         to_run = self._generate_circuits(qp, scale_noise, num_to_average)
    523 
    524         if len(qp) < 5:

~/anaconda3/lib/python3.8/site-packages/mitiq/zne/inference.py in _generate_circuits(self, circuit, scale_noise, num_to_average)
    589         for scale_factor in self.get_scale_factors():
    590             for _ in range(num_to_average):
--> 591                 to_run.append(scale_noise(circuit, scale_factor))
    592         return to_run
    593 

~/anaconda3/lib/python3.8/site-packages/mitiq/interface/conversions.py in new_scaling_function(circuit, *args, **kwargs)
    231 
    232             scaled_circuit.remove_final_measurements()
--> 233             _transform_registers(
    234                 scaled_circuit, new_qregs=circuit.qregs,
    235             )

~/anaconda3/lib/python3.8/site-packages/mitiq/interface/mitiq_qiskit/conversions.py in _transform_registers(circuit, new_qregs)
    180 
    181     if len(qreg_sizes) and sum(qreg_sizes) != nqubits_in_circuit:
--> 182         raise ValueError(
    183             f"The circuit has {nqubits_in_circuit} qubits, but the provided "
    184             f"quantum registers have {sum(qreg_sizes)} qubits."

ValueError: The circuit has 2 qubits, but the provided quantum registers have 5 qubits.

Environment Context
-------------------
Mitiq: A Python toolkit for implementing error mitigation on quantum computers

Authored by: Mitiq team, 2020 & later (https://github.com/unitaryfund/mitiq)

Mitiq Version:	0.9.1

Core Dependencies
-----------------
Cirq Version:	0.10.0
NumPy Version:	1.20.1
SciPy Version:	1.4.1

Optional Dependencies
---------------------
PyQuil Version:	Not installed
Qiskit Version:	0.26.2
Braket Version:	Not installed

Python Version:	3.8.8
Platform Info:	Darwin (x86_64)

**Comment by rmlarose** [comment]
Thanks @Eyuel-E for reporting, this is indeed a bug on our end. I opened #803 to fix it and we should have a patch release soon (probably next week) allowing you to run this example.

Note unrelated to bug: When you call `qiskit.transpile`, you probably want to set `optimization_level=0`. If you print out the circuit in your example after calling `qiskit.transpile`, it only has the measurements.

**Comment by Eyuel-E** [comment]
Thank you for the reply @rmlarose . 

Yes, that's right. Actually, I just provide the basic example, as the operation is identity it makes sense that it only has measurement when optimized. I was using different circuit initially.  Anyway thanks I didn't notice that at first.
