### ISSUE TITLE
Add a notebook on ZNE for randomized benchmarking with backends

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#806]
Add a notebook with a tutorial in the examples' section of the documentation on ZNE for randomized benchmarking on IBM Q and Rigetti back-ends, as discussed in #775, to provide an example from the Mitiq paper that is self-consistent and useful for users (Section III.A, Figure 3 in arXiv v2).

**Comment by purva-thakre** [comment]
@nathanshammah I can take this.
