### ISSUE TITLE
Enable interactive code in the documentation

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#813]
This could be done with [`jupyter-book`](https://jupyterbook.org/intro.html), as discussed in the Mitiq meeting, which extends capabilities of `my-binder`.

**Comment by nathanshammah** [comment]
Quick update on the findings so far:

- 1. As expected, setting up My Binder was very straightforward, and the Mitiq runs on cloud if you click here ---> [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/unitaryfund/mitiq/HEAD), where one can fire up a new notebook and test that Mitiq is installed:
<img width="916" alt="Screen Shot 2021-07-23 at 12 04 37" src="https://user-images.githubusercontent.com/14573436/126760729-2c5359d0-3ac2-44e2-8496-6edae47411e0.png">
 
- 2. Right now there are no jupyter notebooks in the documentation to point to, so the user does not see interactive examples. Point 1. was enabled just by copy-pasting the Mitiq repo link in the Mybinder.org website. It may be possible that by adding specifications in an appropriate `.yml` file in the MItiq Github repository, the My Binder instructions will be such that they include plugins needed to make the `.rst`, `.md`, and `.myst` examples interactive and runnable, such as `Myst-NB` and `jupytext`. I am looking into this. 
- 3. The alternative approach is to use `Jupyter Book`, which is great, and I went through the whole online documentation. I particularly like the `Thebe` options that keeps you in the webpage and make it interactive without changing it at all, and the `plotly` integrations (maybe plotly is also configurable with jupyter nb). However, there are a couple of points to understand properly and decide upon here. I found already these issues: 
- 4. Currently `Jupyter Book` is not hosted on Read The Docs (RTD), which is were we are hosting the documentation. I understand that RTD is considering integrating, but for the time this would mean not having the documentation hosted at  and changes also in continuous integration. Jupyter Book would use GitHub Pages for hosting. I actually think that this could be even better, but it is quite a big breaking change, involving also changes on internet traffic, etc. 
-  5. `Jupyter Book` seems to be a very heavily reworked `Sphinx` specification, but it is not clear how to keep some crucial features of `Sphinx`, such as the API doc. I am looking into this as it should be possible to keep them, but I have not found anything explicit about it in the couple of examples I've looked at and in the JB documentation. Note that the `conf.py` file is changed with a `config.yaml` file. We also have several plugins customizing our API-doc and user guide, such as Napoleon specifics, etc. I think this could be all ported, but right now is a bit of a question mark. 
- 6. In general, I found no straightforward guide to switch from a Sphinx project to a JB. It may be also due to the fact that JB was thought most for books, just like Qiskit used it for its book on quantum and then has a manual for Qiskit that is separate. We started the issue with the intention of completely migrating the documentation to JB.

I will work to assess the points above, some that we can discuss at the Meeting meeting (6pm CET Fridays on Unitary Fund Discord, http://discord.unitary.fund/). Personally I would be happy to enable a first interactive option along point 1., with Juptyer notebooks, which should be super light weight, if doable (should only require adapting a specific `.yaml` file for My Binder), and then look more carefully into JB migration, that requires more work and deliberation and may take a bit of time.

**Comment by astrojuanlu** [comment]
Hi! Juan Luis from Read the Docs here, @nathanshammah pinged me privately about this issue.

Your analysis of the current status of the ecosystem is very good. There is ongoing work to make Sphinx support `.yaml` config, one of the difficulties of supporting Jupyter Book natively on Read the Docs https://github.com/sphinx-doc/sphinx/issues/9040 but the conversation has stalled. You can also see some discussions we had at the beginning of the year at https://github.com/executablebooks/jupyter-book/issues/1091#issuecomment-725590863.

If you want to enable interactive code in a Sphinx project, you might want to have a look at https://sphinx-thebe.readthedocs.io/ which is also developed by the Executable Books Project, but is a conventional Sphinx extension that should work outside of Jupyter Book.

Happy to jump in a call or discuss this further if I can be of help!

**Comment by nathanshammah** [comment]
Thanks @astrojuanlu, actually this solution of using `sphinx-thebe` in the current framework, and possibly add My Binder too, looks great to me and a good fix while things may be sorted out between Sphinx, JB & RTD. Thanks for the context.

**Comment by astrojuanlu** [comment]
Hi folks! Jupyter Book can finally be used on Read the Docs. This functionality hasn't been released yet and we're looking for beta testers, in case you're interested.

See a working example here: https://github.com/astrojuanlu/jupyterbook-on-read-the-docs

which I created following these docs: https://jupyterbook.org/publish/readthedocs.html

Let me know if you have any questions! Happy to jump to a chat.

**Comment by nathanshammah** [comment]
I am reopening this as given the recent [support](https://blog.readthedocs.com/jupyter-book-read-the-docs/) of RTD of Jupyter book, we could move from Sphinx to Jupyter Book.
