### ISSUE TITLE
New technique: Measurement error mitigation

### ISSUE THREAD

**Issue by crazy4pi314** [unitaryfund/mitiq#815]
### Problem

Mitiq needs more error mitigation techniques.

Measurement error mitigation is based on [Measurement Error Mitigation for Variational Quantum Algorithms](https://arxiv.org/abs/2010.08520), should be relatively easy to implement.

### Rough requirements

- Should be implemented in a way such that it is very easy to compose with existing techniques (e.g., ZNE).
- Requires support for measurement results.

**Comment by rmlarose** [comment]
#844 added on technique for measurement error mitigation, more to come!

**Comment by rmlarose** [comment]
RFC for this issue here, please review:

https://docs.google.com/document/d/1Mb-OoojXBm0k8VTapNUkQQi4YQR5vsUvNJqmVgFpIns/edit?usp=sharing

**Comment by amirebrahimi** [comment]
I'd like to offer to take this on as part of a [final project for QCourse511](https://gitlab.com/qworld/qeducation/qcourse511-1/-/issues/21). Final deliverables are due January 11th though, so my question to the Mitiq team is whether it would be feasible to reach an agreement on the design to allow implementation time before that deadline? At the very least I could perform a preliminary implementation based on the current state of the design doc.

**Comment by rmlarose** [comment]
Thanks @amirebrahimi. You are more than welcome to take this up but I have concerns about the Jan 11th date, especially with the holiday break - there are a few points that need to be worked out in the RFC, then once that is accepted, we need to review the PR(s).

As a practical suggestion for your final project, you may consider doing your own complete implementation on a fork so you are not slowed down by the review process. You can of course make a pull request with this at any time. I hesitate to promise it can be merged before Jan 11th though.

**Comment by amirebrahimi** [comment]
> Thanks @amirebrahimi. You are more than welcome to take this up but I have concerns about the Jan 11th date, especially with the holiday break - there are a few points that need to be worked out in the RFC, then once that is accepted, we need to review the PR(s).
> 
> As a practical suggestion for your final project, you may consider doing your own complete implementation on a fork so you are not slowed down by the review process. You can of course make a pull request with this at any time. I hesitate to promise it can be merged before Jan 11th though.

I think that is a good plan and anything after the 11th can be worked out as the RFC firms up.

**Comment by andreamari** [comment]
[This a the new RFC](https://docs.google.com/document/d/1buO5PrO5sS02VXjcaYf37RuR0rF6xpyr4J9H1tI4vN4/edit#heading=h.c072otyej9hw) by @amirebrahimi. Thanks Amir!

Manually converted from the md file in #1294. Given the new contribution policy discussed in #1194.

**Comment by nathanshammah** [comment]
Thanks @amirebrahimi, we can discuss together, whenever you can, during the Mitiq meetings, the timeframe and follow-up issues to implement the feature.

**Comment by amirebrahimi** [comment]
Sounds good. I'll plan on joining tomorrow's meeting.

**Comment by andreamari** [comment]
@allcontributors please add @amirebrahimi for code, test, doc.

**Comment by andreamari** [comment]
Thanks @kun-wang, very interesting!
In this first stage we are probably going to just self-implement the matrix inversion method.
However, in a second stage, we can consider using some of your advanced post-processing methods.
Out of curiosity, is QCompute:QEP a self-contained PyPy package or is it instead a part of the full `qcompute` SDK?

**Comment by andreamari** [comment]
A MVP of the REM module is in Mitiq since we merged its main implementation PR  https://github.com/unitaryfund/mitiq/pull/1449 . 
We are still working on some improvements (e.g. writing docs), but I would say that this issue can be closed.
