### ISSUE TITLE
New technique: Post-selection of measurement results

### ISSUE THREAD

**Issue by crazy4pi314** [unitaryfund/mitiq#816]
### Problem

- Trivial to implement (see below).
    - Technically can be framed as quantum subspace expansion with a classical code, but probably not the best to frame this way in Mitiq.
- Can significantly improve performance when applicable.

```python
from typing import Dict
 
def post_select(
    measurements: Dict[str, int], hamming_weight: int
) -> Dict[str, int]:
   return {k: v for k, v in measurements.items() if sum(map(int, k)) == hamming_weight}
```

### Rough requirements

- Requires support for measurement results.

**Comment by rmlarose** [comment]
Closed by #844.
