### ISSUE TITLE
New technique: Learning-based quantum error mitigation

### ISSUE THREAD

**Issue by crazy4pi314** [unitaryfund/mitiq#821]
### Problem

Mitiq needs more error mitigation techniques.

The [Learning-based quantum error mitigation](https://arxiv.org/abs/2005.07601) could be viewed as an enhancement to `mitiq.cdr`: Fit data with ansatz other than ax + b.

### Rough requirements

- TBD

## Draft RFC
https://docs.google.com/document/d/1VrZRV59-2ApemebfbL556Rj7I2AMhAS7bJgGuTg3K1w/edit?usp=sharing

**Comment by Misty-W** [comment]
@crazy4pi314 I'd like to give this one a try.

**Comment by crazy4pi314** [comment]
Awesome! I'd suggest drafting a proposal for the rough architecture/syntax you are thinking of, and then that give the community a good way to give feedback! There is a formal template in the docs folder, else sharing a word/Google doc link here works too.

**Comment by Misty-W** [comment]
Link to my draft RFC - still very rough

https://docs.google.com/document/d/1Bl8Ix4MB32wa_X_FwMx2LLmt3BRyzoyHwcuYphbGIV8/edit?usp=sharing

**Comment by Misty-W** [comment]
Nooo don’t close this, GitHub bot!

**Comment by Misty-W** [comment]
https://docs.google.com/document/d/1VrZRV59-2ApemebfbL556Rj7I2AMhAS7bJgGuTg3K1w/edit?usp=sharing

**Comment by nathanshammah** [comment]
The RFC (design document) has been approved.

**Comment by Misty-W** [comment]
Step 1 of implementation complete: function to calculate biased noise representations (see #1109)
