### ISSUE TITLE
Spruce up docs landing page

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#828]
The [documentation landing page](https://mitiq.readthedocs.io/en/stable/) is just a huge outline of links and is very bland & boring. (Also, it says "mitiq" instead of "Mitiq" still.) 

![image](https://user-images.githubusercontent.com/32416820/125365453-49c62080-e342-11eb-8880-50c7ec3d9613.png)

## Options

- Add some text and/or images to spruce this up. To be honest I don't think we need the huge outline of links at all - the top nav completely covers this. Some text like the [Overview of Mitiq](https://mitiq.readthedocs.io/en/stable/guide/guide-overview.html) is an option.
- Make the [Mitiq README](https://mitiq.readthedocs.io/en/stable/readme.html) the landing page - this looks way nicer - and get rid of the current landing page.

**Comment by rmlarose** [comment]
Adding this to the 0.10 milestone. If we can get this and #813 done, the documentation will be in much better shape.

**Comment by rmlarose** [comment]
I would ditto this for the [examples landing page](https://mitiq.readthedocs.io/en/stable/examples/examples.html). Again just shows a huge TOC (which is automatically included on the left nav on RTD).

![image](https://user-images.githubusercontent.com/32416820/125992299-e88a6bf4-6c0a-4845-945a-52a206c70494.png)

**Comment by crazy4pi314** [comment]
So pretty much the only thing I found other than just omitting H2 headings from these TOCs is this sphinx extension: https://sphinx-panels.readthedocs.io/en/latest/

@rmlarose can you elaborate more on what you think would address this issue and if this package would help?

**Comment by rmlarose** [comment]
I think the panels extensions looks nice and like a good (relatively easy?) option to pursue! I particularly like that you can [add images to panels](https://sphinx-panels.readthedocs.io/en/latest/#image-caps) and [make them clickable links](https://sphinx-panels.readthedocs.io/en/latest/#link-buttons). This could be really cool for tutorials which produce a plot - the image could be the plot produced, and clicking on it shows the code to make the plot.

Thanks for looking into this!

**Comment by rmlarose** [comment]
My only other comment is how sphinx-panels relates to / integrates with #813. I would value easily-runnable online docs over visuals if we had to pick.

**Comment by crazy4pi314** [comment]
I think the only reasonable option that isn't massive overhead is to drop it to the first level headers instead of depth 2. That will shorten the lists to hopefully just the main topics. I personally am not a fan of this as I often click the subheadings to get exactly where I want, but I don't have any strong feelings.

**Comment by crazy4pi314** [comment]
Also for #813 jupyter book already uses the panels extension: https://jupyterbook.org/explain/sphinx.html#how-to-replicate-jupyter-books-functionality-in-sphinx

**Comment by crazy4pi314** [comment]
I think I would rather table this for now, I would rather address this when/if there is a tool that can help better. Closing but can re-open whenever.
