### ISSUE TITLE
Mitiq contributor survey

### ISSUE THREAD

**Issue by crazy4pi314** [unitaryfund/mitiq#858]
Hi All!

The Mitiq maintainers are starting to do some user surveys for folks who use, develop, or want to use Mitiq and were wondering if folks would be willing to participate in a short in-person interview (~10 min)? If so, please [send us and email](mailto:sarah@unitary.fund) and we can setup a time convent for you.

If you don't have time to chat in person, we also have [a survey](https://bit.ly/mitiq-survey) that would be super helpful if you could drop some thoughts in!

Thanks to our amazing community for helping us make Mitiq the best tool it can be! 💛🌴

**Comment by crazy4pi314** [comment]
Ping @Yash-10 @LogMoss @sid1993

**Comment by sid1993** [comment]
I have filled up the survey and would be happy to get on a call if needed.

**Comment by crazy4pi314** [comment]
@sid1993 Thanks so much! 💖
