### ISSUE TITLE
Randomized compiling

### ISSUE THREAD

**Issue by eliottrosenberg** [unitaryfund/mitiq#864]
It would be great if Mitiq could perform randomized compiling. I am happy to work on this but would like to collaborate with someone who is more familiar with the source code.

It should be simple to implement. Each CNOT gate gets padded by 1-qubit gates that ideally don't affect the outcome.

Refs:
arXiv:1512.01098, 1807.04973, 1906.06270, 2103.08591

**Comment by crazy4pi314** [comment]
Thanks for filing this @eliottrosenberg 💪 I know myself and the team would be happy to help, feel free to ask questions/bounce ideas here or in the discord channel, and we have our regular community call every friday at 9am PDT where the whole team will be there to discuss issues/PRs/Roadmap topics!
