### ISSUE TITLE
Add Mitiq to conda-forge package source for conda

### ISSUE THREAD

**Issue by crazy4pi314** [unitaryfund/mitiq#869]
### Problem

Right now you can only install Mitiq from pip, which is common, but much harder to correctly resolve dependency conflicts as well as manage requirements outside of python (some of our dependencies may need to be built from source). Especially for windows development and users, having a conda package would make a lot of issues moot ( see #839, #837, #620, #416 to name a few).

### Rough requirements

- Decide if we want our own conda channel or just use conda-forge (prefered)
- Need to decide if we build our package in our CI and push to conda-forge or use their feedstock template repos (See [QuTiP example](https://github.com/conda-forge/qutip-feedstock/blob/master/recipe/meta.yaml))
- Resolve how to handle some of our dependencies (really only quantum packages circ, qiskit, and braket) that are not on conda. This could be we make a package for them (totally fine, don't need to be source owner). Else there are ways to bring in source and build as a part of the conda packaging process.

### Relevant/helpful links
- [GitHub action that would keep versions in the conda file up to date](https://github.com/marketplace/actions/conda-action)
- [Building a conda package from scratch](https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs.html)
- [Blog guide to setting up simple conda packages](https://medium.com/runic-software/simple-guide-to-conda-packages-4658cee798d6)

**Comment by jordandsullivan** [comment]
Since our [requirements](https://github.com/unitaryfund/mitiq/blob/master/requirements.txt) are all python packages on PyPI (i.e. none need to be built from source) and we haven't received any user requests for this integration, I'm inclined to not add conda support as something we need to add to our maintenance of the project. I will close unless someone has a strong opinion to the contrary.
