### ISSUE TITLE
Upgrade Cirq to 0.12.0

### ISSUE THREAD

**Issue by crazy4pi314** [unitaryfund/mitiq#896]
Pre-Report Checklist
--------------------

- [x] I am running the latest version of mitiq
- [x] I checked to make sure that this bug has not already been reported

Issue Description
-----------------

We use Cirq as a core dependency, and the newest version (we are 2 minor releases behind) has a [lot of big changes](https://github.com/quantumlib/Cirq/releases/tag/v0.12.0), like the vendor/backend support was pulled out into separate pip packages. Also notable, there is a circ-rigetti package now that includes the QVM servers we run in docker as just local executables which could make our own dev and packaging story much easier.

The changelog should be reviewed, and decide what and how we upgrade/adapt mitiq requirements to allow functionality with these major changes.

**Comment by rmlarose** [comment]
Not upgrading Cirq until Cirq 0.14 - module deprecation `cirq_google` as `cirq.google` for backwards compatibility causes errors with Sphinx docs. See #915.
