### ISSUE TITLE
Improving PEC documentation

### ISSUE THREAD

**Issue by crazy4pi314** [unitaryfund/mitiq#907]
### Problem

As ZNE was chronologically the first technique supported by Mitiq, there is a bit of an over-representation of its use in the docs more broadly. This roadmap task its to add more content and examples to the docs that use the PEC mitigation technique

### Rough requirements

- Showing examples of using PEC with most backends/integrations.
- If possible, more common tasks that are being run by the community shown with improvements from PEC

**Comment by nathanshammah** [comment]
Closed by #1004.
