### ISSUE TITLE
Enable faster start of interactive notebooks

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#910]
With #841 we added interactive notebooks with Binder. 
However, currently the binder image gets updated against new commits on the `master` branch. 
This means that, given the high frequency of commits merged on master, many users will experience a new build of the image from scratch, instead of finding the saved image that Binder uses when it is on par with the latest `HEAD`.

There are two solutions for this that come to mind:
- 1. Add an action in CI that after every commit to the `unitaryfund/master` branch calls the Binder server and hence creates a new image once again. The reason why I don't like so much this option is that it wastes quite a bit of energy by starting a server every time there is a commit merged to master. Maybe this is not so much a big deal. Probably one could think of a timed action alternatively (like: every day, etc.)
- 2. Ping the latest `stable` release. 
- 2a. Could be done by pinging the `releases` branch, although we have in plan to change that to separate branches for each new release and that would then involve updating the name of the branch every time in the Binder link. 
- 2b. Use a special `binder` branch that in the environment/ requirements contains, along with the dependencies requirements, `- pip: mitiq`, which would pull mitiq from PyPI and install the latest version. Note that pulling from pypi may turn out to be much faster due to the wheels pre-compilation.  

Note that also in options 2a and 2b we could add an action to be fired up every time there is a change, to be sure the waiting time goes down to the minimum.

**Comment by nathanshammah** [comment]
My proposed solution, even if it may be short-lived, is to change the  `master` branch with the `release` in the binder link). We should do it after the next release, as that one contains the `binder/` folder and fast-build instructions.  Then we assess how to change the policy if/when we leave the `release` branch format.

**Comment by crazy4pi314** [comment]
This is likely what will address this issue: https://github.com/jupyterhub/repo2docker-action

We would for each release, build and push a docker image to Docker hub and then cache it on mybinder.org for the fastest possible spin up. I would also consider enabling this on PRs so then it can comment with a link to use a cached binder image from the PR's latest commit: https://github.com/jupyterhub/repo2docker-action#cache-builds-on-mybinderorg-and-provide-a-link
