### ISSUE TITLE
Flaky behavior with ZNE Braket example

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#937]
Sometimes the final plot looks good: (https://mitiq.readthedocs.io/en/latest/examples/braket_mirror_circuit.html)

![image](https://user-images.githubusercontent.com/32416820/134260775-672f2faa-501f-4e52-b166-ac17209c2fb9.png)

Other times its nonsensical: (https://mitiq.readthedocs.io/en/stable/examples/braket_mirror_circuit.html)

![image](https://user-images.githubusercontent.com/32416820/134260846-a78dd8a4-a218-4ee9-ab40-eeec97b73df6.png)

I believe this is due to how the noisy simulation is done with braket.

## Desired behavior

Having the example (https://github.com/unitaryfund/mitiq/blob/master/docs/source/examples/braket_mirror_circuit.md) reliably produce the first plot.

**Comment by andreamari** [comment]
FYI I am repeatedly building the stable docs from the readthedocs admin page untill the correct plot will appear (I hope). Not an optimal solution, but at least it should be enough to fix the stable version of the documentation.

**Comment by nathanshammah** [comment]
That could be understandable for a stochastic (quantum trajectory-like) simulator without many repetitions. But a density matrix simulator should be deterministic, unless is a stochastic ~photocurrent + deterministic simulator. 

I am not sure what is the physics behind `DensityMatrixSimulator`. I see it [here](https://github.com/aws/amazon-braket-default-simulator-python/blob/93ba96712bd03c72ed7006f79d556530d0dfb9ea/src/braket/default_simulator/density_matrix_simulator.py#L25) that itself seems to depend on [`BaseLocalSimulator`](https://github.com/aws/amazon-braket-default-simulator-python/blob/3a32ccae3a6fbad8cc1def555124c8c159853e06/src/braket/default_simulator/simulator.py#L56), but it assumes no noise there. 

There are some noise specifications elsewhere
```
_NOISE_INSTRUCTIONS = frozenset(
    instr.lower().replace("_", "")
    for instr in [
        "amplitude_damping",
        "bit_flip",
        "depolarizing",
        "generalized_amplitude_damping",
        "kraus",
        "pauli_channel",
        "phase_flip",
        "phase_damping",
        "two_qubit_dephasing",
        "two_qubit_depolarizing",
```
Knowing the physics behind the noise simulation is important, even if the simulator stops being inconsistent, so we should find it out.

**Comment by rmlarose** [comment]
> FYI I am repeatedly building the stable docs from the readthedocs admin page untill the correct plot will appear (I hope). Not an optimal solution, but at least it should be enough to fix the stable version of the documentation.

Thanks. Fine as a patch fix while keeping this open until an actual fix.

**Comment by andreamari** [comment]
> > FYI I am repeatedly building the stable docs from the readthedocs admin page untill the correct plot will appear (I hope). Not an optimal solution, but at least it should be enough to fix the stable version of the documentation.
> 
> Thanks. Fine as a patch fix while keeping this open until an actual fix.

@rmlarose  Actually the trick of re-building the stable docs doesn't seem work. I did it several times and the plot looks always bad.

After playing a bit with the example, I realized that the problem is a small bug in the computation of the correct bitstring in mirror circuits (see #940). So the AWS simulator is ok.
