### ISSUE TITLE
Mitiq logo picture not showing in pdf of documentation

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#942]
If one downloads the latest (0.10) release on Read The Docs, the image is not showing in the first pages. See https://mitiq.readthedocs.io/_/downloads/en/stable/pdf/

<img width="454" alt="mitiq-image-missing-docs" src="https://user-images.githubusercontent.com/14573436/134634653-86753b62-b1d0-4830-b524-fc6e3cdb3539.png">

This is not happening for other pages of the documentation that contain logos included in the readme.

Maybe this is due to the way the images are imported?
Mitiq Logo: 
```
# <a href="https://github.com/unitaryfund/mitiq"><img src="https://github.com/unitaryfund/mitiq/blob/master/docs/source/img/mitiq-logo.png?raw=true" alt="Mitiq logo" width="350"/></a>
```
Braket logo
```
<a href="https://github.com/aws/amazon-braket-sdk-python"><img src="https://a0.awsstatic.com/libra-css/images/logos/aws_logo_smile_1200x630.png" alt="AWS logo" width="150"/></a>
```

**Comment by crazy4pi314** [comment]
I'll also add that the contributor picture gallery is also not rendering:
![image](https://user-images.githubusercontent.com/6486256/134738381-bb84b7da-93a9-4f54-bf3e-6f637fcae93f.png)

**Comment by crazy4pi314** [comment]
The possible reasons I could see is that the png url has raw=true at the end, which may or may not be handled by latex correctly. This was linked externally as opposed to a relative reference bc that was the only way to get the readme and the docs to render it the same (afair).

**Comment by nathanshammah** [comment]
keep it open
