### ISSUE TITLE
Add CDR section to Users Guide

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#945]
We need to add the Clifford Data Regression (CDR) section to the Users Guide part of the documentation. An example with the "CDR API" is present already. 

This should appear in the table of contents in Section 2, after PEC. 
 
<img width="863" alt="mitiq-toc-docs" src="https://user-images.githubusercontent.com/14573436/134653632-3321bb9b-8afa-4bdc-9454-508e7fa44036.png">

I can take a first stab at it, as I understand @L-P-B is working on making the CDR example(s) more detailed.

This can be a basic paragraph to start with, plus workflow figure. Related issues on #908 and #944.

**Comment by rmlarose** [comment]
@L-P-B can I assign this to you?

**Comment by L-P-B** [comment]
yes!

**Comment by nathanshammah** [comment]
closed by #1031.
