### ISSUE TITLE
Binder launch badges for PRs

### ISSUE THREAD

**Issue by crazy4pi314** [unitaryfund/mitiq#957]
Pre-Request Checklist
---------------------

- [x] I checked to make sure that this feature has not already been requested.

Issue Description
-----------------

It would be really convient for reviewing PRs to have a premade mybinder link setup that could just be clicked on in the comments of the PR. 

Proposed Solution
-----------------

Binder has docs on how to do this with ready-to-copy GitHub actions: 

https://mybinder.readthedocs.io/en/latest/howto/gh-actions-badges.html

**Comment by AkashNarayanan** [comment]
Hello @crazy4pi314 ! I would like to work on this issue.
