### ISSUE TITLE
User documentation for the PennyLane integration

### ISSUE THREAD

**Issue by crazy4pi314** [unitaryfund/mitiq#974]
Issue Description
-----------------

Support for PennyLane was recently added to master (#836 ) and there should be some documentation in the user guides/examples that shows off this functionality.

**Comment by andreamari** [comment]
Hi @anonymousr007,  the planned timeline for this is more or less the following:

- [End of November] There will be a Mitiq+Pennylane tutorial on the PennyLane website + "official" announcement in a blog post.
- [After the previous point] We could add an additional example also in the Mitiq documentation. Possibly showing something different w.r.t. what is shown in the previous point.

In principle the second point could be done in parallel with the first, however it is probably simpler to wait for the first point to happen.

**Comment by crazy4pi314** [comment]
Thanks @andreamari, hopefully that helps @anonymousr007 :)

**Comment by natestemen** [comment]
This was closed a while ago, but in case anyone comes here and sees that this was closed by a bot, we have the following two examples:
- [Error mitigation with Pennylane on IBMQ backends](https://mitiq.readthedocs.io/en/stable/examples/pennylane-ibmq-backends.html)
- [Estimating the potential energy surface of molecular Hydrogen with ZNE and PennyLane + Cirq](https://mitiq.readthedocs.io/en/stable/examples/molecular_hydrogen_pennylane.html)
