### ISSUE TITLE
Re-consider requiring the full qiskit package instead of its sub-elements

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/mitiq#983]
Some motivations for requiring the full `qiskit` package instead of individual elements are:

- We require `pennylane-qiskit`, which requires `qiskit`.
- By requiring `qiskit` we would avoid `pip/dependabot` installation conflicts of individual elements. E.g. #980. See also this comment by @rmlarose (https://github.com/unitaryfund/mitiq/pull/976#discussion_r726206334).
- The main drawback is the installation of `qiskit-acqua` that we don't need. However, `qiskit-acqua` is deprecated and, in the near future, will be separated from `qiskit` (see first note here: https://github.com/Qiskit/qiskit-aqua).

**Comment by nathanshammah** [comment]
To me it sounds fine given your comments.

**Comment by andreamari** [comment]
This was closed by #993
