### ISSUE TITLE
New docs section for Mitiq backend support

### ISSUE THREAD

**Issue by crazy4pi314** [unitaryfund/mitiq#997]
Issue Description
-----------------

As a part of #908, and as specified by the [RFC](https://docs.google.com/document/d/13un5TZPknSOhmOBkrL2rsofjGfdp2jDnd-DywLpGFPc/edit#heading=h.mckr847qq60k) we want to add a general concepts section to the docs about what backends Mitiq supports.

**Comment by crazy4pi314** [comment]
I was taking a look at the new executor section, and had a question about the backend section. @rmlarose I was looking back at the RFC and am not quite sure how the backends differ from the executor guide page. I think my best guess would be a short page linking to other examples that use the different backends as a part of executors? If not, can you help refresh my memory on what is needed here? Thanks!

**Comment by rmlarose** [comment]
Hey @crazy4pi314 absolutely. I suggest making a "core concepts" doc page on frontends and backends which minimally covers:

- Definition of a "frontend" and a `mitiq.QPROGRAM`
- Definition of a "backend" and emphasis that any backend which accepts a `mitiq.QPROGRAM` is compatible with Mitiq
- Executing programs: Functions with the signature `mitiq.QPROGRAM -> mitiq.QuantumResult`
- Batch executing programs: Functions with the signature `T[mitiq.QPROGRAM] -> T[mitiq.QuantumResult]` where `T` is one of  the types [here](https://github.com/unitaryfund/mitiq/blob/59144fb6ab78ec29ef637223b19cbfdd29fc706c/mitiq/executor/executor.py#L279-L287).

This then feeds into the Executors doc which covers program scheduling, results history, etc.
